void shieldCases(){
add("MA013","living Burn selects7/11 once; later status/reinstallation not recalculated",[]{for(bool burn:{false,true}){auto s=arena();s.enemies[0].burn=burn?1:0;s.enemies[1].dead=true;s.enemies[1].hp=0;s.enemies[1].burn=9;const auto p=plate(s,"MA013");s.enemies[0].burn=burn?0:1;retainedValue(s,p,burn?11:7);}});
add("MA015","Shield8 skips this round Heat decay once; extra copies no later skip",[]{auto s=arena();s.heat=8;plate(s,"MA015");plate(s,"MA015");check(shield(s)==16,"Both physical Shield values");next(s);check(s.heat==8,"Current normal2 loss skipped");end(s);check(s.heat==6,"No extra-copy future skip");});
add("MA018","first complete attack only; blocked attack still counter3 and Heat6 Burn2",[]{for(Amount heat:{5,6}){auto s=arena();s.heat=heat;attack(s,0,1,2);attack(s,1,1);plate(s,"MA018");const auto result=end(s);check(s.hp==1000,"All attacks blocked by6 Shield");check(s.enemies[0].hp==(heat>=6?9995:9997)&&s.enemies[1].hp==10000,"Only first attack counter3, plus same-phase Burn2 tick");check(amount(result,"burn_applied")== (heat>=6?2:0),"Heat6 evaluated after attack");}});
add("MA022","one unused reserve Ammo payment on first install, no effect/reinstall charge",[]{auto s=arena();const auto p=make(s,"MA022");reject(s,Action::install(p));const auto ammo=make(s,"MA023");Action a;a.sacrifices={ammo};install(s,p,a);check(!exists(s,ammo)&&part(s,p).shield==12&&s.heat==0,"Consumes Ammo without its Heat payload");remove(s,p);snapshot(s);install(s,p);check(part(s,p).shield==12&&s.sacrificesRound==1,"Reinstallation no second sacrifice");s=arena();const auto q=make(s,"MA022"),wrong=make(s,"SH002");a=Action::install(q);a.sacrifices={wrong};reject(s,a);});
add("MA024","shown total attack14/15 boundary including multihits; first-install snapshot",[]{for(Amount shown:{14,15,16}){auto s=arena();attack(s,0,7,2);attack(s,1,shown-14);const auto p=plate(s,"MA024");recover(s,0);recover(s,1);retainedValue(s,p,shown>=15?12:9);}});
add("MA028","earlier first-installed Shield count including removed, cap3 and no reinstall count",[]{for(int prior:{0,1,3,4}){auto s=arena();for(int i=0;i<prior;++i){const auto q=plate(s);remove(s,q);install(s,q);remove(s,q);}const auto p=plate(s,"MA028");check(s.firstInstallsRound==prior+1,"Reinstall never increments first-install count");retainedValue(s,p,5+2*std::min(3,prior));}});
add("MA031","living burning enemy count0..4 gives0..12 snapshot; dead excluded",[]{for(int burned:{0,1,3,4}){auto s=arena(5);for(int i=0;i<burned;++i)s.enemies[static_cast<std::size_t>(i)].burn=1;s.enemies.back().dead=true;s.enemies.back().hp=0;s.enemies.back().burn=10;const auto p=plate(s,"MA031");for(auto& enemy:s.enemies)enemy.burn=0;retainedValue(s,p,4*std::min(3,burned));}});
add("MA034","one next-shot check: <=1 Ammo success, failure/removal consumes it, unused expires",[]{for(int mode:{0,1,2}){auto s=arena();const auto p=plate(s,"MA034");if(mode==2)remove(s,p);std::vector<Id> bullet{make(s,"SH001")};if(mode==1)bullet.push_back(make(s,"SH001"));auto first=fire(s,bullet);check(count(first,"part_created")== (mode==0?1:0),"Next shot eligibility checked once");if(mode==2)install(s,p);auto second=shot(s,"SH001");check(count(second,"part_created")==0,"Failed or successful check is consumed, reinstallation cannot rearm");}auto s=arena();const auto p=plate(s,"MA034");remove(s,p);next(s);install(s,p);check(count(shot(s,"SH001"),"part_created")==0,"Unused next-shot check expired at round end");});
add("MA040","first-install Heat4 and Shield7, committed future7 survives removal, no rearm",[]{auto s=arena();s.heat=3;const auto p=make(s,"MA040");reject(s,Action::install(p));s.heat=4;install(s,p);check(s.heat==0&&shield(s)==7,"First install pays exactly4");remove(s,p);snapshot(s);end(s);check(shield(s)==7,"Committed new Shield arrives after old clears even if source removed");collect(s);install(s,p);end(s);check(shield(s)==0,"Saved reinstallation does not repeat delivery/payment");});
add("MA044","first positive-to-zero Shield break restores6 after whole attack, once",[]{auto s=arena();attack(s,0,7,2);attack(s,1,8);plate(s,"MA044");const auto result=end(s);check(s.hp==994,"First two-hit attack loses4 before recovery6, later attack loses2");check(count(result,"part_created")==1&&amount(result,"part_created")==6,"One restoration only");});
add("MA054","HP3 requires4, earlier round HP loss gate excludes its own first payment",[]{auto s=arena();s.hp=3;const auto p=make(s,"MA054");reject(s,Action::install(p));s.hp=4;install(s,p);check(s.hp==1&&s.heat==0&&shield(s)==18,"Own payment alone cannot satisfy previous-loss gate");remove(s,p);install(s,p);check(s.hp==1&&s.heat==0,"No reinstall HP charge");s=arena();use(s,"MA046");const auto before=s.heat;plate(s,"MA054");check(s.heat==before+2&&s.hp==995,"Earlier planning HP loss qualifies then pays3");});
add("MA055","post-enemy remaining active Shield records floor/5 Iron cap3 before reset",[]{for(Amount remaining:{4,5,14,15,20}){auto s=arena();plate(s,"MA055");plate(s);plate(s);Rules::spendShield(s,22-remaining,true);const auto before=s.materials[0];end(s);check(s.materials[0]==before+std::min(3,remaining/5)&&shield(s)==0,"Remaining active Shield converted after attacks and before reset");}});
add("MA057","no enemy attack HP loss grants next4 Heat; planning HP costs excluded",[]{for(Amount attackDamage:{8,9}){auto s=arena();use(s,"MA046");attack(s,0,attackDamage);plate(s,"MA057");end(s);check(s.heat==(attackDamage==8?4:0),"Only enemy attack HP loss breaks Heat refund");}});
add("MA062","Heat0 grants16; Heat1/2/3 grants6 and one saturating loss2; snapshot",[]{for(Amount heat:{0,1,2,3}){auto s=arena();s.heat=heat;const auto p=plate(s,"MA062");check(s.heat==std::max(0,heat-2),"First-install cooling stops at0");const auto expected=heat==0?16:6;s.heat=9;retainedValue(s,p,expected);check(s.heat==9,"Reinstall neither cools nor recalculates");}});
add("MA065","each distinct enemy first attack Burn2, not per hit, even if fully blocked",[]{auto s=arena();attack(s,0,1,3);attack(s,1,1,2);plate(s,"MA065");const auto result=end(s);check(amount(result,"burn_applied")==4&&s.enemies[0].burn==1&&s.enemies[1].burn==1&&s.enemies[2].burn==0,"Two attacking enemies, once each, then normal ticks");check(s.hp==1000,"HP damage not required");});
add("MA070","first-install Shield8+currentHeat, no spending or later recalculation",[]{for(Amount heat:{0,1,8,10}){auto s=arena();s.heat=heat;const auto p=plate(s,"MA070");check(s.heat==heat,"Heat not spent");s.heat=0;retainedValue(s,p,8+heat);}});
add("MA071","first attack with HP loss cools5 and gives12 after it; full block does not trigger",[]{for(Amount hit:{6,7}){auto s=arena();s.heat=9;attack(s,0,hit);attack(s,1,2);plate(s,"MA071");const auto result=end(s);check(s.hp==(hit==6?998:999),"Recovery cannot prevent triggering HP loss");check(amount(result,"part_created")==12,"Only first HP-losing attack creates12");check(s.heat==2,"Cool5 then normal2");}});
add("MA072","first already-burning attacker schedules one Iron across duplicate meshes",[]{auto s=arena();s.enemies[0].burn=1;s.enemies[1].burn=2;attack(s,0,1,2);attack(s,1,1);plate(s,"MA072");plate(s,"MA072");const auto before=s.materials[0];end(s);check(s.materials[0]==before+1,"Duplicate parts and later burning attacker cannot add more Iron");s=arena();attack(s,0,1);plate(s,"MA072");const auto plain=s.materials[0];end(s);check(s.materials[0]==plain,"Unburned attacker gives none");});
add("MA075","first install needs prior different first-installed Shield even if removed; later reinstall legal",[]{auto s=arena();const auto p=make(s,"MA075");reject(s,Action::install(p));const auto first=plate(s);remove(s,first);install(s,p);check(part(s,p).shield==18&&s.firstInstallsRound==2,"Removed earlier Shield still counts");remove(s,p);next(s);install(s,p);check(part(s,p).shield==18&&s.firstInstallsRound==0,"Reinstallation neither rechecks eligibility nor creates first-install count");});
add("MA083","explicit decline or all-current-Heat payment; partial choice rejected, zero legal",[]{for(Amount heat:{0,1,8}){for(bool pay:{false,true}){auto s=arena();s.heat=heat;const auto p=make(s,"MA083");Action a;a.amount=pay?heat:0;install(s,p,a);check(part(s,p).shield==18+(pay?2*heat:0)&&s.heat==(pay?0:heat),"Optional all-Heat payment");}}auto s=arena();s.heat=8;Action bad=Action::install(make(s,"MA083"));bad.amount=3;reject(s,bad);});
add("MA099","next14 only if Heat0 after decay before startup gains; reset precedes arrival",[]{for(Amount heat:{2,3}){auto s=arena();s.heat=heat;use(s,"MA056");plate(s,"MA099");check(shield(s)==22,"Current22");end(s);check(s.heat==(heat==2?1:2),"Steady Burner adds Heat after decay");check(shield(s)==(heat==2?14:0),"Delivery condition sampled before startup gain");}});
add("MA102","remember current Heat capped8; greatest seal survives normal decay once",[]{for(Amount heat:{3,8,10}){auto s=arena();s.heat=heat;plate(s,"MA102");s.heat=1;plate(s,"MA102");end(s);check(s.heat==std::min(8,heat),"Highest remembered amount wins");collect(s);end(s);check(s.heat==std::max(0,std::min(8,heat)-2),"Seal expires after one enemy phase");}});
add("MA104","round1 false; previous enemy attack HP loss yields26, planning HP cost alone12",[]{auto s=arena();check(part(s,plate(s,"MA104")).shield==12,"First round base12");s=arena();attack(s,0,3);next(s);recover(s,0);check(part(s,plate(s,"MA104")).shield==26,"Previous actual attack HP loss adds14");s=arena();use(s,"MA046");next(s);check(part(s,plate(s,"MA104")).shield==12,"Planning cost alone does not count");});
add("MA108","first fully Shield-absorbed attack counter10+Burn3, once; partial attack excluded",[]{for(Amount hit:{2,19}){auto s=arena();attack(s,0,hit);attack(s,1,1);plate(s,"MA108");const auto result=end(s);check(amount(result,"burn_applied")== (hit==2?3:0),"Fully absorbed positive attack only");check(s.enemies[0].hp==(hit==2?9987:10000)&&s.enemies[1].hp==10000,"One counter10 and normal same-phase Burn3 tick");}});
}
