// Independent campaign integration using real cinderwallUpgradeHooks throughout.
// Fixtures constrain shop stock, route position and terminal ammunition; they
// never substitute an upgrade effect or claim a balanced full-city playthrough.
#include "overkill/campaign_session.hpp"
#include "overkill/upgrades.hpp"
#include <Windows.h>
#include <algorithm>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace overkill;
namespace {
int passed=0,failed=0;
void expect(bool value,const std::string& why){if(!value)throw std::runtime_error(why);}
void equal(Amount actual,Amount wanted,const std::string& why){expect(actual==wanted,why+" expected="+std::to_string(wanted)+" actual="+std::to_string(actual));}
void run(const char*name,const std::function<void()>&test){try{test();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
CampaignAction command(const Campaign&c,CampaignActionType type,Id subject=0,std::string choice={}){CampaignAction a;a.runId=c.runId;a.type=type;a.sequence=c.nextTransaction;a.subject=subject;a.choice=std::move(choice);return a;}
CampaignResult act(const CampaignRules&r,Campaign&c,const CampaignAction&a){auto out=r.apply(c,a);expect(out.ok,out.reason);return out;}
void reject(const CampaignRules&r,Campaign&c,const CampaignAction&a){const auto before=serializeCampaign(c);expect(!r.apply(c,a).ok,"expected rejected action");expect(serializeCampaign(c)==before,"rejection mutated campaign");}
void roundtrip(Campaign&c){const auto bytes=serializeCampaign(c);Campaign out;std::string error;expect(deserializeCampaign(bytes,out,error),error);expect(serializeCampaign(out)==bytes,"noncanonical campaign roundtrip");c=std::move(out);}
void combat(const CampaignRules&r,Campaign&c,const Action&a){auto move=command(c,CampaignActionType::Combat);move.combat=a;act(r,c,move);}
Campaign start(const CampaignRules&r,std::uint64_t seed=1,const std::string&mayor="MY1-05"){for(auto n=seed;n<seed+200;++n){auto c=r.newGame(n,"independent-p08-campaign");if(std::find(c.mayorOffers.begin(),c.mayorOffers.end(),mayor)==c.mayorOffers.end())continue;act(r,c,command(c,CampaignActionType::ChooseMayor,0,mayor));c.fight.credits=1000;return c;}throw std::runtime_error("requested Mayor seed not found");}
Id stock(Campaign&c,ProductKind kind,const std::string&id,Amount price=1){const auto product=c.nextId++;c.shop.push_back({product,kind,id,0,1,price});return product;}
void buy(const CampaignRules&r,Campaign&c,ProductKind kind,const std::string&id,Amount price=1){act(r,c,command(c,CampaignActionType::Buy,stock(c,kind,id,price)));}
void preowned(const Rules&r,Campaign&c,const std::string&id){auto out=r.acquireUpgrade(c.fight,id);expect(out.ok,out.reason);expect(c.fight.upgradeRequests.empty()&&c.fight.upgradeChoices.empty(),"fixture needs a no-choice acquisition");c.everAcquired.push_back(id);}
CampaignOffer& offer(Campaign&c){auto it=std::find_if(c.upgradeOffers.begin(),c.upgradeOffers.end(),[](const CampaignOffer&o){return !o.deferred;});expect(it!=c.upgradeOffers.end(),"pending offer absent");return *it;}
void decline(const CampaignRules&r,Campaign&c){auto a=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);a.decline=true;act(r,c,a);}
void resolve(const CampaignRules&r,Campaign&c,const std::string&choice,Id exchange=0){auto a=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id,choice);a.exchange=exchange;act(r,c,a);}
void enter(const CampaignRules&r,Campaign&c){for(const auto&o:routeOffers(c.route))if(o.kind!=EncounterKind::Mystery){act(r,c,command(c,CampaignActionType::EnterOffer,o.id));return;}throw std::runtime_error("combat route choice absent");}
void win(const Rules&fights,const CampaignRules&r,Campaign&c){if(c.fight.phase==Phase::Collection)combat(r,c,Action::collect(0));for(int i=0;i<10&&c.phase==CityPhase::Fight;++i){auto enemy=std::find_if(c.fight.enemies.begin(),c.fight.enemies.end(),[](const Enemy&e){return !e.dead&&!e.escaped;});expect(enemy!=c.fight.enemies.end(),"living target absent");const Id target=enemy->id;expect(fights.grantPlainPart(c.fight,Kind::Ammo,1000,"qa-terminal-fixture").ok,"terminal fixture grant");combat(r,c,Action::load({c.fight.parts.back().id}));combat(r,c,Action::fire(target));}expect(c.phase==CityPhase::Rewards,"terminal fixture did not reach rewards");}
void advance(const CampaignRules&r,Campaign&c){act(r,c,command(c,CampaignActionType::RequestAdvance));if(c.skipConfirmation)act(r,c,command(c,CampaignActionType::ConfirmAdvance));}
void enterExchange(const CampaignRules&r,Campaign&c){while(c.route.position<12){for(const auto&o:routeOffers(c.route))if(o.mystery=="C1-M-EXCHANGE"){act(r,c,command(c,CampaignActionType::EnterOffer,o.id));return;}std::string error;expect(selectRouteOffer(c.route,routeOffers(c.route).front().id,error),error);expect(completeRouteNode(c.route,error),error);}throw std::runtime_error("controlled route has no Exchange Mystery");}
Campaign exchangeReady(const CampaignRules&r){for(std::uint64_t seed=1;seed<100;++seed){auto c=start(r,seed);auto route=c.route;while(route.position<12){for(const auto&o:routeOffers(route))if(o.mystery=="C1-M-EXCHANGE")return c;std::string error;expect(selectRouteOffer(route,routeOffers(route).front().id,error),error);expect(completeRouteNode(route,error),error);}}throw std::runtime_error("Exchange seed not found");}
Campaign technicianReady(const CampaignRules&r){for(std::uint64_t seed=1;seed<100;++seed){auto c=start(r,seed);while(c.route.position<12){for(const auto&o:routeOffers(c.route))if(o.mystery=="C1-M-TECH"){c.fight.hp=17;for(const auto&id:eligibleUpgradeIds())if(id!="UGS-039")if(std::find(c.everAcquired.begin(),c.everAcquired.end(),id)==c.everAcquired.end())c.everAcquired.push_back(id);act(r,c,command(c,CampaignActionType::EnterOffer,o.id));return c;}std::string error;expect(selectRouteOffer(c.route,routeOffers(c.route).front().id,error),error);expect(completeRouteNode(c.route,error),error);}}throw std::runtime_error("Technician seed not found");}
void remember(std::vector<std::string>&ids,const std::string&id){if(std::find(ids.begin(),ids.end(),id)==ids.end())ids.push_back(id);}
std::vector<Id> storage(const Campaign&c,MemoryKind kind){std::vector<Id>ids;for(const auto&copy:c.fight.memory)if(copy.storage==kind)ids.push_back(copy.id);return ids;}
const RecipeCopy& copy(const Campaign&c,Id id){auto it=std::find_if(c.fight.memory.begin(),c.fight.memory.end(),[&](const RecipeCopy&x){return x.id==id;});expect(it!=c.fight.memory.end(),"copy absent");return *it;}
CampaignAction crashAction(const Campaign&c,int mode){if(mode==0){auto it=std::find_if(c.shop.begin(),c.shop.end(),[](const Product&p){return p.definition=="UGS-089"&&p.quantity>0;});expect(it!=c.shop.end(),"crash purchase absent");return command(c,CampaignActionType::Buy,it->id);}auto pending=std::find_if(c.upgradeOffers.begin(),c.upgradeOffers.end(),[](const CampaignOffer&o){return !o.deferred;});expect(pending!=c.upgradeOffers.end(),"crash exchange offer absent");auto a=command(c,CampaignActionType::ResolveUpgradeOffer,pending->id,pending->selected);a.exchange=c.fight.memory.back().id;return a;}
}
int wmain(int argc,wchar_t**argv){Rules fights;CampaignRules rules(fights,cinderwallUpgradeHooks(fights));
if(argc==5&&std::wstring(argv[1])==L"--crash"){CampaignSession session(argv[2],rules);if(!session.load().ok)return 2;auto point=std::stoi(argv[3]),mode=std::stoi(argv[4]);auto out=session.apply(crashAction(session.state(),mode),[point](SavePoint p){if(static_cast<int>(p)==point)ExitProcess(73);});return out.ok?0:3;}
const auto disk=std::filesystem::path(__FILE__).parent_path()/"build"/"artifacts"/std::to_string(GetCurrentProcessId());std::filesystem::create_directories(disk);
run("C-U01 three acquisition recipe offers preserve exchange cursor without victory payout",[&]{
 auto c=start(rules);buy(rules,c,ProductKind::Upgrade,"UGS-069",11);c.memorySlots=static_cast<Amount>(c.fight.memory.size());const auto credit=c.fight.credits;buy(rules,c,ProductKind::Upgrade,"UGS-089",17);equal(c.fight.credits,credit-17,"acquisition paid once");const auto candidates=offer(c).candidates;equal(static_cast<Amount>(candidates.size()),3,"three offers preseeded");resolve(rules,c,candidates[0][0]);expect(offer(c).selected==candidates[0][0],"full-memory selection not saved");roundtrip(c);expect(offer(c).candidates==candidates,"reload rerolled candidates");auto block=command(c,CampaignActionType::OpenShop);reject(rules,c,block);resolve(rules,c,candidates[0][0],c.fight.memory.front().id);equal(offer(c).index,1,"first exchange reentered parent");decline(rules,c);equal(offer(c).index,2,"middle Skip skipped entire bundle");auto final=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id,candidates[2][0]);final.exchange=c.fight.memory.front().id;act(rules,c,final);const auto before=serializeCampaign(c);expect(act(rules,c,final).replayed&&serializeCampaign(c)==before,"duplicate final offer replayed acquisition");expect(c.upgradeOffers.empty()&&c.fight.upgradeRequests.empty()&&c.fight.upgradeResolution.empty(),"finished bundle not cleared");equal(c.fight.credits,credit-17,"acquisition recipes triggered Victory Filing Credit");
});
run("C-U02 exact recipe copy requires different exchange and is once-owned after decline",[&]{
 auto c=start(rules);c.memorySlots=static_cast<Amount>(c.fight.memory.size());const auto original=c.fight.memory.front();buy(rules,c,ProductKind::Upgrade,"UGS-032");auto a=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);a.target=original.id;a.exchange=original.id;reject(rules,c,a);a.exchange=0;act(rules,c,a);expect(offer(c).selected==std::to_string(original.id),"pending source selection not saved");roundtrip(c);decline(rules,c);expect(copy(c,original.id).recipe==original.recipe,"decline removed source");expect(ownedUpgrade(c.fight,"UGS-032")!=nullptr,"decline removed upgrade ownership");auto duplicate=command(c,CampaignActionType::Buy,stock(c,ProductKind::Upgrade,"UGS-032"));reject(rules,c,duplicate);
});
run("C-U03 Utility memory is empty capacity and cannot store Ammo",[&]{
 auto c=start(rules);c.memorySlots=static_cast<Amount>(c.fight.memory.size());buy(rules,c,ProductKind::Upgrade,"UGS-100");expect(storage(c,MemoryKind::Utility).empty(),"acquisition moved existing copies or filled new slots");buy(rules,c,ProductKind::Recipe,"SH074");equal(static_cast<Amount>(storage(c,MemoryKind::Utility).size()),1,"new Utility slot");auto ammo=stock(c,ProductKind::Recipe,"SH001");reject(rules,c,command(c,CampaignActionType::Buy,ammo));buy(rules,c,ProductKind::Recipe,"MA035");equal(static_cast<Amount>(storage(c,MemoryKind::Utility).size()),2,"second Utility slot");auto bad=command(c,CampaignActionType::Buy,ammo);bad.exchange=storage(c,MemoryKind::Utility).front();reject(rules,c,bad);bad.exchange=storage(c,MemoryKind::General).front();act(rules,c,bad);roundtrip(c);equal(static_cast<Amount>(storage(c,MemoryKind::Utility).size()),2,"general exchange disturbed Utility slots");
});
run("C-U04 Borrowed choice is extra, deterministic on Continue, uncopyable and removed at victory",[&]{
 auto c=start(rules);c.memorySlots=static_cast<Amount>(c.fight.memory.size());buy(rules,c,ProductKind::Upgrade,"UGS-133");enter(rules,c);const auto options=offer(c).candidates;equal(static_cast<Amount>(options.front().size()),3,"three Borrowed choices");for(const auto&id:options.front()){expect(id.rfind("SH",0)==0,"Borrowed offered mercenary recipe");expect(fights.recipe(id)->rarity==Rarity::Common,"Borrowed offered non-Common");}auto invalid=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);invalid.decline=true;reject(rules,c,invalid);resolve(rules,c,options.front().front());expect(storage(c,MemoryKind::Borrowed).size()==1,"temporary extra slot absent");const auto firstFight=serialize(c.fight);roundtrip(c);act(rules,c,command(c,CampaignActionType::Continue));expect(offer(c).candidates==options,"Continue rerolled borrowed definitions");resolve(rules,c,options.front().front());expect(serialize(c.fight)==firstFight,"Continue duplicated entry state");const auto borrowed=storage(c,MemoryKind::Borrowed).front();if(c.fight.phase==Phase::Collection)combat(rules,c,Action::collect(0));buy(rules,c,ProductKind::Upgrade,"UGS-032");expect(std::find(offer(c).copies.begin(),offer(c).copies.end(),borrowed)==offer(c).copies.end(),"Borrowed included in permanent-copy choices");auto forbidden=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);forbidden.target=borrowed;reject(rules,c,forbidden);decline(rules,c);win(fights,rules,c);expect(storage(c,MemoryKind::Borrowed).empty(),"Borrowed recipe survived fight cleanup");equal(static_cast<Amount>(c.fight.memory.size()),c.memorySlots,"cleanup removed or added permanent copies");roundtrip(c);
});
run("C-U05 Surveyor decline and exhausted pool keep one normal Mystery credit",[&]{
 for(bool exhausted:{false,true}){auto c=exchangeReady(rules);buy(rules,c,ProductKind::Upgrade,"UGS-113");if(exhausted)for(const auto&id:eligibleUpgradeIds())remember(c.everAcquired,id);enterExchange(rules,c);const auto credit=c.fight.credits;auto leave=command(c,CampaignActionType::LeaveMystery);act(rules,c,leave);if(!exhausted){expect(offer(c).source=="UGS-113","Surveyor decision absent");equal(c.fight.credits,credit,"normal credit paid before decision");roundtrip(c);decline(rules,c);}equal(c.fight.credits,credit+10,"decline/exhaustion normal10 exactly once");const auto bytes=serializeCampaign(c);expect(act(rules,c,leave).replayed&&serializeCampaign(c)==bytes,"Mystery request repeated");expect(c.upgradeOffers.empty()&&c.fight.upgradeRequests.empty(),"completed Surveyor request retained");}
});
run("C-U06 nested upgrade acquisition acknowledges parent before forced copy choice",[&]{
 auto c=exchangeReady(rules);buy(rules,c,ProductKind::Recipe,"SH012");const auto a=c.fight.memory.back().id;buy(rules,c,ProductKind::Recipe,"SH012");const auto b=c.fight.memory.back().id;buy(rules,c,ProductKind::Upgrade,"UGS-113");for(const auto&u:rules.content().upgrades)if(u.rarity==1&&u.id!="UGS-145")remember(c.everAcquired,u.id);enterExchange(rules,c);act(rules,c,command(c,CampaignActionType::LeaveMystery));expect(offer(c).candidates.front()==std::vector<std::string>{"UGS-145"},"single eligible nested result differs");resolve(rules,c,"UGS-145");expect(c.upgradeOffers.empty()&&c.fight.upgradeChoices.size()==1,"parent was not acked before child");roundtrip(c);auto answer=command(c,CampaignActionType::ResolveUpgradeChoice);answer.combat.type=ActionType::ResolveUpgradeChoice;answer.combat.upgradeChoice.choice=c.fight.upgradeChoices.front().id;answer.combat.upgradeChoice.objects={a,b};act(rules,c,answer);const auto bytes=serializeCampaign(c);expect(act(rules,c,answer).replayed&&serializeCampaign(c)==bytes,"child choice reapplied tags");expect(c.fight.upgradeChoices.empty()&&c.fight.upgradeRequests.empty()&&c.fight.upgradeResolution.empty(),"nested frame not finished");equal(static_cast<Amount>(copy(c,a).tags.size()),1,"one tag per selected copy");
});
run("C-U07 ever-acquired exhaustion pays Compass30 only after fifth victory",[&]{
 auto c=start(rules);preowned(fights,c,"UGS-150");for(const auto&id:eligibleUpgradeIds())remember(c.everAcquired,id);const auto credit=c.fight.credits;for(int won=1;won<=6;++won){enter(rules,c);win(fights,rules,c);equal(c.fight.credits,credit+(won>=5?30:0),"fifth-only exhaustion credit");expect(c.upgradeOffers.empty(),"exhausted pool offered already acquired ID");roundtrip(c);if(won<6)advance(rules,c);}expect(ownedUpgrade(c.fight,"UGS-150")&&ownedUpgrade(c.fight,"UGS-150")->charges==0,"spent Compass state absent");
});
run("C-U08 real license charge and midfight purchase roll back on Continue",[&]{
 auto c=start(rules);preowned(fights,c,"UGS-015");const auto purchase=stock(c,ProductKind::Upgrade,"UGS-075",19);enter(rules,c);equal(ownedUpgrade(c.fight,"UGS-015")->charges,2,"one entry charge");const auto entryFight=serialize(c.fight);const auto credit=c.fight.credits;combat(rules,c,Action::collect(0));buy(rules,c,ProductKind::Recipe,"SH074",7);act(rules,c,command(c,CampaignActionType::Buy,purchase));expect(ownedUpgrade(c.fight,"UGS-075")!=nullptr,"midfight purchase absent");roundtrip(c);for(int i=0;i<3;++i){act(rules,c,command(c,CampaignActionType::Continue));expect(serialize(c.fight)==entryFight,"Continue changed real entry effects or charge");equal(c.fight.credits,credit,"purchase money escaped rollback");expect(ownedUpgrade(c.fight,"UGS-075")==nullptr,"midfight upgrade escaped rollback");expect(std::find(c.everAcquired.begin(),c.everAcquired.end(),"UGS-075")==c.everAcquired.end(),"midfight ever-acquired escaped rollback");}
});
run("C-U09 shop discount does not discount its own acquisition or replay",[&]{
 auto c=start(rules);const auto credit=c.fight.credits;buy(rules,c,ProductKind::Upgrade,"UGS-075",19);equal(c.fight.credits,credit-19,"self discount incorrectly retroactive");const auto id=stock(c,ProductKind::Recipe,"SH001",19);auto purchase=command(c,CampaignActionType::Buy,id);act(rules,c,purchase);equal(c.fight.credits,credit-34,"later price floor19x.8=15");const auto bytes=serializeCampaign(c);expect(act(rules,c,purchase).replayed&&serializeCampaign(c)==bytes,"duplicate discounted purchase charged again");
});
run("C-U12 moving Utility slots preserves physical copy tags and rejects fight/capacity violations",[&]{
 auto c=start(rules);buy(rules,c,ProductKind::Recipe,"SH074");const auto a=c.fight.memory.back().id;buy(rules,c,ProductKind::Recipe,"SH074");const auto b=c.fight.memory.back().id;buy(rules,c,ProductKind::Upgrade,"UGS-144");auto selection=command(c,CampaignActionType::ResolveUpgradeChoice);selection.combat.type=ActionType::ResolveUpgradeChoice;selection.combat.upgradeChoice.choice=c.fight.upgradeChoices.front().id;selection.combat.upgradeChoice.objects={a,b};act(rules,c,selection);buy(rules,c,ProductKind::Upgrade,"UGS-100");enter(rules,c);combat(rules,c,Action::collect(0));combat(rules,c,Action::craft(a));win(fights,rules,c);advance(rules,c);const auto original=copy(c,a);const auto idCounter=c.fight.nextId;auto move=command(c,CampaignActionType::MoveRecipeCopy,a,"utility");act(rules,c,move);expect(copy(c,a).storage==MemoryKind::Utility&&copy(c,a).recipe==original.recipe,"move replaced physical recipe");expect(c.fight.nextId==idCounter,"move allocated a new copy ID");expect(copy(c,a).tags.size()==original.tags.size()&&copy(c,a).tags[0].source==original.tags[0].source&&copy(c,a).tags[0].usedFight==original.tags[0].usedFight&&copy(c,a).tags[0].order==original.tags[0].order,"move reset calibration or first-use history");act(rules,c,command(c,CampaignActionType::MoveRecipeCopy,b,"utility"));auto third=std::find_if(c.fight.memory.begin(),c.fight.memory.end(),[&](const RecipeCopy&x){return x.id!=a&&x.id!=b&&fights.recipe(x.recipe)->kind==Kind::Utility;});expect(third!=c.fight.memory.end(),"third Utility fixture absent");reject(rules,c,command(c,CampaignActionType::MoveRecipeCopy,third->id,"utility"));reject(rules,c,command(c,CampaignActionType::MoveRecipeCopy,c.fight.memory.front().id,"utility"));act(rules,c,command(c,CampaignActionType::MoveRecipeCopy,a,"general"));roundtrip(c);enter(rules,c);reject(rules,c,command(c,CampaignActionType::MoveRecipeCopy,a,"utility"));
});
run("C-U13 cancel staged exchange keeps paid ownership and all seeded candidates",[&]{
 auto c=start(rules);c.memorySlots=static_cast<Amount>(c.fight.memory.size());buy(rules,c,ProductKind::Upgrade,"UGS-089",17);const auto candidates=offer(c).candidates;const auto request=offer(c).request;const auto money=c.fight.credits;resolve(rules,c,candidates.front().front());act(rules,c,command(c,CampaignActionType::CancelUpgradeExchange,offer(c).id));expect(offer(c).selected.empty()&&offer(c).index==0&&offer(c).request==request&&offer(c).candidates==candidates,"cancel discarded or rerolled offer");equal(c.fight.credits,money,"cancel refunded/recharged acquisition");roundtrip(c);resolve(rules,c,candidates.front().back(),c.fight.memory.front().id);equal(offer(c).index,1,"replacement selection did not complete first offer");
});
run("C-U14 Technician plus Risky Calibration validates combined16HP before commit",[&]{
 auto c=technicianReady(rules);expect(c.rewards.size()==1&&c.rewards.front().choices==std::vector<std::string>{"UGS-039"},"controlled eligible calibration offer absent");auto take=command(c,CampaignActionType::AcceptCalibration,0,"UGS-039");c.fight.hp=16;reject(rules,c,take);c.fight.hp=17;act(rules,c,take);equal(c.fight.hp,1,"outer8 and inner8 HP payment");expect(c.fight.upgradeChoices.size()==1,"nested permanent tuning choice absent");roundtrip(c);Id ammo=0,shield=0;for(const auto&x:c.fight.memory){if(fights.recipe(x.recipe)->kind==Kind::Ammo)ammo=x.id;if(fights.recipe(x.recipe)->kind==Kind::Shield)shield=x.id;}auto answer=command(c,CampaignActionType::ResolveUpgradeChoice);answer.combat.type=ActionType::ResolveUpgradeChoice;answer.combat.upgradeChoice.choice=c.fight.upgradeChoices.front().id;answer.combat.upgradeChoice.objects={ammo,shield};act(rules,c,answer);equal(c.fight.hp,1,"nested resolution repeated HP payment");expect(c.phase==CityPhase::Between&&c.fight.upgradeChoices.empty(),"nested calibration did not finish");
});
run("C-U15 two earned deferred subscriptions remain usable after one copy becomes ineligible",[&]{
 auto c=start(rules,1,"MY1-13");c.fight.memory.clear();
 // Empty memory is controlled setup. The six victories and both entitlements
 // below are generated by real combat completion and MY1-13 effects.
 for(int victory=1;victory<=6;++victory){auto regular=std::find_if(routeOffers(c.route).begin(),routeOffers(c.route).end(),[](const RouteOffer&o){return o.kind==EncounterKind::Regular;});expect(regular!=routeOffers(c.route).end(),"Regular route fixture absent");act(rules,c,command(c,CampaignActionType::EnterOffer,regular->id));win(fights,rules,c);advance(rules,c);}
 equal(static_cast<Amount>(c.upgradeOffers.size()),2,"two earned saved entitlements");for(const auto&o:c.upgradeOffers)expect(o.deferred,"empty memory must defer subscription");buy(rules,c,ProductKind::Recipe,"SH001");const auto firstCopy=c.fight.memory.back().id;auto one=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);one.target=firstCopy;one.material=0;act(rules,c,one);expect(c.upgradeOffers.size()==1&&c.upgradeOffers.front().deferred,"second entitlement kept a stale now-ineligible copy and blocks shopping");roundtrip(c);buy(rules,c,ProductKind::Recipe,"SH002");const auto secondCopy=c.fight.memory.back().id;expect(offer(c).copies==std::vector<Id>{secondCopy},"second entitlement did not refresh exact eligible-copy set");auto two=command(c,CampaignActionType::ResolveUpgradeOffer,offer(c).id);two.target=secondCopy;two.material=1;act(rules,c,two);expect(c.upgradeOffers.empty(),"second earned entitlement stuck");expect(copy(c,firstCopy).tags.size()==1&&copy(c,secondCopy).tags.size()==1,"subscription lost or applied twice");roundtrip(c);
});
for(int mode=0;mode<2;++mode)run(mode==0?"C-U10 actual process exits preserve acquisition plus nested offers atomically":"C-U11 actual process exits preserve nested memory exchange atomically",[&]{
 auto before=start(rules);before.memorySlots=static_cast<Amount>(before.fight.memory.size());stock(before,ProductKind::Upgrade,"UGS-089",17);if(mode==1){act(rules,before,crashAction(before,0));resolve(rules,before,offer(before).candidates.front().front());}const auto action=crashAction(before,mode);auto after=before;act(rules,after,action);const auto oldBytes=serializeCampaign(before),newBytes=serializeCampaign(after);
 std::vector<wchar_t> exe(32768);const auto length=GetModuleFileNameW(nullptr,exe.data(),static_cast<DWORD>(exe.size()));expect(length>0&&length<exe.size(),"executable path");
 for(int point=0;point<4;++point){auto path=disk/("p08-"+std::to_string(mode)+"-"+std::to_string(point)+".ofsave");const auto seeded=SaveStore(path).commit(oldBytes,"");expect(seeded.ok,seeded.error);std::wstring args=L"\""+std::wstring(exe.data(),length)+L"\" --crash \""+path.wstring()+L"\" "+std::to_wstring(point)+L" "+std::to_wstring(mode);STARTUPINFOW startup{};startup.cb=sizeof(startup);startup.dwFlags=STARTF_USESHOWWINDOW;startup.wShowWindow=SW_HIDE;PROCESS_INFORMATION child{};expect(CreateProcessW(nullptr,args.data(),nullptr,nullptr,FALSE,CREATE_NO_WINDOW,nullptr,nullptr,&startup,&child)!=0,"launch crash child");const auto waited=WaitForSingleObject(child.hProcess,10000);DWORD code=0;GetExitCodeProcess(child.hProcess,&code);CloseHandle(child.hThread);CloseHandle(child.hProcess);expect(waited==WAIT_OBJECT_0&&code==73,"actual requested process exit absent");CampaignSession loaded(path,rules);const auto read=loaded.load();expect(read.ok,read.reason);expect(serializeCampaign(loaded.state())==(point<2?oldBytes:newBytes),"partial nested upgrade transaction persisted");const auto retry=loaded.apply(action);expect(retry.ok&&retry.replayed==(point>=2),"retry disagrees with durable receipt");expect(serializeCampaign(loaded.state())==newBytes,"retry duplicated upgrade/choice/payment");std::cout<<"PASS process exit mode="<<mode<<" boundary="<<point<<" exit=73\n";}
});
std::cout<<"SUMMARY "<<passed<<" passed, "<<failed<<" failed\n";return failed?1:0;
}
