"""Compile offer/price metadata from the reviewed manifest; no gameplay effects."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RARITIES = ["Base", "Common", "Uncommon", "Rare", "Legendary"]


def quote(value):
    # ASCII source containing UTF-8 bytes is portable across MSVC source codepages.
    out = '"'
    for byte in str(value).encode("utf-8"):
        if byte == 34:
            out += '\\"'
        elif byte == 92:
            out += "\\\\"
        elif 32 <= byte < 127:
            out += chr(byte)
        else:
            out += f"\\{byte:03o}"
    return out + '"'


def strings(values):
    return "{" + ",".join(quote(x) for x in values) + "}"


def compile_metadata():
    manifest_bytes = (ROOT / "content/cinderwall.manifest.json").read_bytes()
    manifest = json.loads(manifest_bytes)
    snapshot = json.loads((ROOT / "content/catalogue.snapshot.json").read_text(encoding="utf-8"))
    out = ["// Generated by tools/compile_city_content.py; effects remain in C++ rules.",
           f"result.manifestHash={quote(hashlib.sha256(manifest_bytes).hexdigest())};"]
    for kind, key in [("recipes", "eligible_recipe_ids"), ("upgrades", "eligible_upgrade_ids")]:
        prices = manifest["shop"]["recipe_prices" if kind == "recipes" else "upgrade_prices"]
        overrides = manifest["shop"].get("upgrade_price_overrides", {}) if kind == "upgrades" else {}
        out.append(f"result.{kind}={{")
        for identity in manifest[key]:
            row = snapshot[kind][identity]
            price = overrides.get(identity, prices.get(row["rarity"], 0))
            out.append("{" + ",".join([quote(identity), quote(row["name"]), quote(row["effect"]),
                                      str(RARITIES.index(row["rarity"])), str(price)]) + "},")
        out.append("};")
    for key, member in [("recipe_pools", "recipePools"), ("upgrade_pools", "upgradePools"), ("mayor_pools", "mayorPools")]:
        out.append(f"result.{member}={{")
        for source, pool in sorted(manifest[key].items()):
            weights = "{" + ",".join(str(pool["rarity_weights"].get(x, 0)) for x in RARITIES) + "}"
            out.append("{" + quote(source) + "," + strings(pool["ids"]) + "," + weights + "},")
        out.append("};")
    out.append("result.starters=" + strings(manifest["starter_recipe_ids"]) + ";")
    for member, values in [("materialPrices", manifest["shop"]["material_unit_prices"]),
                           ("materialStock", manifest["shop"]["material_stock_by_city"]["1"])]:
        out.append(f"result.{member}={{" + ",".join(map(str, values)) + "};")
    out.append("result.coreValues={")
    for robot in manifest["robot_ids"]:
        values = manifest["core_values"][robot]
        if len(values) != 1:
            raise ValueError(f"Cinderwall body reference must be singular: {robot}")
        out.append("{" + quote(robot) + "," + str(values[0]) + "},")
    out.append("};")
    for member, value in [("memorySlots", manifest["campaign"]["initial_memory_slots"]),
                          ("startingCredits", manifest["campaign"]["start_credits"]),
                          ("recipeSlots", manifest["shop"]["recipe_offer_slots_by_city"]["1"]),
                          ("upgradeSlots", manifest["shop"]["upgrade_offer_slots_by_city"]["1"])]:
        out.append(f"result.{member}={value};")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = compile_metadata().encode("ascii")
    target = ROOT / "core/src/city_content.generated.inc"
    if args.check:
        if not target.exists() or target.read_bytes() != expected:
            raise SystemExit("City offer metadata is stale; run tools/compile_city_content.py.")
    else:
        target.write_bytes(expected)
    print("City offer metadata: exact manifest projection; no runtime-effect certification.")


if __name__ == "__main__":
    main()
