"""Compile original animation metadata into the cosmetic Unreal adapter.

No gameplay quantities are copied here. Hits and summons still need committed
core events; these rows only identify assets and their display cue times.
"""
import argparse
import hashlib
import json
from pathlib import Path

GAME = Path(__file__).resolve().parents[1]
OUTPUT = GAME / "unreal/Source/OverkillFoundry/Private/FoundryRosterData.inl"


def generate():
    robots, clips, cues, identities = [], [], [], []
    legacy = {"BreachRam": ("C1-R02", "BR_"), "RivetMite": ("C1-R01", "RM_")}
    for version in ("cinderwall-v001", "roster-v001"):
        path = GAME / "assets/production" / version / "asset-report.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        # A portable text identity is stable through Git's newline conversion.
        digest = hashlib.sha256(path.read_text(encoding="utf-8").encode()).hexdigest()
        identities.append(f"// {path.relative_to(GAME).as_posix()} sha256-lf={digest}")
        for name, robot in data["robots"].items():
            definition, prefix = legacy[name] if name in legacy else (robot["source_id"], robot["prefix"])
            robots.append(f'    {{TEXT("{definition}"), TEXT("SK_{name}"), {len(robot["materials"])}}},')
            for asset, clip in data["clips"].items():
                if not asset.startswith(prefix):
                    continue
                assert clip["gameplay_authority"] is False
                key = asset[len(prefix):]
                if key in ("attack_blast", "attack_rivet"):
                    key = "attack"
                clips.append(f'    {{TEXT("{definition}"), TEXT("{key}"), TEXT("{asset}")}},')
                for cue in clip["events"]:
                    assert 0 <= cue["t"] <= clip["duration_s"]
                    cues.append(f'    {{TEXT("{asset}"), {float(cue["t"]):.3f}f, TEXT("{cue["event"]}"), {cue.get("hit_index", 0)}}},')
    assert len(robots) == 10 and len(clips) == 87
    return "\n".join([
        "// Generated by tools/generate_roster_visuals.py; do not edit.", *identities,
        "namespace FoundryVisualData", "{",
        "struct FRobot { const TCHAR* Definition; const TCHAR* Asset; int32 MaterialSlots; };",
        "struct FClip { const TCHAR* Definition; const TCHAR* Key; const TCHAR* Asset; };",
        "struct FCue { const TCHAR* Asset; float At; const TCHAR* Event; int32 HitIndex; };",
        "static const FRobot Robots[] = {", *robots, "};",
        "static const FClip Clips[] = {", *clips, "};",
        "static const FCue Cues[] = {", *cues, "};", "}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Roster cosmetic table is stale; run tools/generate_roster_visuals.py")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print("Roster cosmetic table: 10 original meshes, 87 clips; metadata matches")
