#pragma once
#include "CoreMinimal.h"
#include "SalvageModel.h"
#include "WorkbenchTutorial.h"
class AMagnetWorkbench;
class APlayerController;
class UStaticMesh;
class UStaticMeshComponent;
class UMaterialInstanceDynamic;
class UMaterialInterface;
class UCameraComponent;
class UCanvas;
class UFont;
class USoundBase;
class UPointLightComponent;
class UAudioComponent;

enum class EMagnetAction : uint8 { None, Sweep, Aim, Dump, UI };
struct FPieceVisual {
 UStaticMeshComponent* Mesh=nullptr;
 UStaticMeshComponent* Ring=nullptr;
 FVector Size=FVector(30,30,10);
 FVector From=FVector::ZeroVector;
 FVector Position=FVector::ZeroVector;
 float Progress=1;
 float Duration=.35f;
 bool bPouring=false;
 int32 Slot=0;
 FVector2D Velocity=FVector2D::ZeroVector;
 float Spin=0;
 float Attracted=0;
 float CaptureDelay=0;
 TArray<UStaticMeshComponent*> Details;
};
struct FForceParticle { FVector Position=FVector::ZeroVector; FVector Velocity=FVector::ZeroVector; FLinearColor Color=FLinearColor::White; float Life=0; float Maximum=1; float Size=2; };
struct FHaulPopup { FVector Position=FVector::ZeroVector; FString Text; FLinearColor Color=FLinearColor::White; float Life=1.2f; };
struct FDemoButton { FBox2D Rect; FString Label; int32 Id=0; bool Enabled=true; };
struct FWorkbenchImpl {
 AMagnetWorkbench* Owner=nullptr;
 APlayerController* PC=nullptr;
 UCameraComponent* Camera=nullptr;
 UFont* RuntimeFont=nullptr;
 UMaterialInterface* Surface=nullptr;
 UMaterialInterface* Overlay=nullptr;
 TMap<FName,UStaticMesh*> Meshes;
 TMap<FName,UMaterialInstanceDynamic*> Materials;
 TMap<FName,USoundBase*> Sounds;
 TArray<TWeakObjectPtr<UAudioComponent>> PlayingSounds;
 TArray<TWeakObjectPtr<UAudioComponent>> PickupVoices;
 TWeakObjectPtr<UAudioComponent> HeavyVoice;
 TSet<int32> SeenRare;
 UAudioComponent* MusicAudio=nullptr;
 UAudioComponent* MagnetAudio=nullptr;
 UAudioComponent* WarningAudio=nullptr;
 UAudioComponent* FurnaceAudio=nullptr;
 UStaticMeshComponent* RecoveredBlock=nullptr;
 TArray<UStaticMeshComponent*> StaticShapes;
 TArray<UStaticMeshComponent*> MagnetShapes;
 TArray<FVector> MagnetOffsets;
 TArray<FVector> MagnetSizes;
 TArray<UStaticMeshComponent*> Coils;
 TArray<UStaticMeshComponent*> ReachParts;
 TArray<UStaticMeshComponent*> StabilizerParts;
 TArray<UStaticMeshComponent*> FieldLights;
 TArray<FForceParticle> Particles;
 TArray<FHaulPopup> Popups;
 TMap<int32,FPieceVisual> Visuals;
 UStaticMeshComponent* FurnaceFill=nullptr;
 UPointLightComponent* FurnaceLight=nullptr;
 MagnetSweep::FSalvageModel Model;
 MagnetSweep::FTutorialProgress Tutorial;
 bool bTutorialPractice=false;
 FString CareerSavePath;
 MagnetSweep::FPullSelection Preview;
 EMagnetAction Action=EMagnetAction::None;
 FVector2D Pointer=FVector2D::ZeroVector;
 FVector2D Magnet=FVector2D(0,-240);
 FVector2D LastMagnet=Magnet;
 FVector2D RawWorld=Magnet;
 FVector2D LastSweepPoint=Magnet;
 bool bLastSweepInTray=false;
 FDelegateHandle InputHandle;
 bool bWorldHit=false;
 bool bInTray=false;
 bool bFurnaceHover=false;
 bool bPaused=false;
 bool bWasFocused=true;
 bool bMuted=false;
 bool bWorkshop=false;
 bool bReceipt=false;
 bool bPrecision=false;
 bool bPrecisionLatched=false;
 bool bFieldLatched=false;
 bool bFieldWasOn=false;
 bool bRiskWasActive=false;
 bool bFailureShown=false;
 float SfxVolume=.8f;
 float MusicVolume=.3f;
 float FieldIntensity=0;
 float Impact=0;
 float FieldRadius=150;
 float MagnetAngle=0;
 float SessionSeconds=0;
 bool bObservedMusic=false,bObservedFieldSound=false,bObservedWarningSound=false;
 int32 SmeltAudioEvents=0,RewardAudioEvents=0,OverloadAudioEvents=0;
 FVector2D MagnetTarget=Magnet;
 FVector2D MagnetVelocity=FVector2D::ZeroVector;
 MagnetSweep::FBankResult LastBank;
 bool bConfirmRetry=false;
 bool bConfirmNew=false;
 bool bPendingNext=false;
 bool bPendingDeposit=false;
 bool bMouseWasDown=false;
 bool bHaulDrag=false;
 int32 HoverRing=INDEX_NONE;
 int32 AimedRing=INDEX_NONE;
 int32 DisplayUpgrade=0;
 int32 Deposits=0;
 int32 Pulls=0;
 int32 Sweeps=0;
 int32 LastBurst=0;
 float Time=0;
 float PickupCooldown=0;
 float RecoveryTimer=0;
 float PourTimer=0;
 float ForgeTimer=0;
 float NoticeTimer=0;
 float SaveTimer=0;
 float FurnacePulse=0;
 FIntPoint WindowedSize=FIntPoint(1600,900);
 float Width=1600, Height=900, UIScale=1, UX=0, UY=0;
 float FrameAverage=1.f/60.f;
 FString NoticeTitle;
 FString NoticeBody;
 FString Profile=TEXT("player");
 FString SavePath;
 FString LastEvent=TEXT("start");
 bool bQA=false;
 TArray<FDemoButton> Buttons;
 FWorkbenchImpl(AMagnetWorkbench* InOwner);
 void Start();
 void Stop();
 void SweepPath();
 void Tick(float Delta);
 void Paint(UCanvas* C);
 void PaintTutorial(UCanvas* C);
 bool TutorialIntro() const;
 bool CanCaptureForPlayer(int32 Id) const;
 void TutorialChanged(bool Changed);
 void UpdateTutorial();
 void EnterTutorialPractice();
 void ReturnFromTutorial();
 void ResetTutorialScene();
 void SetupScene();
 void BuildPieces();
 void UpdateVisuals(float Delta);
 void UpdateAttraction(float Delta);
 void Vent();
 void UpdateAudio(float Delta);
 void AddBurst(FVector Position,FLinearColor Color,int32 Count,float Force=100);
 void SpillVisuals(const TArray<int32>& Released,const TArray<int32>& Destroyed,bool bFailure);
 void BeginJob(int32 Job);
 void PaintEffects(UCanvas* C);
 void UpdatePointer(FVector2D EventPosition=FVector2D(-1,-1));
 void HandlePress();
 void HandleRelease();
 void OnRecovery(const MagnetSweep::FRecoveryResult& Result,bool bPull,int32 Tangled=0);
 void Deposit(bool Next=false);
 void NextDelivery();
 void Button(int32 Id);
 void Pause(bool Value);
 void Toast(const FString& Title,const FString& Body,float Duration=4.f);
 void Play(FName Name,float Volume=1,float Pitch=1);
 UStaticMesh* Mesh(FName Name);
 UMaterialInstanceDynamic* Mat(FName Name,FLinearColor Color,float Metal=.25f,float Rough=.4f,float Glow=0,bool bOverlay=false);
 UStaticMeshComponent* Shape(FName MeshName,FVector Position,FVector Size,FName Material,FRotator Rotation=FRotator::ZeroRotator,bool Static=true);
 void Place(UStaticMeshComponent* Shape,FVector Position,FVector Size,FRotator Rotation=FRotator::ZeroRotator);
 FVector World(FVector2D V,float Z=10) const {return FVector(V.X,V.Y,Z);}
 FVector2D Project(FVector V) const;
 int32 HitButton() const;
 bool Save();
 bool Load();
 bool DecodeSave(const FString& Text);
 FString EncodeSave() const;
 void WriteTelemetry();
 void DrawText(UCanvas* C,const FString& Text,float X,float Y,float Scale,FLinearColor Color,bool Large=false) const;
 void Rect(UCanvas* C,float X,float Y,float W,float H,FLinearColor Color) const;
 void Line(UCanvas* C,FVector2D A,FVector2D B,FLinearColor Color,float Thickness=1) const;
 void WorldCircle(UCanvas* C,FVector2D Center,float Radius,FLinearColor Color,float Thickness=1,float Z=12) const;
};
