// Independent campaign/session tests. P08 effects are explicit controlled hooks.
#include "overkill/campaign_session.hpp"
#include "overkill/robots.hpp"
#include <Windows.h>
#include <algorithm>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace overkill;
namespace {
int passed=0,failed=0;
void expect(bool value,const std::string& message){if(!value)throw std::runtime_error(message);}
void equal(Amount actual,Amount expected,const std::string& message){expect(actual==expected,message+" expected="+std::to_string(expected)+" actual="+std::to_string(actual));}
void run(const char* name,const std::function<void()>& test){try{test();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
CampaignAction command(const Campaign& c,CampaignActionType type,Id subject=0,std::string choice={}){CampaignAction a;a.runId=c.runId;a.type=type;a.sequence=c.nextTransaction;a.subject=subject;a.choice=std::move(choice);return a;}
CampaignResult apply(const CampaignRules& r,Campaign& c,const CampaignAction& a){auto out=r.apply(c,a);expect(out.ok,out.reason);return out;}
void combat(const CampaignRules&r,Campaign&c,const Action&a){auto move=command(c,CampaignActionType::Combat);move.combat=a;apply(r,c,move);}
void roundtrip(Campaign& c){const auto bytes=serializeCampaign(c);Campaign restored;std::string error;expect(deserializeCampaign(bytes,restored,error),error);expect(serializeCampaign(restored)==bytes,"campaign snapshot changed");c=std::move(restored);}
bool validSnapshot(const Campaign& c){try{const auto bytes=serializeCampaign(c);Campaign out;std::string error;return deserializeCampaign(bytes,out,error);}catch(const std::exception&){return false;}}
void reject(const CampaignRules&r,Campaign&c,const CampaignAction&a){const auto before=serializeCampaign(c);expect(!r.apply(c,a).ok,"invalid action accepted");expect(serializeCampaign(c)==before,"rejection changed campaign");}
CampaignHooks hooks(const Rules& fights){CampaignHooks h;
    h.acquireUpgrade=[](Campaign& c,const std::string&,const CampaignAction&){c.upgrades.back().charges=2;return Result{true,{},{}};};
    h.initializeFight=[](Campaign& c,const RouteOffer& o){c.fight.enemies=makeCinderwallFormation(o.formation,o.encounterSeed,o.encounterKey,c.fight.nextId,o.binderDefaultSeen);c.fight.materials[0]+=3;if(!c.upgrades.empty())++c.upgrades.front().fightCount;return Result{true,{},{}};};
    h.combatCompleted=[](Campaign& c){if(!c.upgrades.empty())++c.upgrades.front().campaignCount;return Result{true,{},{}};};
    h.noncombatCompleted=[](Campaign& c){c.fight.credits+=10;if(!c.upgrades.empty())++c.upgrades.front().roundCount;return Result{true,{},{}};};
    h.grantPart=[&fights](Campaign& c,const std::string& id){return fights.grantPart(c.fight,id);};
    h.partSaleValue=[](const Campaign&,const Part&p){return p.materialBasis[0]*2;};return h;
}
Campaign start(const CampaignRules&r,std::uint64_t seed=731,const std::string& id="independent-campaign"){auto c=r.newGame(seed,id);apply(r,c,command(c,CampaignActionType::ChooseMayor,0,c.mayorOffers[0]));return c;}
Id product(const Campaign& c,ProductKind kind,Amount material=0){for(const auto&p:c.shop)if(p.kind==kind&&(kind!=ProductKind::Material||p.material==material)&&p.quantity>0)return p.id;throw std::runtime_error("product absent");}
void enter(const CampaignRules&r,Campaign&c){for(const auto&o:routeOffers(c.route))if(o.formation=="C1-F-RAM"){apply(r,c,command(c,CampaignActionType::EnterOffer,o.id));return;}throw std::runtime_error("Ram offer absent");}
void win(const Rules& fights,const CampaignRules&r,Campaign&c){if(c.fight.phase==Phase::Collection)combat(r,c,Action::collect(0));expect(fights.grantPlainPart(c.fight,Kind::Ammo,1000,"independent-terminal-fixture").ok,"fixture grant failed");const auto id=c.fight.parts.back().id;combat(r,c,Action::load({id}));combat(r,c,Action::fire(c.fight.enemies[0].id));expect(c.phase==CityPhase::Rewards,"fixture did not reach rewards");}
Campaign rewards(const Rules& fights,const CampaignRules&r){auto c=start(r);enter(r,c);win(fights,r,c);return c;}
Id reward(const Campaign& c,RewardKind kind){for(const auto&v:c.rewards)if(v.kind==kind)return v.id;throw std::runtime_error("reward absent");}
const RewardEntry& entry(const Campaign&c,Id id){for(const auto&v:c.rewards)if(v.id==id)return v;throw std::runtime_error("reward absent");}
void advance(const CampaignRules&r,Campaign&c){apply(r,c,command(c,CampaignActionType::RequestAdvance));if(c.skipConfirmation)apply(r,c,command(c,CampaignActionType::ConfirmAdvance));}
Campaign mystery(const CampaignRules&r,const std::string& kind){for(std::uint64_t seed=1;seed<90;++seed){auto c=start(r,seed);while(c.route.position<12){for(const auto&o:routeOffers(c.route))if(o.mystery==kind){apply(r,c,command(c,CampaignActionType::EnterOffer,o.id));return c;}std::string error;expect(selectRouteOffer(c.route,routeOffers(c.route).front().id,error),error);expect(completeRouteNode(c.route,error),error);}}throw std::runtime_error("Mystery seed absent");}
void seedFile(const std::filesystem::path& p,const Campaign& c){const auto out=SaveStore(p).commit(serializeCampaign(c),"");expect(out.ok,out.error);}
CampaignAction crashAction(const Campaign&c,int mode){if(mode==0)return command(c,CampaignActionType::ConfirmAdvance);if(mode==1){auto a=command(c,CampaignActionType::Combat);a.combat=Action::fire(c.fight.enemies[0].id);return a;}auto a=command(c,CampaignActionType::ClaimReward,c.recipeWindow,c.pendingRecipeChoice);a.exchange=c.fight.memory[0].id;return a;}
}
int wmain(int argc,wchar_t**argv){Rules fights;CampaignRules rules(fights,hooks(fights));
if(argc==5&&std::wstring(argv[1])==L"--crash"){CampaignSession s(argv[2],rules);if(!s.load().ok)return 2;const auto point=std::stoi(argv[3]),mode=std::stoi(argv[4]);const auto out=s.apply(crashAction(s.state(),mode),[point](SavePoint p){if(static_cast<int>(p)==point)ExitProcess(73);});return out.ok?0:3;}
const auto disk=std::filesystem::path(__FILE__).parent_path()/"build"/"artifacts"/std::to_string(GetCurrentProcessId());std::filesystem::create_directories(disk);
run("missing P08 executor rejects Mayor acquisition without payment or receipt",[&]{CampaignRules bare(fights);auto c=bare.newGame(1,"no-p08");reject(bare,c,command(c,CampaignActionType::ChooseMayor,0,c.mayorOffers[0]));expect(c.upgrades.empty()&&c.phase==CityPhase::Arrival,"unsupported Mayor acquired");});
run("T11 result cleanup precedes purchases and entry keeps new supplies",[&]{auto c=rewards(fights,rules);expect(c.fight.materials==Materials{}&&c.fight.parts.empty()&&c.entry.empty(),"old fight residue retained");c.fight.credits=50;advance(rules,c);auto buy=command(c,CampaignActionType::Buy,product(c,ProductKind::Material));buy.quantity=2;const auto price=rules.content().materialPrices[0];apply(rules,c,buy);roundtrip(c);equal(c.fight.credits,50-2*price,"purchase money");equal(c.fight.materials[0],2,"purchase inventory");enter(rules,c);equal(c.fight.materials[0],5,"2saved plus explicit3 entry grant");});
run("T12 repeated Continue restores exact inputs and preserves only profile discoveries",[&]{auto c=start(rules);auto buy=command(c,CampaignActionType::Buy,product(c,ProductKind::Material));buy.quantity=2;apply(rules,c,buy);enter(rules,c);const auto originalFight=serialize(c.fight);const auto originalShop=c.shop;const auto originalEntry=c.entry;const auto stockId=product(c,ProductKind::Material);for(int repeat=0;repeat<3;++repeat){apply(rules,c,command(c,CampaignActionType::Buy,stockId));c.upgrades[0].charges=0;c.fight.hp=17;apply(rules,c,command(c,CampaignActionType::OpenShop));const auto discoveries=c.profile.recipes;roundtrip(c);apply(rules,c,command(c,CampaignActionType::Continue));expect(serialize(c.fight)==originalFight,"entry reconstruction differs");expect(c.entry==originalEntry&&c.profile.recipes==discoveries,"checkpoint or profile changed");equal(c.upgrades[0].charges,2,"charge not restored");equal(c.upgrades[0].fightCount,1,"entry hook multiplied");expect(c.shop[0].quantity==originalShop[0].quantity,"shop inventory leaked");}});
run("T19 recipe Back preserves fixed choices and owned cores without automatic sale",[&]{auto c=rewards(fights,rules);const auto rid=reward(c,RewardKind::Recipe),cid=reward(c,RewardKind::Cores);const auto choices=entry(c,rid).choices;const auto money=c.fight.credits;apply(rules,c,command(c,CampaignActionType::OpenRecipes,rid));apply(rules,c,command(c,CampaignActionType::BackRecipes));apply(rules,c,command(c,CampaignActionType::ClaimReward,cid));roundtrip(c);apply(rules,c,command(c,CampaignActionType::OpenRecipes,rid));expect(entry(c,rid).choices==choices&&entry(c,rid).claim==ClaimState::Pending,"Back changed reward");expect(c.cores.size()==1&&c.fight.credits==money,"core disappeared or auto-sold");});
run("T13 T21 pending exchange survives save and cancel then commits once",[&]{auto c=rewards(fights,rules);c.memorySlots=static_cast<Amount>(c.fight.memory.size());const auto rid=reward(c,RewardKind::Recipe),old=c.fight.memory.back().id;const auto choice=entry(c,rid).choices[1];apply(rules,c,command(c,CampaignActionType::OpenRecipes,rid));apply(rules,c,command(c,CampaignActionType::ClaimReward,rid,choice));expect(c.pendingRecipeChoice==choice,"exchange cursor absent");roundtrip(c);apply(rules,c,command(c,CampaignActionType::BackRecipes));expect(c.fight.memory.back().id==old&&entry(c,rid).claim==ClaimState::Pending,"cancel applied exchange");apply(rules,c,command(c,CampaignActionType::OpenRecipes,rid));auto accept=command(c,CampaignActionType::ClaimReward,rid,choice);accept.exchange=old;apply(rules,c,accept);const auto snapshot=serializeCampaign(c);expect(apply(rules,c,accept).replayed,"repeat receipt not replayed");expect(serializeCampaign(c)==snapshot,"repeat exchange changed state");expect(std::none_of(c.fight.memory.begin(),c.fight.memory.end(),[&](const RecipeCopy& p){return p.id==old;}),"old memory retained");});
run("T20 T22 confirmation abandons only pending loot and closes once",[&]{auto c=rewards(fights,rules);const auto cid=reward(c,RewardKind::Cores),rid=reward(c,RewardKind::Recipe);apply(rules,c,command(c,CampaignActionType::ClaimReward,cid));apply(rules,c,command(c,CampaignActionType::RequestAdvance));roundtrip(c);apply(rules,c,command(c,CampaignActionType::CancelAdvance));expect(entry(c,rid).claim==ClaimState::Pending&&c.cores.size()==1,"cancel lost pending/claimed reward");apply(rules,c,command(c,CampaignActionType::RequestAdvance));auto confirmed=command(c,CampaignActionType::ConfirmAdvance);apply(rules,c,confirmed);const auto before=serializeCampaign(c);expect(apply(rules,c,confirmed).replayed&&serializeCampaign(c)==before,"confirmation advanced twice");expect(entry(c,rid).claim==ClaimState::Abandoned&&c.cores.size()==1&&c.route.position==2,"abandonment changed owned items/progress");auto empty=rewards(fights,rules);empty.rewards.clear();const auto generation=empty.shopGeneration;apply(rules,empty,command(empty,CampaignActionType::RequestAdvance));expect(empty.phase==CityPhase::Between&&!empty.skipConfirmation&&empty.shopGeneration==generation,"empty reward fixture requested confirmation or restocked again");});
run("T18 noncombat Mystery consumes one node without combat restock",[&]{auto c=mystery(rules,"C1-M-EXCHANGE");const auto position=c.route.position,generation=c.shopGeneration;const auto money=c.fight.credits;const auto shop=c.shop;apply(rules,c,command(c,CampaignActionType::OpenShop,0));roundtrip(c);apply(rules,c,command(c,CampaignActionType::LeaveMystery));equal(c.route.position,position+1,"Mystery node count");equal(c.shopGeneration,generation,"noncombat restock");equal(c.fight.credits,money+10,"one explicit Mystery hook");equal(c.upgrades[0].campaignCount,0,"combat hook ran");expect(c.shop[0].id==shop[0].id,"stock rerolled");});
run("transaction sequence reuse with different payload rejects atomically",[&]{auto c=start(rules);auto a=command(c,CampaignActionType::Buy,product(c,ProductKind::Material));apply(rules,c,a);a.quantity=2;reject(rules,c,a);});
run("queued purchase from old New Game cannot execute in a replacement run",[&]{const auto p=disk/"replacement.ofsave";CampaignSession s(p,rules);expect(s.newGame(3,"old-run").ok,"oldrun");expect(s.apply(command(s.state(),CampaignActionType::ChooseMayor,0,s.state().mayorOffers[0])).ok,"oldMayor");auto stale=command(s.state(),CampaignActionType::Buy,product(s.state(),ProductKind::Material));expect(s.newGame(3,"new-run").ok,"newrun");expect(s.apply(command(s.state(),CampaignActionType::ChooseMayor,0,s.state().mayorOffers[0])).ok,"newMayor");const auto before=serializeCampaign(s.state());const auto out=s.apply(stale);expect(!out.ok,"old-run purchase was accepted in new-run");expect(serializeCampaign(s.state())==before,"replacement campaign changed");});
run("snapshot rejects living HP represented as a terminal defeated campaign",[&]{auto c=start(rules);c.phase=CityPhase::Defeated;expect(!validSnapshot(c),"living campaign serialized as Defeated");});
run("snapshot rejects zero-HP defeat represented as between-fight play",[&]{auto c=start(rules);c.fight.hp=0;c.fight.phase=Phase::Defeat;expect(!validSnapshot(c),"dead campaign serialized as Between");});
run("snapshot rejects fight identity diverging from committed encounter",[&]{auto c=start(rules);enter(rules,c);c.fight.encounter="changed-encounter";++c.fight.seed;expect(!validSnapshot(c),"fight seed/key diverged from committed offer");});
run("snapshot rejects current formation diverging from original entry",[&]{auto c=start(rules);enter(rules,c);auto& node=c.route.nodes[0];auto selected=std::find_if(node.offers.begin(),node.offers.end(),[&](const RouteOffer&o){return o.id==node.selected;});auto other=std::find_if(node.offers.begin(),node.offers.end(),[&](const RouteOffer&o){return o.id!=node.selected;});std::swap(selected->formation,other->formation);expect(!validSnapshot(c),"formation changed under original encounter ID");});
run("postreplacement save error reconciles the committed purchase and receipt",[&]{auto c=start(rules);const auto p=disk/"ambiguous.ofsave";seedFile(p,c);CampaignSession s(p,rules);expect(s.load().ok,"load");auto a=command(s.state(),CampaignActionType::Buy,product(s.state(),ProductKind::Material));a.quantity=3;const auto out=s.apply(a,[](SavePoint pnt){if(pnt==SavePoint::Replaced)throw std::runtime_error("independent fault after replace");});expect(out.ok&&out.reconciled,"committed purchase not reconciled");equal(s.state().fight.materials[0],3,"purchase count");const auto revision=s.revision();expect(s.apply(a).replayed&&s.revision()==revision,"reconciled operation repeated");});
run("precommit save error publishes no speculative reward claim",[&]{auto c=rewards(fights,rules);const auto p=disk/"failed-reward.ofsave";seedFile(p,c);CampaignSession s(p,rules);expect(s.load().ok,"load");const auto before=serializeCampaign(s.state());const auto a=command(s.state(),CampaignActionType::ClaimReward,reward(s.state(),RewardKind::Cores));const auto out=s.apply(a,[](SavePoint pnt){if(pnt==SavePoint::TemporaryFlushed)throw std::runtime_error("independent fault before replace");});expect(!out.ok&&out.reconciled&&serializeCampaign(s.state())==before,"uncommitted cores exposed");expect(s.apply(a).ok&&s.state().cores.size()==1,"retry failed");});
run("defeat closes checkpoint without restock or loot and preserves discoveries",[&]{auto c=start(rules);enter(rules,c);apply(rules,c,command(c,CampaignActionType::OpenShop));const auto discoveries=c.profile.recipes;c.fight.hp=1;for(int i=0;i<4&&c.phase==CityPhase::Fight;++i){if(c.fight.phase==Phase::Collection)combat(rules,c,Action::collect(0));combat(rules,c,Action::endTurn());}expect(c.phase==CityPhase::Defeated&&c.fight.hp==0,"controlled lethal attack did not end campaign");expect(c.entry.empty()&&c.rewards.empty()&&c.cores.empty()&&c.shopGeneration==1,"defeat granted loot/restock/checkpoint");reject(rules,c,command(c,CampaignActionType::Continue));roundtrip(c);expect(c.profile.recipes==discoveries,"death lost profile discoveries");});
run("boss completion and unlock receipt survive reload and duplicate final Fire",[&]{auto c=start(rules);while(c.route.position<12){std::string e;expect(selectRouteOffer(c.route,routeOffers(c.route).front().id,e),e);expect(completeRouteNode(c.route,e),e);}expect(routeOffers(c.route).size()==1,"boss offers are not sole choice");apply(rules,c,command(c,CampaignActionType::EnterOffer,routeOffers(c.route)[0].id));combat(rules,c,Action::collect(0));expect(fights.grantPlainPart(c.fight,Kind::Ammo,1000,"boss-transaction-fixture").ok,"grant");combat(rules,c,Action::load({c.fight.parts.back().id}));auto final=command(c,CampaignActionType::Combat);final.combat=Action::fire(c.fight.enemies[0].id);apply(rules,c,final);expect(c.route.position==13&&c.profile.cityClearReceipts.size()==1,"boss clear fact");expect(std::find(c.profile.unlocked.begin(),c.profile.unlocked.end(),"Ivo")!=c.profile.unlocked.end(),"earned unlock absent");roundtrip(c);const auto before=serializeCampaign(c);expect(apply(rules,c,final).replayed&&serializeCampaign(c)==before,"duplicate final Fire repeated reward/clear");advance(rules,c);expect(c.phase==CityPhase::Complete,"final route did not close");roundtrip(c);});
for(int mode=0;mode<3;++mode)run(mode==0?"actual process exits preserve confirmed abandonment atomically":mode==1?"actual process exits preserve terminal Fire atomically":"actual process exits preserve recipe exchange atomically",[&]{
    auto before=mode==1?start(rules):rewards(fights,rules);
    if(mode==0){apply(rules,before,command(before,CampaignActionType::ClaimReward,reward(before,RewardKind::Cores)));apply(rules,before,command(before,CampaignActionType::RequestAdvance));}
    else if(mode==1){enter(rules,before);combat(rules,before,Action::collect(0));expect(fights.grantPlainPart(before.fight,Kind::Ammo,1000,"crash-terminal-fixture").ok,"grant");combat(rules,before,Action::load({before.fight.parts.back().id}));}
    else{before.memorySlots=static_cast<Amount>(before.fight.memory.size());const auto rid=reward(before,RewardKind::Recipe);apply(rules,before,command(before,CampaignActionType::OpenRecipes,rid));apply(rules,before,command(before,CampaignActionType::ClaimReward,rid,entry(before,rid).choices[1]));}
    const auto a=crashAction(before,mode);auto after=before;apply(rules,after,a);const auto oldBytes=serializeCampaign(before),newBytes=serializeCampaign(after);
    std::vector<wchar_t> exe(32768);const auto length=GetModuleFileNameW(nullptr,exe.data(),static_cast<DWORD>(exe.size()));expect(length>0&&length<exe.size(),"executable path");
    for(int point=0;point<4;++point){const auto path=disk/("crash-"+std::to_string(mode)+"-"+std::to_string(point)+".ofsave");seedFile(path,before);std::wstring args=L"\""+std::wstring(exe.data(),length)+L"\" --crash \""+path.wstring()+L"\" "+std::to_wstring(point)+L" "+std::to_wstring(mode);STARTUPINFOW startup{};startup.cb=sizeof(startup);startup.dwFlags=STARTF_USESHOWWINDOW;startup.wShowWindow=SW_HIDE;PROCESS_INFORMATION child{};expect(CreateProcessW(nullptr,args.data(),nullptr,nullptr,FALSE,CREATE_NO_WINDOW,nullptr,nullptr,&startup,&child)!=0,"launch crash child");const auto waited=WaitForSingleObject(child.hProcess,10000);DWORD code=0;GetExitCodeProcess(child.hProcess,&code);CloseHandle(child.hThread);CloseHandle(child.hProcess);expect(waited==WAIT_OBJECT_0&&code==73,"requested actual process exit not observed");CampaignSession restored(path,rules);const auto loaded=restored.load();expect(loaded.ok,loaded.reason);expect(serializeCampaign(restored.state())==(point<2?oldBytes:newBytes),"partial transaction persisted");const auto retried=restored.apply(a);expect(retried.ok&&retried.replayed==(point>=2),"retry disagrees with durable receipt");expect(serializeCampaign(restored.state())==newBytes,"retry diverged from exactly-once result");std::cout<<"PASS process exit mode="<<mode<<" boundary="<<point<<" exit=73\n";}
});
std::cout<<"Campaign independent groups: "<<passed<<" passed, "<<failed<<" failed.\n";return failed?1:0;}
