"""Emit immutable catalogue metadata, never infer executable behavior from prose."""
from pathlib import Path
import json,re,sys
root=Path(__file__).resolve().parents[1]
rows=json.loads((root/'content/catalogue.snapshot.json').read_text(encoding='utf8'))['recipes']
lines=['// Generated by content/compile_recipe_effects.py. Effects execute in recipe_effects.inl.']
for id in [*(f'SH{n:03d}' for n in range(1,127)),*(f'MA{n:03d}' for n in range(1,121))]:
    r=rows[id]; code=int(id[2:])+(1000 if id.startswith('MA') else 0)
    kind='Spread' if id in ('SH005','SH051','SH082','SH110','MA041','MA111') else r['kind']
    timing={'Ammo':'Assembly','Spread':'Assembly','Shield':'Install','Utility':'Use','Modifier':'Activate','Magnet':'Activate'}[kind]
    auto=id in ('SH026','SH057')
    if auto: timing='Use'
    output=re.sub(r'^\d+ ','',r['output_text']).replace('Immediate effect: ','').replace(' (no part)','')
    if id=='MA038':output='Warm Rivet'
    cost=','.join(str(r['materials'].get(k,0)) for k in ('Iron','Copper','Carbon','Glass','Circuit'))
    q=lambda x:json.dumps(x,ensure_ascii=True)
    lines.append('{'+','.join((q(id),q(r['name']),q(output),'Kind::'+kind,'{'+cost+'}',str(r['cooldown'] or 0),'{{Op::Catalogue,Timing::'+timing+','+str(code)+',0}}','true' if auto else 'false','Rarity::'+r['rarity'],str(2 if id=='MA038' else 1),str(code)))+'},')
out=root/'core/src/catalogue_data.inc'; text='\n'.join(lines)+'\n'
if '--check' in sys.argv:
    assert out.read_text(encoding='utf8')==text,'Generated recipe metadata is stale'
else:out.write_text(text,encoding='utf8')
print(f'{len(lines)-1} source recipe metadata rows verified; no behavior claim')
