#include "overkill/upgrades.hpp"
#include "overkill/robots.hpp"
#include <algorithm>
#include <functional>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
using namespace overkill;
namespace {
int assertions=0,failures=0;std::set<std::string> covered;
void check(bool b,const std::string& text){++assertions;if(!b)throw std::runtime_error(text);}
void ok(Result r){check(r.ok,r.reason);}
void act(const Rules&r,State&s,const Action&a){ok(r.apply(s,a));}
Id memory(State&s,const std::string&id){const auto n=s.nextId++;s.memory.push_back({n,id,0,0,0});return n;}
State fixture(){State s;s.phase=Phase::Preparation;s.hotBarrel=false;s.hp=40;s.materials={100,100,100,100,100};s.rng=Rng::seeded(42,"upgrades");for(int i=0;i<3;++i){Enemy e;e.id=s.nextId++;e.definition="test";e.name="Target";e.hp=e.maxHp=1000;e.intent={Move::Attack,10,1};e.pattern={e.intent};s.enemies.push_back(e);}for(const auto* id:{"SH001","SH002","SH004","SH019","SH007","SH008","SH024","SH013","MA001"})memory(s,id);return s;}
Id copy(const State&s,const std::string&id){for(const auto& c:s.memory)if(c.recipe==id)return c.id;throw std::runtime_error("Missing copy "+id);}
Id part(const State&s,const std::string&id){for(auto it=s.parts.rbegin();it!=s.parts.rend();++it)if(it->recipe==id&&it->place==Place::Reserve)return it->id;throw std::runtime_error("Missing part "+id);}
void acquire(const Rules&r,State&s,const std::string&id){ok(r.acquireUpgrade(s,id));}
void answer(const Rules&r,State&s,UpgradeAnswer a){a.choice=s.upgradeChoices.front().id;Action action;action.type=ActionType::ResolveUpgradeChoice;action.upgradeChoice=a;act(r,s,action);}
void start(const Rules&r,State&s,EncounterClass kind=EncounterClass::Regular){ok(r.startUpgrades(s,kind));}
void collect(const Rules&r,State&s,Amount precision=-1){act(r,s,Action::collect(0,precision));}
void shot(const Rules&r,State&s,const std::string&id="SH001",Id target=0){ok(r.grantPart(s,id));act(r,s,Action::load({part(s,id)}));act(r,s,Action::fire(target?target:s.enemies[0].id));}
void next(const Rules&r,State&s){act(r,s,Action::endTurn());if(s.upgradeChoices.empty()&&s.upgradeRequests.empty()&&s.phase==Phase::Collection)collect(r,s);}
void rejection(const Rules&r,State&s,const Action&a){const auto before=serialize(s);auto result=r.apply(s,a);check(!result.ok,"Expected invalid action");check(before==serialize(s),"Rejected action mutated state");}
void roundTrip(const State&s){State c;std::string error;check(deserialize(serialize(s),c,error),error);check(serialize(c)==serialize(s),"Snapshot changed state");}
void event(const Rules&r,State&s,UpgradeEventKind kind,Id subject=0){UpgradeEvent e;e.kind=kind;e.subject=subject;e.baseValue=1;ok(r.upgradeEvent(s,e));}
void acknowledge(const Rules&r,State&s){check(!s.upgradeRequests.empty(),"Expected saved adapter request");const auto id=s.upgradeRequests.front().id;check(acknowledgeUpgradeRequest(s,id),"Acknowledge existing request");check(!acknowledgeUpgradeRequest(s,id),"Request cannot be acknowledged twice");ok(r.resumeUpgrades(s));}
void accept(const Rules&r,State&s,Id subject,AcquisitionSource origin=AcquisitionSource::Victory,Id reward=1,bool light=false){UpgradeEvent e;e.kind=UpgradeEventKind::RecipeAccepted;e.subject=subject;e.origin=origin;e.reward=reward;e.lightTouch=light;ok(r.upgradeEvent(s,e));}
void run(const char* name,const std::function<void()>&fn){try{fn();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failures;std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
}
int main(){Rules r;
run("exact eligible set, acquisition atomicity, stats and queries",[&]{check(eligibleUpgradeIds().size()==152,"152 IDs");for(const auto& pair:std::map<std::string,Amount>{{"MY1-02",10},{"MY1-05",18},{"UGS-011",18},{"UGS-064",14},{"UGS-070",12},{"UGS-071",4},{"UGS-120",6}}){auto s=fixture();acquire(r,s,pair.first);check(s.maxHp==80+pair.second&&s.hp==40+pair.second,pair.first+" maxHP and one heal");const auto before=serialize(s);check(!r.acquireUpgrade(s,pair.first).ok,"Repeat ownership rejects");check(before==serialize(s),"Repeat acquisition atomic");roundTrip(s);covered.insert(pair.first);}
    auto s=fixture();acquire(r,s,"MAU-02");check(upgradeHeatCap(s)==14&&s.heat==0,"Heat cap capacity is not free Heat");acquire(r,s,"MAU-04");check(upgradeHeatDecay(s)==1,"Only ordinary decay reduced");acquire(r,s,"UGS-058");check(upgradePrecisionWidthPercent(s)==120,"Precision original width20percent");acquire(r,s,"UGS-075");check(upgradeShopPrice(s,PurchaseKind::Recipe,9)==7&&upgradeShopPrice(s,PurchaseKind::Material,1)==1&&upgradeShopPrice(s,PurchaseKind::Part,9)==9,"Vendor product filter floor once");acquire(r,s,"UGS-017");check(upgradeCoreSaleValue(s,7)==8,"Floor per core");acquire(r,s,"UGS-100");check(upgradeUtilityMemoryBonus(s)==2&&upgradeGeneralMemoryBonus(s)==0,"Typed Utility slots");covered.insert({"MAU-02","MAU-04","UGS-058","UGS-075","UGS-017","UGS-100"});
});
run("entry sources, explicit turn starts, saved selection and preview",[&]{auto s=fixture();for(const auto* id:{"MAU-01","MY1-03","MY1-04","MY1-M1","UGS-006","UGS-007","UGS-013","UGS-022","UGS-053","MY2-03","MY3-02"})acquire(r,s,id);start(r,s);check(s.heat==6,"Two independent Heat grants");check(s.hp==42,"One entry heal");check(s.materials[0]==103&&s.materials[1]==103,"Turn1 supplies");check(Rules::shield(s)==12,"Ordinary Shield plus direct opening6");check(s.enemies[0].mark==2&&s.enemies[1].mark==0,"MaximumHP tie slot");check(upgradeGeneralMemoryBonus(s)==4,"Archive capacity");collect(r,s);const auto before=serialize(s);const auto preview=r.preview(s,Action::endTurn());check(preview.result.ok,preview.result.reason);check(serialize(s)==before,"Preview unchanged");act(r,s,Action::endTurn());check(serialize(s)==serialize(preview.state),"Preview exact phase");check(Rules::shield(s)==10,"Turn2 Shutter");roundTrip(s);covered.insert({"MAU-01","MY1-03","MY1-04","MY1-M1","UGS-006","UGS-007","UGS-013","UGS-022","UGS-053","MY2-03","MY3-02"});
    s=fixture();acquire(r,s,"MY1-08");acquire(r,s,"UGS-024");start(r,s);check(s.upgradeChoices.size()==1&&s.upgradeChoices[0].source=="MY1-08","Pause before later source");roundTrip(s);UpgradeAnswer a;a.values={1};answer(r,s,a);check(s.upgradeChoices.front().source=="UGS-024","Next choice saved");a.values={0};answer(r,s,a);check(s.materials[0]==102&&ownedUpgrade(s,"UGS-024")->charges==4,"Supply charge once");collect(r,s);const auto copper=s.materials[1];act(r,s,Action::craft(copy(s,"SH002")));check(s.materials[1]==copper,"Refund actual Copper");covered.insert({"MY1-08","UGS-024"});
});
run("physical paid production, committed copies and immutable resale",[&]{auto s=fixture();for(const auto* id:{"MY1-01","MY2-02","UGS-121","UGS-140","UGS-015"})acquire(r,s,id);start(r,s);collect(r,s);act(r,s,Action::craft(copy(s,"SH001")));std::vector<Part> slugs;for(const auto&p:s.parts)if(p.recipe=="SH001")slugs.push_back(p);check(slugs.size()==2,"Trial copies first output once");check(slugs[0].upgradeDamage==4&&slugs[1].upgradeDamage==2,"Copy retains Mayor2 but excludes single-output Jig2");check(slugs[1].origin==PartOrigin::Copied&&slugs[0].origin==PartOrigin::Produced,"Paid vs copy provenance");check(slugs[0].sourceRecipeCopy==copy(s,"SH001")&&slugs[0].resaleReference=="SH001","Copy source and immutable basis");act(r,s,Action::craft(copy(s,"SH002")));auto p=part(s,"SH002");act(r,s,Action::install(p));check(Rules::shield(s)==13,"Plate Binder3 and Laminator4");ok(r.grantPart(s,"SH001"));check(s.parts.back().upgradeDamage==0,"Free grant is not production");roundTrip(s);covered.insert({"MY1-01","MY2-02","UGS-121","UGS-140","UGS-015"});
});
run("payment clocks, defense and real shared retention",[&]{auto s=fixture();acquire(r,s,"MAU-03");acquire(r,s,"MY1-M3");start(r,s);collect(r,s);s.heat=10;auto use=memory(s,"MA085");act(r,s,Action::craft(use));check(s.heat==4&&Rules::shield(s)==3&&s.hp==46,"Actual6Heat triggers after Use");covered.insert({"MAU-03","MY1-M3"});
    s=fixture();acquire(r,s,"MY3-03");acquire(r,s,"UGS-123");for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};start(r,s);collect(r,s);ok(r.grantPlainPart(s,Kind::Shield,7,"fixture",true));act(r,s,Action::endTurn());check(Rules::shield(s)==7&&s.parts.empty(),"6+3 retention shares7 without old payload");roundTrip(s);covered.insert({"MY3-03","UGS-123"});
});
run("main shot clocks, Armor bypass and source-copy momentum",[&]{auto s=fixture();acquire(r,s,"UGS-001");acquire(r,s,"UGS-139");acquire(r,s,"MAU-07");start(r,s);collect(r,s);s.heat=8;s.enemies[0].armor=4;shot(r,s);check(s.enemies[0].hp==987,"6slug+6first+1turn Armor bypass");shot(r,s);check(s.enemies[0].hp==985,"Second shot only6 minus4");covered.insert({"UGS-001","UGS-139","MAU-07"});
});
run("acquisition selection rejects nonmatching copies and resumes once",[&]{auto s=fixture();acquire(r,s,"UGS-039");check(s.hp==32,"Acquisition HP cost once before choice");roundTrip(s);UpgradeAnswer a;a.objects={copy(s,"SH001"),copy(s,"SH004")};Action invalid;invalid.type=ActionType::ResolveUpgradeChoice;invalid.upgradeChoice=a;invalid.upgradeChoice.choice=s.upgradeChoices.front().id;rejection(r,s,invalid);a.objects={copy(s,"SH001"),copy(s,"SH002")};answer(r,s,a);check(s.hp==32&&s.memory[0].tags.size()==1,"No second payment on selection");covered.insert("UGS-039");
});
run("Mayor opening choices and named encounter gates",[&]{
    for(const auto kind:{EncounterClass::Regular,EncounterClass::Officer,EncounterClass::Boss}){auto s=fixture();acquire(r,s,"MY1-07");acquire(r,s,"UGS-090");start(r,s,kind);check(Rules::shield(s)==(kind==EncounterClass::Officer?8:0),"Inspector only Officer");check(s.materials[0]==(kind==EncounterClass::Officer?104:100),"Officer Iron");check(s.hp==(kind==EncounterClass::Boss?52:40),"Boss triage only boss");}covered.insert({"MY1-07","UGS-090"});
    for(const bool defence:{false,true}){auto s=fixture();acquire(r,s,"MY1-22");start(r,s);UpgradeAnswer a;a.option=defence?"defence":"assault";answer(r,s,a);check(s.parts.size()==2&&Rules::shield(s)==(defence?8:0),"Drawer grants only chosen pair");check(s.parts[0].resaleReference==std::string("generated:")+(defence?"shield:4":"ammo:4"),"Drawer immutable generated basis");}covered.insert("MY1-22");
    auto s=fixture();acquire(r,s,"MY1-21");start(r,s);UpgradeAnswer a;a.objects={copy(s,"SH001")};answer(r,s,a);collect(r,s);auto use=Action::craft(copy(s,"SH001"));const auto iron=s.materials[0];act(r,s,use);act(r,s,use);check(s.materials[0]==iron-2,"Two paid noCD Uses");rejection(r,s,use);next(r,s);act(r,s,use);rejection(r,s,use);covered.insert("MY1-21");
    s=fixture();acquire(r,s,"MY1-23");start(r,s);a.objects={copy(s,"SH002")};answer(r,s,a);collect(r,s);act(r,s,Action::craft(copy(s,"SH002")));act(r,s,Action::install(part(s,"SH002")));check(Rules::shield(s)==13,"Blueprint first selected Shield+7");covered.insert("MY1-23");
    s=fixture();acquire(r,s,"MY1-15");a.option="assault";answer(r,s,a);start(r,s);collect(r,s);act(r,s,Action::craft(copy(s,"SH001")));check(s.parts.back().upgradeDamage==2,"Assault output2");act(r,s,Action::craft(copy(s,"SH004")));check(s.parts.back().upgradeDamage==0,"First output only");covered.insert("MY1-15");
    s=fixture();acquire(r,s,"MY1-M2");start(r,s);collect(r,s);s.heat=3;act(r,s,Action::craft(copy(s,"SH001")));check(s.parts.back().upgradeDamage==0&&s.heat==3,"Ledger condition before own gain");s.heat=4;act(r,s,Action::craft(copy(s,"SH004")));check(s.parts.back().upgradeDamage==3&&s.heat==5,"Ledger3 and1 at4");covered.insert("MY1-M2");
});
run("physical selected copies, calibration cooldown and momentum",[&]{
    auto s=fixture();acquire(r,s,"UGS-046");UpgradeAnswer a;a.objects={copy(s,"SH001"),copy(s,"SH004")};answer(r,s,a);start(r,s);collect(r,s);const auto duplicate=memory(s,"SH001");act(r,s,Action::craft(copy(s,"SH001")));check(s.parts.back().upgradeDamage==1,"Selected die-set copy");act(r,s,Action::craft(duplicate));check(s.parts.back().upgradeDamage==0,"Later duplicate not selected");covered.insert("UGS-046");
    for(const auto& item:std::vector<std::pair<std::string,Kind>>{{"UGS-144",Kind::Utility},{"UGS-145",Kind::Ammo}}){s=fixture();std::vector<Id> options;for(const auto& def:r.content())if(def.kind==item.second&&def.cooldown>0&&!def.automaticOutput){if(def.id=="SH033"||def.id=="SH067"||def.id=="SH011"||def.id=="SH012")options.push_back(memory(s,def.id));}check(options.size()>=2,"Two authored numeric test copies");acquire(r,s,item.first);a.objects={options[0],options[1]};answer(r,s,a);start(r,s);collect(r,s);const auto* def=r.recipe(std::find_if(s.memory.begin(),s.memory.end(),[&](const RecipeCopy&c){return c.id==options[0];})->recipe);act(r,s,Action::craft(options[0]));const auto it=std::find_if(s.memory.begin(),s.memory.end(),[&](const RecipeCopy&c){return c.id==options[0];});check(it->cooldown==std::max(0,def->cooldown-1),item.first+" first numeric assignment");check(it->tags[0].usedFight==s.fightSerial,"Coupon marked for exact fight");covered.insert(item.first);}
    s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};acquire(r,s,"UGS-102");a.objects={copy(s,"SH001")};answer(r,s,a);start(r,s);collect(r,s);const auto enemy=s.enemies[0].id;shot(r,s);check(s.enemies[0].hp==994,"Free same-definition slug has no recipe-copy lineage");for(int turn=1;turn<=3;++turn){act(r,s,Action::craft(copy(s,"SH001")));act(r,s,Action::load({part(s,"SH001")}));const auto before=s.enemies[0].hp;act(r,s,Action::fire(enemy));check(before-s.enemies[0].hp==6+2*turn,"Consecutive source-copy momentum");if(turn<3)next(r,s);}covered.insert("UGS-102");
    s=fixture();acquire(r,s,"UGS-119");start(r,s);a.objects={copy(s,"SH001"),copy(s,"SH002")};answer(r,s,a);collect(r,s);act(r,s,Action::craft(copy(s,"SH001")));check(s.parts.back().upgradeDamage==2,"Pairwise selected Ammo");act(r,s,Action::craft(copy(s,"SH002")));check(s.parts.back().upgradeShield==2,"Pairwise selected Shield independent coupon");covered.insert("UGS-119");
});
run("opening production counts and true paid-use discount qualification",[&]{auto s=fixture();acquire(r,s,"UGS-009");start(r,s);collect(r,s);for(const auto* id:{"SH001","SH002","SH004","SH019"})act(r,s,Action::craft(copy(s,id)));check(s.parts[0].upgradeDamage==2&&s.parts[1].upgradeShield==2&&s.parts[2].upgradeDamage==2&&s.parts[3].upgradeShield==0,"Calibrator three outputs only");covered.insert("UGS-009");
    s=fixture();acquire(r,s,"MY1-09");start(r,s);collect(r,s);for(const auto* id:{"SH013","SH004","SH019"})act(r,s,Action::craft(copy(s,id)));Action fourth=Action::craft(copy(s,"SH002"));fourth.discount={1,1,0,0,0};const auto iron=s.materials[0];act(r,s,fourth);check(s.materials[0]==iron,"Fourth use may pay zero raw material");auto bad=Action::craft(memory(s,"SH001"));bad.discount={1,0,0,0,0};rejection(r,s,bad);covered.insert("MY1-09");
    s=fixture();acquire(r,s,"UGS-116");start(r,s);const auto selected=ownedUpgrade(s,"UGS-116")->values[0];check(selected>=0&&selected<5,"Discount material revealed");collect(r,s);const Recipe* def=nullptr;for(const auto& candidate:r.content())if(candidate.cost[static_cast<std::size_t>(selected)]>0&&candidate.kind==Kind::Ammo&&!candidate.automaticOutput){def=&candidate;break;}check(def!=nullptr,"Paid material recipe exists");const auto first=memory(s,def->id),second=memory(s,def->id);const auto before=s.materials[static_cast<std::size_t>(selected)];act(r,s,Action::craft(first));check(s.materials[static_cast<std::size_t>(selected)]==before-def->cost[static_cast<std::size_t>(selected)]+1,"First selected ingredient discounted1");const auto after=s.materials[static_cast<std::size_t>(selected)];act(r,s,Action::craft(second));check(s.materials[static_cast<std::size_t>(selected)]==after-def->cost[static_cast<std::size_t>(selected)],"Second copy pays full");roundTrip(s);covered.insert("UGS-116");
});
run("Fire counts distinguish supports, valid Fires, source age and next shot",[&]{auto s=fixture();for(const auto* id:{"UGS-030","UGS-060","UGS-083","UGS-088","UGS-093","UGS-122"})acquire(r,s,id);start(r,s);collect(r,s);for(int i=1;i<=5;++i)shot(r,s);check(s.enemies[0].hp==962,"Fifth cam adds8 once");check(s.enemies[1].hp==995&&s.enemies[2].hp==1000,"Third Fire tripod lowest other slot");check(Rules::shield(s)==10,"First3 harness6 plus secondBrace4");check(s.materials[1]==103,"FifthFire grants1Copper after ordinary base2");check(std::count_if(s.parts.begin(),s.parts.end(),[](const Part&p){return p.recipe=="SH003";})==1,"Single-slug reader once");covered.insert({"UGS-030","UGS-060","UGS-083","UGS-088","UGS-093","UGS-122"});
    s=fixture();acquire(r,s,"UGS-044");acquire(r,s,"UGS-077");start(r,s);collect(r,s);ok(r.grantPart(s,"SH001"));s.parts.back().createdRound=1;s.round=2;const auto iron=s.materials[0];act(r,s,Action::load({part(s,"SH001")}));act(r,s,Action::fire(s.enemies[0].id));check(s.enemies[0].hp==991&&s.materials[0]==iron+1,"Saved slug+3 and oneIron refund");shot(r,s);check(s.enemies[0].hp==985&&s.materials[0]==iron+1,"Neither once-per-turn bonus repeats");covered.insert({"UGS-044","UGS-077"});
    s=fixture();acquire(r,s,"UGS-115");start(r,s,EncounterClass::Officer);collect(r,s);shot(r,s);shot(r,s);check(s.enemies[0].hp==985,"Officer firstmain+3 only");covered.insert("UGS-115");
    s=fixture();acquire(r,s,"UGS-021");start(r,s);UpgradeAnswer a;a.objects={s.enemies[1].id};answer(r,s,a);collect(r,s);shot(r,s);shot(r,s,"SH001",s.enemies[1].id);check(s.enemies[0].hp==994&&s.enemies[1].hp==990,"Kite waits for selected robot");covered.insert("UGS-021");
});
run("prehit and per-hit reactions, final-death interruption and status novelty",[&]{auto s=fixture();s.hp=20;s.enemies.resize(1);s.enemies[0].intent=s.enemies[0].pattern[0]={Move::Attack,5,2};for(const auto* id:{"MY1-20","UGS-019","UGS-014","UGS-025"})acquire(r,s,id);start(r,s);collect(r,s);act(r,s,Action::endTurn());check(s.hp==20&&s.enemies[0].hp==996,"Alarm precedes hit and counterpulses each shield hit");collect(r,s);act(r,s,Action::endTurn());check(s.hp==13,"Second attack10 then scheduledheal3");check(s.materials[0]>=108&&s.materials[1]>=105,"Diagnostic only enemy HP loss");covered.insert({"MY1-20","UGS-019","UGS-014","UGS-025"});
    s=fixture();s.enemies[0].armor=2;acquire(r,s,"UGS-049");start(r,s);collect(r,s);shot(r,s);check(s.enemies[0].hp==996&&s.enemies[0].mark==2,"Paint follows actual Armor reduction");shot(r,s);check(s.enemies[0].hp==990&&s.enemies[0].mark==0,"Triggering hit never benefits retroactively");covered.insert("UGS-049");
    s=fixture();acquire(r,s,"UGS-048");start(r,s);collect(r,s);s.enemies[0].hp=1;s.enemies[1].hp=1;const auto iron=s.materials[0];shot(r,s);shot(r,s,"SH001",s.enemies[1].id);check(s.materials[0]==iron+1&&s.materials[2]==102,"One kill payout per player turn");covered.insert("UGS-048");
    s=fixture();acquire(r,s,"UGS-037");s.hp=1;s.enemies[0].mesh=2;start(r,s);check(s.phase==Phase::Defeat&&s.enemies[0].hp==996&&s.enemies[1].hp==1000,"Arrival recoil stops later targets");covered.insert("UGS-037");
    s=fixture();acquire(r,s,"UGS-105");start(r,s);check(std::all_of(s.enemies.begin(),s.enemies.end(),[](const Enemy&e){return e.weaken==1;}),"Fight entry Weaken all");covered.insert("UGS-105");
});
run("Use counts, cooling consequences and recipe healing attribution",[&]{auto s=fixture();for(const auto* id:{"MY2-01","UGS-127","UGS-107","UGS-136","UGS-066"})acquire(r,s,id);start(r,s);collect(r,s);s.memory[0].cooldown=1;const auto before=s.materials[1];act(r,s,Action::craft(copy(s,"SH007")));check(s.memory[0].cooldown==0&&s.materials[1]==before-r.recipe("SH007")->cost[1]+1,"Recirculator fresh1Copper on cooling");check(Rules::shield(s)==5,"Final-counter removal Shield");shot(r,s);check(s.enemies[0].hp==991,"First paidUtility queues next3");for(int i=0;i<3;++i){const auto id=memory(s,"SH007");act(r,s,Action::craft(id));}check(s.enemies[1].hp==997,"Third paidUtility ArcFork");check(Rules::shield(s)==10,"FourthUtility Barrier");covered.insert({"MY2-01","UGS-127","UGS-107","UGS-136","UGS-066"});
    s=fixture();acquire(r,s,"UGS-106");start(r,s);collect(r,s);const auto healing=memory(s,"SH074");act(r,s,Action::craft(healing));check(s.hp==47,"Actual recipe heal4 plusFilter3");const auto second=memory(s,"SH074");act(r,s,Action::craft(second));check(s.hp==51,"Filter oncefight");covered.insert("UGS-106");
    s=fixture();acquire(r,s,"UGS-095");start(r,s);collect(r,s);const auto mod=memory(s,"SH024");act(r,s,Action::craft(mod));check(Rules::shield(s)==7,"First paidModifier grants7");covered.insert("UGS-095");
    s=fixture();acquire(r,s,"UGS-055");start(r,s);collect(r,s);for(int i=0;i<3;++i)act(r,s,Action::craft(memory(s,"SH109")));check(Rules::shield(s)==6,"Heavy5materials firsttwo grants");covered.insert("UGS-055");
});
run("end-turn supplies and installed/reserve distinction",[&]{for(const auto* id:{"UGS-004","UGS-010","UGS-047","UGS-086","UGS-087","UGS-109"}){auto s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Attack,0,1};acquire(r,s,id);start(r,s);collect(r,s);const auto result=r.apply(s,Action::endTurn());ok(result);const auto expected=(std::string(id)=="UGS-010"||std::string(id)=="UGS-086")?5:std::string(id)=="UGS-047"?3:4;check(std::any_of(result.events.begin(),result.events.end(),[&](const Event&e){return e.type=="first_install"&&e.amount==expected;}),std::string(id)+" expected first install");covered.insert(id);}
    auto s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};for(const auto* id:{"MY1-19","UGS-005","UGS-028","UGS-091","UGS-108"})acquire(r,s,id);start(r,s);collect(r,s);ok(r.grantPart(s,"SH001"));act(r,s,Action::load({part(s,"SH001")}));ok(r.grantPlainPart(s,Kind::Shield,10,"fixture",true));act(r,s,Action::endTurn());check(s.bullet.size()==1,"Harness keeps assembly once");check(s.enemies[0].hp==995,"Nozzle reads10 before enemy phase");check(std::any_of(s.parts.begin(),s.parts.end(),[](const Part&p){return p.recipe=="MY1-19"&&p.createdRound==2;}),"Night delivery fresh nextturn");check(s.materials[0]==107&&s.materials[2]==102,"Idle furnace nextturn2Iron1Carbon");collect(r,s);act(r,s,Action::endTurn());check(s.bullet.empty(),"Harness later endturn unloads");covered.insert({"MY1-19","UGS-005","UGS-028","UGS-091","UGS-108"});
});
run("collection choice persists, fixed Precision retry and periodic grants",[&]{auto s=fixture();for(const auto* id:{"MY1-18","MY1-17","UGS-042","UGS-061","UGS-096"})acquire(r,s,id);start(r,s);collect(r,s,0);check(s.materials[0]==107,"First steering base5+fork2 before later source");check(s.upgradeChoices.front().kind==UpgradeChoiceKind::PrecisionRetry,"Earlier retry pauses later haul hooks");UpgradeAnswer a;a.values={2};answer(r,s,a);check(s.upgradeChoices.front().kind==UpgradeChoiceKind::HaulExchange,"Saved posthaul sorter");a={};a.removed={1,0,0,0,0};a.added={0,0,0,0,1};roundTrip(s);answer(r,s,a);check(s.materials[0]==110&&s.materials[4]==102,"Retry2,sort-1,hopper1,consolation1");check(s.precisionSpent&&s.precisionGoodFight==1&&s.precisionFailedFight==1,"Retry never replaces original outcome");covered.insert({"MY1-18","MY1-17","UGS-042","UGS-061","UGS-096"});
    s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};for(const auto* id:{"UGS-018","UGS-050","UGS-051","UGS-094","UGS-099","UGS-117","UGS-076"})acquire(r,s,id);start(r,s);collect(r,s);check(s.materials[0]==104&&s.materials[1]==101,"Coupler removes authored firstIron/Copper");for(int turn=2;turn<=5;++turn){act(r,s,Action::endTurn());if(turn==4){check(s.upgradeChoices.front().source=="UGS-099","Cycle4 storedmaterial choice");a={};a.values={3};answer(r,s,a);}collect(r,s);}check(s.materials[3]>=107,"Cycle4 Glass2");check(s.enemies[0].hp==992,"Pulse2 on turns2to5");covered.insert({"UGS-018","UGS-050","UGS-051","UGS-094","UGS-099","UGS-117","UGS-076"});
});
run("independent regressions: persistent first-shot and recoil before Suture",[&]{auto s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};acquire(r,s,"UGS-001");start(r,s);collect(r,s);next(r,s);next(r,s);shot(r,s);check(s.enemies[0].hp==988,"Ballistic Starter survives idle turns");
    s=fixture();acquire(r,s,"UGS-066");acquire(r,s,"MAU-05");start(r,s);collect(r,s);act(r,s,Action::craft(copy(s,"MA001")));act(r,s,Action::craft(memory(s,"MA001")));s.hp=4;s.enemies[0].mesh=2;act(r,s,Action::craft(memory(s,"MA019")));check(s.phase==Phase::Defeat&&s.hp==0&&s.enemies[1].hp==1000,"Earlier Arc reaction kills before later Suture");covered.insert("MAU-05");
});
run("printed recipe copies drop later upgrade values, keep grant provenance",[&]{auto s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};acquire(r,s,"UGS-140");start(r,s);collect(r,s);act(r,s,Action::craft(memory(s,"SH026")));check(Rules::shield(s)==8,"Original printed4 plus upgrade4");Id original=0;for(const auto&p:s.parts)if(p.recipe=="SH026")original=p.id;act(r,s,Action::remove(original));Action a=Action::craft(memory(s,"SH118"));a.parts={original};act(r,s,a);next(r,s);std::vector<Id> copies;for(const auto&p:s.parts)if(p.recipe=="SH026"&&p.id!=original&&p.place==Place::Reserve){check(p.origin==PartOrigin::Copied&&p.upgradeShield==0&&p.creator=="SH118","Printed-only copy origin and values");copies.push_back(p.id);}check(copies.size()==2,"Two copied outputs");for(Id id:copies)act(r,s,Action::install(id));check(Rules::shield(s)==14,"Normal6 delivery plus printed4+4");roundTrip(s);});
run("equipment cooling and actual-material Use milestones",[&]{auto s=fixture();acquire(r,s,"MY1-10");start(r,s);collect(r,s);s.memory[0].cooldown=3;Action a;a.type=ActionType::ActivateUpgrade;a.upgrade="MY1-10";a.subject=s.memory[0].id;const auto materials=s.materials;act(r,s,a);check(s.memory[0].cooldown==0&&s.materials==materials,"Equipment clears counters without material payment");s.memory[1].cooldown=1;a.subject=s.memory[1].id;rejection(r,s,a);covered.insert("MY1-10");
    s=fixture();acquire(r,s,"MY1-11");start(r,s);UpgradeAnswer choice;choice.values={0};answer(r,s,choice);collect(r,s);const auto before=s.materials[0];for(int i=0;i<4;++i)act(r,s,Action::craft(memory(s,"SH001")));check(s.materials[0]==before-4+5,"Third actual Iron-paying Use grants once");covered.insert("MY1-11");
});
run("victory healing, growth and kill-qualified Credits",[&]{auto s=fixture();acquire(r,s,"UGS-002");const auto credits=s.credits;UpgradeEvent e;e.kind=UpgradeEventKind::Victory;ok(r.upgradeEvent(s,e));check(s.credits==credits,"No-kill notification cannot reward kills");e.baseValue=3;ok(r.upgradeEvent(s,e));check(s.credits==credits+8,"Multiple kills still one payout");covered.insert("UGS-002");
    s=fixture();acquire(r,s,"UGS-065");event(r,s,UpgradeEventKind::Escaped);check(s.hp==40&&ownedUpgrade(s,"UGS-065")->charges==1,"Escape keeps Dressing for next win");event(r,s,UpgradeEventKind::Victory);event(r,s,UpgradeEventKind::Victory);check(s.hp==50&&ownedUpgrade(s,"UGS-065")->charges==0,"Dressing consumes one permanent charge");covered.insert("UGS-065");
    s=fixture();acquire(r,s,"UGS-036");event(r,s,UpgradeEventKind::Escaped);check(s.hp==40,"No archive heal after escape");event(r,s,UpgradeEventKind::Victory);check(s.hp==41,"Nine copies heal one");for(int i=0;i<21;++i)memory(s,"SH001");event(r,s,UpgradeEventKind::Victory);check(s.hp==45,"Archive heal capped4");covered.insert("UGS-036");
    s=fixture();acquire(r,s,"UGS-074");s.hp=41;event(r,s,UpgradeEventKind::Victory);check(s.hp==41,"Above half does not heal");s.hp=40;event(r,s,UpgradeEventKind::Victory);check(s.hp==48,"Exact half heals8");covered.insert("UGS-074");
    s=fixture();acquire(r,s,"UGS-129");event(r,s,UpgradeEventKind::Escaped);check(s.maxHp==80,"Growth excludes escape");event(r,s,UpgradeEventKind::Victory);check(s.maxHp==81&&s.hp==41,"Win growth also heals1");covered.insert("UGS-129");
});
run("campaign entitlements survive skipped shops and consume together",[&]{auto s=fixture();acquire(r,s,"UGS-033");acquire(r,s,"UGS-073");for(int i=0;i<2;++i)event(r,s,UpgradeEventKind::Victory);event(r,s,UpgradeEventKind::PartSold);check(s.maxHp==80&&s.hp==40,"Part sales do not redeem core dividend");roundTrip(s);event(r,s,UpgradeEventKind::CoreSold);check(s.maxHp==82&&s.hp==42,"Two victories redeem two dividends together");event(r,s,UpgradeEventKind::Purchase);check(s.hp==48,"Two warranties heal6 together");event(r,s,UpgradeEventKind::CoreSold);event(r,s,UpgradeEventKind::Purchase);check(s.maxHp==82&&s.hp==48,"Split transaction cannot repeat entitlements");covered.insert({"UGS-033","UGS-073"});
    s=fixture();acquire(r,s,"UGS-072");event(r,s,UpgradeEventKind::Victory);check(s.credits==110,"Unspent Credit Escrow pays10");event(r,s,UpgradeEventKind::Purchase);event(r,s,UpgradeEventKind::Victory);check(s.credits==110,"First later purchase permanently disables payouts");covered.insert("UGS-072");
    s=fixture();acquire(r,s,"MY1-16");UpgradeEvent sale;sale.kind=UpgradeEventKind::PartSold;sale.baseValue=20;ok(r.upgradeEvent(s,sale));ok(r.upgradeEvent(s,sale));check(s.credits==112,"Salvage match capped12 oncefight");covered.insert("MY1-16");
    s=fixture();acquire(r,s,"UGS-085");check(s.credits==200,"Acquisition Credits applied once");const auto before=serialize(s);check(!r.acquireUpgrade(s,"UGS-085").ok&&serialize(s)==before,"Cannot reacquire refund item");covered.insert("UGS-085");
});
run("finite fight lease, Officer awakenings and pending vouchers",[&]{auto s=fixture();acquire(r,s,"UGS-035");for(int fight=1;fight<=6;++fight){s.parts.clear();s.bullet.clear();start(r,s);collect(r,s);const auto before=s.enemies[0].hp;shot(r,s);shot(r,s);shot(r,s);check(before-s.enemies[0].hp==(fight<=5?24:18),"Only first two shots during five leased fights");event(r,s,fight%2?UpgradeEventKind::Escaped:UpgradeEventKind::Victory);}check(ownedUpgrade(s,"UGS-035")->charges==0,"Escape consumes lease charge");covered.insert("UGS-035");
    s=fixture();acquire(r,s,"UGS-045");acquire(r,s,"UGS-125");s.encounterClass=EncounterClass::Regular;event(r,s,UpgradeEventKind::Victory);check(ownedUpgrade(s,"UGS-045")->campaignCount==0,"Regular win gives no Officer level");s.encounterClass=EncounterClass::Officer;for(int i=0;i<4;++i)event(r,s,UpgradeEventKind::Victory);check(ownedUpgrade(s,"UGS-045")->campaignCount==3&&upgradeCounter(*ownedUpgrade(s,"UGS-125"),"awakened")==1,"Officer threshold and level cap");start(r,s);collect(r,s);check(s.materials[0]==106,"Awakened opener steers1");shot(r,s);check(s.enemies[0].hp==981,"6base+6training+7awakened");shot(r,s);check(s.enemies[0].hp==975,"Opener consumed once");covered.insert({"UGS-045","UGS-125"});
    s=fixture();acquire(r,s,"UGS-126");start(r,s);collect(r,s);check(s.materials[0]==104&&s.materials[1]==101,"Loan removes authored Iron and Copper from firstbase");event(r,s,UpgradeEventKind::Escaped);check(upgradePrecisionWidthPercent(s)==110&&ownedUpgrade(s,"UGS-126")->charges==0,"Completed loan permanently widens originalregion");start(r,s);const auto previous=s.materials;collect(r,s);check(s.materials[0]-previous[0]==5&&s.materials[1]-previous[1]==2,"No second loan deduction");covered.insert("UGS-126");
    s=fixture();acquire(r,s,"UGS-142");s.precisionFailedFight=2;event(r,s,UpgradeEventKind::Victory);start(r,s);check(s.materials[0]==101,"Multiple failures make one next-entry Iron");start(r,s);check(s.materials[0]==101,"Entry voucher consumed");covered.insert("UGS-142");
    s=fixture();acquire(r,s,"UGS-146");event(r,s,UpgradeEventKind::Victory);UpgradeAnswer a;a.values={4};answer(r,s,a);event(r,s,UpgradeEventKind::Victory);a.values={2};answer(r,s,a);roundTrip(s);start(r,s);check(s.materials[2]==102&&s.materials[4]==100,"Latest shipment replaces rather than stacks");start(r,s);check(s.materials[2]==102,"Shipment consumed at entry");covered.insert("UGS-146");
});
run("reward-copy provenance and independently spent physical coupons",[&]{auto s=fixture();for(const auto* id:{"UGS-012","UGS-016","UGS-040","UGS-041","UGS-069","UGS-134","UGS-148"})acquire(r,s,id);const auto shield=memory(s,"SH002");accept(r,s,shield,AcquisitionSource::Shop);check(s.upgradeRequests.empty()&&s.memory.back().tags.empty(),"Shop copy is no victory acceptance");accept(r,s,shield);check(s.upgradeRequests.front().kind==UpgradeRequestKind::CopyRecipe&&s.upgradeRequests.front().recipeCopy==shield,"First victory copy request names exact copy");roundTrip(s);acknowledge(r,s);check(s.credits==106,"Accepted reward pays Filing once");const auto utility=memory(s,"SH007");accept(r,s,utility);check(s.upgradeRequests.empty(),"Second accepted recipe does not recurse Carbonpaper");accept(r,s,memory(s,"SH001"),AcquisitionSource::Upgrade);check(upgradeCounter(*ownedUpgrade(s,"UGS-016"),"acceptances")==2,"Generated copies do not advance acceptance counter");for(int i=0;i<3;++i)accept(r,s,memory(s,"SH001"));check(s.hp==48,"Fifth actual reward acceptance heals8");start(r,s);collect(r,s);const auto resources=s.materials;act(r,s,Action::craft(shield));check(s.materials[0]==resources[0]&&s.materials[1]==resources[1]-1&&s.parts.back().upgradeShield==2,"Shield coupon saves1Iron and paid copy retains Reinforced");act(r,s,Action::craft(utility));check(s.materials[1]==resources[1]-1&&s.materials[3]==resources[3]-1,"Utility startup coupon only Copper");covered.insert({"UGS-012","UGS-016","UGS-040","UGS-041","UGS-069","UGS-134"});
    s=fixture();acquire(r,s,"UGS-148");const auto light=memory(s,"SH002");accept(r,s,light,AcquisitionSource::Victory,1,true);start(r,s);collect(r,s);const auto before=s.materials;act(r,s,Action::craft(light));check(s.materials[0]==before[0]&&s.materials[1]==before[1]-1,"Light-Touch tie chooses Iron only");check(s.memory.back().tags[0].usedFight==s.fightSerial,"Tag spent on exact physical copy");covered.insert("UGS-148");
});
run("one victory screen shares acceptance allowances across nested offers",[&]{auto s=fixture();acquire(r,s,"UGS-069");acquire(r,s,"UGS-040");const auto first=memory(s,"SH002"),second=memory(s,"SH002");accept(r,s,first,AcquisitionSource::Victory,1);accept(r,s,second,AcquisitionSource::Victory,2);check(s.credits==106,"Second nested offer does not create a second main victory screen");check(s.memory[s.memory.size()-2].tags.size()==1&&s.memory.back().tags.empty(),"Only first Shield acceptance from whole victory is reinforced");});
run("source-typed offers pause, persist and resume in acquired order",[&]{for(const auto& id:std::vector<std::string>{"MY1-06","UGS-032","UGS-089"}){auto s=fixture();acquire(r,s,id);check(s.upgradeRequests.size()==1,"One acquisition request");const auto q=s.upgradeRequests.front();if(id=="MY1-06")check(q.rarity==2&&q.sharedOnly&&!q.optional&&upgradeGeneralMemoryBonus(s)==4,"Annex exact shared Uncommon offer and4slots");if(id=="UGS-032")check(q.kind==UpgradeRequestKind::CopyRecipe&&q.recipeCopy==0,"Copier adapter selects stored physical source");if(id=="UGS-089")check(q.kind==UpgradeRequestKind::RecipeOffer&&q.offers==3&&q.count==3,"Three saved sequential normal offers");roundTrip(s);rejection(r,s,Action::craft(copy(s,"SH001")));acknowledge(r,s);check(s.upgradeResolution.empty(),"Resume consumes finished frame");covered.insert(id);}
    auto s=fixture();acquire(r,s,"UGS-133");start(r,s);check(s.phase==Phase::Collection&&s.upgradeRequests.front().source=="UGS-133"&&s.upgradeRequests.front().rarity==1&&s.upgradeRequests.front().sharedOnly,"Borrowed shared Common choice precedes first turn");roundTrip(s);acknowledge(r,s);check(s.phase==Phase::Collection,"Borrow completion resumes first collection");covered.insert("UGS-133");
    s=fixture();acquire(r,s,"MY1-13");s.encounterClass=EncounterClass::Officer;event(r,s,UpgradeEventKind::Victory);check(s.upgradeRequests.empty(),"Subscription excludes Officer");s.encounterClass=EncounterClass::Regular;for(int i=0;i<3;++i)event(r,s,UpgradeEventKind::Victory);check(s.upgradeRequests.front().kind==UpgradeRequestKind::Subscription,"Third Regular earned persistent selection");roundTrip(s);acknowledge(r,s);covered.insert("MY1-13");
});
run("post-victory offer filters and carried periodic clocks",[&]{for(const auto& item:std::vector<std::pair<std::string,int>>{{"UGS-031",1},{"UGS-034",3},{"UGS-062",2},{"UGS-101",1},{"UGS-147",1}}){auto s=fixture();acquire(r,s,item.first);s.encounterClass=item.first=="UGS-147"?EncounterClass::Officer:EncounterClass::Regular;for(int i=1;i<=item.second;++i){event(r,s,UpgradeEventKind::Victory);if(i<item.second)check(s.upgradeRequests.empty(),"Periodic offer not early");}check(s.upgradeRequests.size()==1,"One authored reward request");const auto q=s.upgradeRequests.front();if(item.first=="UGS-034"||item.first=="UGS-062")check(q.kind==UpgradeRequestKind::AddRewardOption&&q.sharedOnly&&q.filterKind&&q.recipeKind==(item.first=="UGS-034"?Kind::Utility:Kind::Modifier),"Added option type and source filter");if(item.first=="UGS-031")check(q.kind==UpgradeRequestKind::AddRewardOption&&q.normalOffer&&q.sharedOnly,"Decoder modifies every normal offer");if(item.first=="UGS-101")check(q.kind==UpgradeRequestKind::AddRewardOffer&&q.normalOffer,"Regular second independent normal offer");if(item.first=="UGS-147")check(q.kind==UpgradeRequestKind::AddRewardOffer&&q.rarity==3,"Officer adds separate Rare offer");roundTrip(s);acknowledge(r,s);covered.insert(item.first);}
    auto s=fixture();acquire(r,s,"UGS-150");for(int i=1;i<=5;++i){event(r,s,UpgradeEventKind::Victory);if(i<5)check(s.upgradeRequests.empty(),"Uncommon claim waits five victories");}check(s.upgradeRequests.front().kind==UpgradeRequestKind::UpgradeOffer&&s.upgradeRequests.front().rarity==2&&s.upgradeRequests.front().sharedOnly&&ownedUpgrade(s,"UGS-150")->charges==0,"Fifth claim permanently spent before choice");acknowledge(r,s);event(r,s,UpgradeEventKind::Victory);check(s.upgradeRequests.empty(),"No second campaign claim");covered.insert("UGS-150");
});
run("Mystery outcomes and exact nonstacking entry shipment",[&]{auto s=fixture();acquire(r,s,"UGS-097");acquire(r,s,"UGS-132");event(r,s,UpgradeEventKind::Victory);check(s.hp==40&&upgradeCounter(*ownedUpgrade(s,"UGS-132"),"shipment")==0,"Combat Mystery is not noncombat");event(r,s,UpgradeEventKind::Noncombat);event(r,s,UpgradeEventKind::Noncombat);check(s.hp==46,"Completed noncombat triggers one heal each");start(r,s);check(s.parts.size()==2&&s.parts[0].recipe=="SH001"&&Rules::shield(s)==6,"Two Mysteries produce one named shipment");s.parts.clear();start(r,s);check(s.parts.empty(),"Shipment clears after delivery");covered.insert({"UGS-097","UGS-132"});
    s=fixture();acquire(r,s,"UGS-113");event(r,s,UpgradeEventKind::Noncombat);check(s.upgradeRequests.front().kind==UpgradeRequestKind::UpgradeOffer&&s.upgradeRequests.front().rarity==1&&s.upgradeRequests.front().optional,"City survey offers Common instead of Credits");acknowledge(r,s);event(r,s,UpgradeEventKind::Noncombat);check(s.upgradeRequests.empty(),"One survey per city");event(r,s,UpgradeEventKind::CityStart);event(r,s,UpgradeEventKind::Noncombat);check(s.upgradeRequests.size()==1,"New city renews survey");covered.insert("UGS-113");
    s=fixture();acquire(r,s,"UGS-131");const auto rng=s.rng.state;event(r,s,UpgradeEventKind::ShopRestocked);check(s.upgradeRequests.front().kind==UpgradeRequestKind::RevealReward&&s.rng.state==rng,"Reveal requests information without drawing reward RNG");covered.insert("UGS-131");
});
run("sacrifice clocks and lethal upgrade recoil interrupt the original effect",[&]{auto s=fixture();acquire(r,s,"UGS-038");acquire(r,s,"UGS-056");start(r,s);collect(r,s);const auto glass=s.materials[3];for(int i=0;i<3;++i){ok(r.grantPart(s,"SH001"));Action a=Action::craft(memory(s,"SH032"));a.parts={part(s,"SH001")};act(r,s,a);}check(s.enemies[0].hp==994&&s.enemies[1].hp==1000,"First two sacrificed parts strike lowestslot");check(s.materials[3]==glass-r.recipe("SH032")->cost[3]*3+1,"Third sacrifice grants1Glass");shot(r,s);check(upgradeCounter(*ownedUpgrade(s,"UGS-056"),"sacrifices")==3,"Firing is not sacrifice");covered.insert({"UGS-038","UGS-056"});
    s=fixture();acquire(r,s,"UGS-038");start(r,s);collect(r,s);s.hp=1;s.enemies[0].mesh=2;ok(r.grantPart(s,"SH001"));Action a=Action::craft(memory(s,"SH065"));a.parts={part(s,"SH001")};act(r,s,a);check(s.phase==Phase::Defeat&&Rules::shield(s)==0&&s.deliveries.empty(),"Sacrifice recoil stops later Shield and delivery");
});
run("novel enemy debuff types exclude extra present stacks",[&]{auto s=fixture();acquire(r,s,"UGS-029");s.enemies=makeCinderwallFormation("C1-F-CHASSIS",42,"hazard",s.nextId);start(r,s);collect(r,s);s.enemies[0].robotAction="thermal_runaway";s.enemies[0].intent={Move::Support,0,0};s.burn=3;act(r,s,Action::endTurn());check(s.maxHp==80,"More enemy stacks of already present Burn do not qualify");collect(r,s);s.burn=0;s.enemies[0].robotAction="thermal_runaway";s.enemies[0].intent={Move::Support,0,0};act(r,s,Action::endTurn());check(s.maxHp==81,"First new enemy Burn grows1");collect(r,s);s.burn=0;s.enemies[0].robotAction="thermal_runaway";s.enemies[0].intent={Move::Support,0,0};act(r,s,Action::endTurn());check(s.maxHp==81,"Same type not new twice after cleared");roundTrip(s);covered.insert("UGS-029");});
run("canonical grants qualify Slug listeners and preserve paid event identity",[&]{auto s=fixture();acquire(r,s,"MY1-03");acquire(r,s,"UGS-044");acquire(r,s,"UGS-122");start(r,s);collect(r,s);Id slug=0;for(const auto&p:s.parts)if(p.kind==Kind::Ammo){slug=p.id;check(p.canonicalRecipe=="SH001"&&p.creator=="MY1-03"&&p.resaleReference=="generated:ammo:6","Canonical type is separate from source and resale");}const auto iron=s.materials[0];act(r,s,Action::load({slug}));act(r,s,Action::fire(s.enemies[0].id));check(s.materials[0]==iron+1&&std::any_of(s.parts.begin(),s.parts.end(),[](const Part&p){return p.recipe=="SH003";}),"Generic Mayor Slug activates canonical readers");
    s=fixture();acquire(r,s,"MAU-03");start(r,s);collect(r,s);s.heat=10;ok(r.grantPart(s,"MA041"));const auto spread=part(s,"MA041");ok(r.grantPart(s,"SH001"));act(r,s,Action::load({part(s,"SH001"),spread}));auto result=r.apply(s,Action::fire(s.enemies[0].id,{{spread,s.enemies[1].id}}));ok(result);const auto payment=std::find_if(result.events.begin(),result.events.end(),[](const Event&e){return e.type=="heat_cost";});check(payment!=result.events.end()&&payment->subject==spread&&payment->source=="MA041"&&payment->amount==4,"Fire cost identifies physical paid source");check(std::any_of(result.events.begin(),result.events.end(),[](const Event&e){return e.type=="part_created"&&e.source=="MAU-03";}),"Payment trigger grant identifies its own source");check(eventJson(*payment).find("\"source\":\"MA041\"")!=std::string::npos&&eventJson(*payment).find("\"paid\":[")!=std::string::npos,"Machine event output retains provenance fields");roundTrip(s);
});
run("Fire reaction clocks merge physical bindings with upgrade acquisition",[&]{for(const bool shieldEarlier:{false,true}){auto s=fixture();acquire(r,s,shieldEarlier?"MY1-M1":"UGS-060");acquire(r,s,shieldEarlier?"UGS-060":"MY1-M1");start(r,s);collect(r,s);shot(r,s);shot(r,s);s.hp=2;s.enemies[1].mesh=2;ok(r.grantPart(s,"MA041"));const auto spread=part(s,"MA041");ok(r.grantPart(s,"SH001"));act(r,s,Action::load({part(s,"SH001"),spread}));act(r,s,Action::fire(s.enemies[0].id,{{spread,s.enemies[2].id}}));check((s.phase==Phase::Defeat)==!shieldEarlier,"Earlier acquired effect and its recoil finish before later Heat-ledger Shield");if(shieldEarlier)check(s.hp==2&&Rules::shield(s)==6,"Earlier Heat-ledger Shield absorbs later Tripod recoil");else check(s.hp==0&&Rules::shield(s)==0,"Final death stops later delayed payment grant");}
    for(const bool bindingEarlier:{false,true}){auto s=fixture();if(!bindingEarlier)acquire(r,s,"UGS-060");ok(r.grantPart(s,"SH062"));act(r,s,Action::install(part(s,"SH062")));if(bindingEarlier)acquire(r,s,"UGS-060");start(r,s);collect(r,s);shot(r,s);shot(r,s);s.hp=2;s.parts.clear();s.protection.clear();ok(r.grantPart(s,"SH062"));act(r,s,Action::install(part(s,"SH062")));for(auto&p:s.parts)if(p.recipe=="SH062"){p.shield=0;p.bindingOrder=bindingEarlier?1:s.nextOrder-1;}s.enemies[1].mesh=2;shot(r,s);check((s.phase==Phase::Defeat)==!bindingEarlier,"Physical after-shot Shield uses binding order against Tripod");}
});
run("committed Trial copy preserves earlier crafting attachment",[&]{auto s=fixture();acquire(r,s,"UGS-015");start(r,s);collect(r,s);ok(r.grantPart(s,"SH103"));Action activation;activation.type=ActionType::Activate;activation.subject=part(s,"SH103");act(r,s,activation);act(r,s,Action::craft(copy(s,"SH001")));std::vector<Id> slugs;for(const auto&p:s.parts)if(p.recipe=="SH001"){slugs.push_back(p.id);check(p.attachments.size()==1&&p.attachments[0].damage==8,"Committed output copy keeps Fine Mould attachment");}check(slugs.size()==2,"One original plus one Trial copy");act(r,s,Action::load(slugs));act(r,s,Action::fire(s.enemies[0].id));check(s.enemies[0].hp==972,"Both committed6+8 Slugs contribute once");});
run("native same-seed event and snapshot parity through saved choices",[&]{const auto replay=[&](bool reload){auto s=fixture();for(auto&e:s.enemies)e.intent=e.pattern[0]={Move::Recover,0,0};std::string events;const auto apply=[&](const Action&a){const auto result=r.apply(s,a);ok(result);for(const auto&e:result.events)events+=eventJson(e);};for(const auto* id:{"MY1-08","UGS-024","UGS-116","UGS-001","UGS-015","MY3-03","UGS-123"})acquire(r,s,id);start(r,s);while(!s.upgradeChoices.empty()){if(reload){State restored;std::string error;check(deserialize(serialize(s),restored,error),error);s=restored;}Action choice;choice.type=ActionType::ResolveUpgradeChoice;choice.upgradeChoice.choice=s.upgradeChoices.front().id;choice.upgradeChoice.values={1};apply(choice);}apply(Action::collect(0,2));apply(Action::craft(copy(s,"SH001")));std::vector<Id> slugs;for(const auto&p:s.parts)if(p.kind==Kind::Ammo)slugs.push_back(p.id);apply(Action::load(slugs));apply(Action::fire(s.enemies[0].id));apply(Action::endTurn());roundTrip(s);return std::make_pair(serialize(s),events);};const auto uninterrupted=replay(false),resumed=replay(true);check(uninterrupted==resumed,"Saved choice resume reproduces every event, cursor and RNG state");});
std::cout<<"Remaining core author assertions:";for(const auto& id:eligibleUpgradeIds())if(!covered.count(id))std::cout<<" "<<id;std::cout<<"\n";
std::cout<<assertions<<" assertions; "<<covered.size()<<" explicitly covered upgrade IDs; "<<failures<<" failures\n";return failures?1:0;}
