#include "overkill/core.hpp"
#include "overkill/upgrades.hpp"
#include <algorithm>
#include <functional>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
using namespace overkill;
namespace {
Rules rules;int checks=0,passed=0,failed=0;
void check(bool value,const std::string& reason){++checks;if(!value)throw std::runtime_error(reason);}
void group(const std::string& name,const std::function<void()>& test){try{test();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
State scene(){State s;s.hotBarrel=false;s.phase=Phase::Preparation;s.materials={100,100,100,100,100};s.rng=Rng::seeded(31,"copy-attribution");s.encounter="copy-attribution";Enemy e;e.id=s.nextId++;e.hp=e.maxHp=10000;e.name=e.definition="Controlled quiet target";e.intent={Move::Recover,0,0};e.pattern={e.intent};s.enemies.push_back(e);return s;}
Result act(State& s,const Action& a){const auto before=serialize(s);const auto p=rules.preview(s,a);check(serialize(s)==before,"Preview changed live state");const auto result=rules.apply(s,a);check(result.ok,result.reason);check(p.result.ok&&serialize(p.state)==serialize(s)&&p.result.events.size()==result.events.size(),"Exact preview state");for(std::size_t i=0;i<result.events.size();++i)check(eventJson(result.events[i])==eventJson(p.result.events[i]),"Exact preview events");return result;}
void own(State& s,const std::string& id){const auto r=rules.acquireUpgrade(s,id);check(r.ok,r.reason);}
void begin(State& s){check(rules.startUpgrades(s,EncounterClass::Regular).ok,"Start owned fight upgrades");act(s,Action::collect(0));}
void next(State& s){act(s,Action::endTurn());act(s,Action::collect(0));}
void reload(State& s){const auto bytes=serialize(s);State loaded;std::string error;check(deserialize(bytes,loaded,error),error);check(bytes==serialize(loaded),"Canonical restored attribution");s=std::move(loaded);}
Id store(State& s,const std::string& id){const Id n=s.nextId++;s.memory.push_back({n,id,0,0,0});return n;}
Part& part(State& s,Id id){for(auto& p:s.parts)if(p.id==id)return p;throw std::runtime_error("Physical output missing");}
std::vector<Id> use(State& s,Id memory,Action a={}){const auto before=s.nextId;a.type=ActionType::Craft;a.subject=memory;const auto result=act(s,a);int count=0;for(const auto& e:result.events)if(e.type=="recipe_used"){++count;check(e.subject==memory,"Actual paid source-copy identity");if(e.source=="SH001")check(e.paid==Materials{1,0,0,0,0},"Real resource-paid Plain Slug");}check(count==1,"Copies never replay recipe Use");std::vector<Id> out;for(const auto& p:s.parts)if(p.id>=before)out.push_back(p.id);return out;}
std::vector<Id> use(State& s,const std::string& id,Action a={}){return use(s,store(s,id),a);}
Amount fire(State& s,const std::vector<Id>& ids){act(s,Action::load(ids));const auto hp=s.enemies[0].hp;act(s,Action::fire(s.enemies[0].id));for(Id id:ids)check(std::none_of(s.parts.begin(),s.parts.end(),[&](const Part& p){return p.id==id;}),"Consumed exact output");return hp-s.enemies[0].hp;}
void chosenTag(State& s,Id id){own(s,"UGS-046");check(s.upgradeChoices.size()==1,"Permanent recipe tag choice");Action a;a.type=ActionType::ResolveUpgradeChoice;a.upgradeChoice.choice=s.upgradeChoices.front().id;a.upgradeChoice.objects={id};act(s,a);}
bool jigMarker(const Part& p){return std::any_of(p.attachments.begin(),p.attachments.end(),[](const Attachment& a){return a.source=="UGS-121";});}
void activate(State& s,Id id,Action a={}){a.type=ActionType::Activate;a.subject=id;act(s,a);}
}
int main(){
group("UC01 one physical Jig bonus in both acquisition orders with optional other committed tag",[]{for(bool other:{false,true})for(bool first:{false,true}){auto s=scene();const auto recipe=store(s,"SH001");if(other)chosenTag(s,recipe);own(s,first?"UGS-121":"UGS-015");own(s,first?"UGS-015":"UGS-121");begin(s);const auto ids=use(s,recipe);check(ids.size()==2,"Exactly original and lease duplicate");check(part(s,ids[0]).upgradeDamage==(other?3:2)&&part(s,ids[1]).upgradeDamage==(other?1:0),"Only Jig component omitted from committed duplicate");check(jigMarker(part(s,ids[0]))&&!jigMarker(part(s,ids[1])),"Attribution belongs only to original");check(part(s,ids[0]).origin==PartOrigin::Produced&&part(s,ids[1]).origin==PartOrigin::Copied,"Physical production provenance unchanged");for(Id id:ids)check(part(s,id).resaleReference=="SH001"&&part(s,id).materialBasis==Materials{1,0,0,0,0}&&part(s,id).sourceRecipeCopy==recipe,"Copy canonical value and source identity preserved");reload(s);check(fire(s,ids)==(other?16:14),"Real combined shot excludes duplicated Jig2");}});
group("UC02 zero attribution marker leaves ordinary bonus timing eligibility and resale intact",[]{auto s=scene();own(s,"MY1-01");own(s,"UGS-121");own(s,"UGS-015");begin(s);const auto ids=use(s,"SH001");check(part(s,ids[0]).upgradeDamage==4&&part(s,ids[1]).upgradeDamage==2,"Mayor2 stays copyable");const Materials prices{4,4,4,5,6};for(Id id:ids){check(isUnusedPart(part(s,id)),"Marker does not make unused Ammo used");check(upgradePartSaleValue(s,part(s,id),prices)==2,"Canonical resale unchanged");}for(const auto& a:part(s,ids[0]).attachments)if(a.source=="UGS-121")check(a.damage==0&&a.heat==0&&a.dueRound==0,"Marker adds no second damage or timing hook");next(s);reload(s);const auto heat=s.heat;check(fire(s,ids)==18&&s.heat==heat,"Saved original10 + copy8; marker triggers no Heat");const auto later=use(s,"SH001");check(later.size()==1&&part(s,later[0]).upgradeDamage==4,"Next turn ordinary/Jig renew; lease does not rearm");});
group("UC03 printed SH118 descendants strip all later bonuses while saved original retains them",[]{auto s=scene();const auto recipe=store(s,"SH001");chosenTag(s,recipe);own(s,"UGS-121");begin(s);const auto original=use(s,recipe)[0];Action a;a.parts={original};use(s,"SH118",a);reload(s);next(s);std::vector<Id> copies;for(const auto& p:s.parts)if(p.creator=="SH118")copies.push_back(p.id);check(copies.size()==2&&part(s,original).upgradeDamage==3&&jigMarker(part(s,original)),"Original saved bonus and two descendants");for(Id id:copies)check(part(s,id).upgradeDamage==0&&part(s,id).attachments.empty()&&part(s,id).resaleReference=="SH001","Printed-only copy excludes tagged bonuses");a.parts={copies[0]};use(s,"SH118",a);next(s);std::vector<Id> all{original};for(const auto& p:s.parts)if(p.creator=="SH118")all.push_back(p.id);check(all.size()==5,"Copy of printed copy produces two more without Jig attribution");reload(s);check(fire(s,all)==33,"Original9 and four printed6 descendants");});
group("UC04 committed ordinary damage attachment is preserved beside omitted Jig",[]{for(bool jigFirst:{false,true}){auto s=scene();const auto recipe=store(s,"SH001");chosenTag(s,recipe);own(s,jigFirst?"UGS-121":"UGS-015");own(s,jigFirst?"UGS-015":"UGS-121");begin(s);activate(s,use(s,"SH103")[0]);const auto ids=use(s,recipe);check(ids.size()==2,"Trial duplicate");for(Id id:ids)check(std::any_of(part(s,id).attachments.begin(),part(s,id).attachments.end(),[](const Attachment& a){return a.source=="SH103"&&a.damage==8;}),"Fine Mould committed attachment survives copy");next(s);reload(s);check(fire(s,ids)==32,"Original17 and copy15 preserve all ordinary committed bonuses");}});
group("UC05 printed Return Delivery fresh copy excludes Jig without resetting its original turn allowance",[]{auto s=scene();own(s,"UGS-121");begin(s);activate(s,use(s,"SH072")[0]);const auto original=use(s,"SH001")[0];Action attached;attached.parts={original};activate(s,use(s,"SH036")[0],attached);act(s,Action::load({original}));auto a=Action::fire(s.enemies[0].id);a.partChoices={{0,original}};const auto hp=s.enemies[0].hp;act(s,a);check(hp-s.enemies[0].hp==12,"Original base6 plus Jig2 plus attached4");check(part(s,use(s,"SH001")[0]).upgradeDamage==0,"Copy scheduling does not rearm same-turn Jig");next(s);std::vector<Id> returned;for(const auto& p:s.parts)if(p.creator=="SH072")returned.push_back(p.id);check(returned.size()==1&&part(s,returned[0]).upgradeDamage==0&&part(s,returned[0]).attachments.empty(),"Printed returned copy has no Jig or attachment");check(fire(s,returned)==6,"Actual copied6");});
group("UC06 free named grants and failed paid Uses do not consume first paid Jig output",[]{auto s=scene();own(s,"UGS-121");begin(s);check(rules.grantPart(s,"SH001").ok,"Grant fixture");check(s.parts.back().upgradeDamage==0&&!jigMarker(s.parts.back()),"Grant is not paid production");const auto recipe=store(s,"SH001");s.materials[0]=0;const auto before=serialize(s);auto result=rules.apply(s,Action::craft(recipe));check(!result.ok&&result.events.empty()&&serialize(s)==before,"Failed payment atomic");s.materials[0]=1;const auto id=use(s,recipe)[0];check(part(s,id).upgradeDamage==2&&jigMarker(part(s,id)),"First actual paid use still qualifies");});
group("UC07 inconsistent copied attribution is rejected before committing delivery or round",[]{auto s=scene();own(s,"UGS-121");begin(s);const auto original=use(s,"SH001")[0];Part invalid=part(s,original);invalid.origin=PartOrigin::Copied;invalid.upgradeDamage=1;Delivery d;d.id=s.nextId++;d.source="controlled-corrupt-copy";d.dueRound=s.round+1;d.kind=DeliveryKind::PartCopy;d.parts={invalid};s.deliveries.push_back(d);const auto before=serialize(s);const auto result=rules.apply(s,Action::endTurn());check(!result.ok&&result.reason.find("attribution")!=std::string::npos&&result.events.empty()&&serialize(s)==before,"Never underflow or silently infer missing aggregate component");});
std::cout<<"SUMMARY "<<passed<<" passed, "<<failed<<" failed, "<<checks<<" assertions.\n";return failed?1:0;
}
