// Independent semantic probes. Expectations come from the exact catalogue/robot contracts.
#include "overkill/core.hpp"
#include "overkill/robots.hpp"
#include <algorithm>
#include <functional>
#include <iostream>
#include <numeric>
#include <stdexcept>
using namespace overkill;
namespace {
int passed=0,failed=0;
void expect(bool value,const std::string& why){if(!value)throw std::runtime_error(why);}
void equal(Amount actual,Amount wanted,const std::string& why){expect(actual==wanted,why+" expected="+std::to_string(wanted)+" actual="+std::to_string(actual));}
Result act(const Rules&r,State&s,const Action&a){auto out=r.apply(s,a);expect(out.ok,out.reason);return out;}
State arena(Amount damage=0,Amount hits=0){State s;s.encounter="expanded-independent";s.rng=Rng::seeded(651,s.encounter);s.phase=Phase::Preparation;s.hotBarrel=false;s.materials={500,500,500,500,500};Enemy e;e.id=s.nextId++;e.definition="QA";e.hp=e.maxHp=10000;e.intent={damage?Move::Attack:Move::Recover,damage,hits};e.pattern={e.intent};s.enemies={e};return s;}
State formation(const std::string&id){auto s=arena();s.enemies=makeCinderwallFormation(id,s.seed,s.encounter,s.nextId);return s;}
Id memory(State&s,const std::string&id){const auto n=s.nextId++;s.memory.push_back({n,id,0,0,0});return n;}
Result use(const Rules&r,State&s,const std::string&id,Action a={}){a.type=ActionType::Craft;a.subject=memory(s,id);return act(r,s,a);}
Part& part(State&s,Id id){auto it=std::find_if(s.parts.begin(),s.parts.end(),[&](const Part&p){return p.id==id;});expect(it!=s.parts.end(),"part missing");return *it;}
Id created(const Result&out){for(const auto&e:out.events)if(e.type=="part_created")return e.subject;throw std::runtime_error("expected part creation");}
Id craft(const Rules&r,State&s,const std::string&id,Action a={}){return created(use(r,s,id,a));}
Id grant(const Rules&r,State&s,const std::string&id){auto out=r.grantPart(s,id);expect(out.ok,out.reason);return created(out);}
Id plain(const Rules&r,State&s,Kind k,Amount n,bool installed=false){auto out=r.grantPlainPart(s,k,n,"qa-grant",installed);expect(out.ok,out.reason);return created(out);}
void install(const Rules&r,State&s,Id id,Action a={}){a.type=ActionType::Install;a.subject=id;act(r,s,a);}
void activate(const Rules&r,State&s,Id id,Action a={}){a.type=ActionType::Activate;a.subject=id;act(r,s,a);}
Result fire(const Rules&r,State&s,std::vector<Id> ids,Id target=0,Action a={}){act(r,s,Action::load(std::move(ids)));a.type=ActionType::Fire;a.target=target?target:s.enemies[0].id;return act(r,s,a);}
void next(const Rules&r,State&s){act(r,s,Action::endTurn());if(s.phase==Phase::Collection)act(r,s,Action::collect(0));}
void rejected(const Rules&r,State&s,const Action&a){const auto before=serialize(s);expect(!r.apply(s,a).ok,"expected rejection");expect(serialize(s)==before,"rejection changed state");}
void roundtrip(State&s){State decoded;std::string error;const auto before=serialize(s);expect(deserialize(before,decoded,error),error);expect(serialize(decoded)==before,"snapshot not canonical");s=decoded;}
Amount sum(const Materials&m){return std::accumulate(m.begin(),m.end(),Amount{0});}
void run(const char*name,const std::function<void()>&fn){try{fn();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
}
int main(){Rules r;
run("removed MA059 cannot reduce an enemy attack",[&]{auto s=arena(10,1);auto p=craft(r,s,"MA059");install(r,s,p);act(r,s,Action::remove(p));act(r,s,Action::endTurn());equal(s.hp,70,"HP without the source installed");});
run("removed MA086 cannot halve its chosen enemy attack",[&]{auto s=arena(10,1);auto p=craft(r,s,"MA086");Action choice;choice.target=s.enemies[0].id;install(r,s,p,choice);act(r,s,Action::remove(p));act(r,s,Action::endTurn());equal(s.hp,70,"HP without the source installed");});
run("first-bound SH060 zeroing precedes later MA055 Shield reading after reinstall",[&]{
    auto s=arena();auto zero=craft(r,s,"SH060"),read=craft(r,s,"MA055");install(r,s,zero);install(r,s,read);const auto order=part(s,zero).bindingOrder;act(r,s,Action::remove(zero));install(r,s,zero);expect(part(s,zero).bindingOrder==order,"reinstall changed binding order");const auto iron=s.materials[0];next(r,s);equal(s.materials[0]-iron,5,"later reader must see zero, only steered haul Iron");
});
run("source removal does not cancel already committed MA016 Shield delivery",[&]{auto s=arena();auto p=craft(r,s,"MA016");install(r,s,p);act(r,s,Action::remove(p));roundtrip(s);act(r,s,Action::endTurn());equal(Rules::shield(s),5,"fresh next-round delivery");expect(part(s,p).place==Place::Reserve,"source not kept in reserve");});
run("next-shot SH062 check expires when removed and does not rearm",[&]{auto s=arena();auto p=craft(r,s,"SH062");install(r,s,p);act(r,s,Action::remove(p));fire(r,s,{grant(r,s,"SH001")});install(r,s,p);fire(r,s,{grant(r,s,"SH001")});equal(Rules::shield(s),6,"missed check must not grant fresh7");});
run("SH094 reacts once per attack rather than once per hit",[&]{auto s=arena(4,2);install(r,s,craft(r,s,"SH094"));next(r,s);equal(s.enemies[0].hp,9993,"one7 counter for one two-hit attack");equal(s.hp,80,"16Shield covers8");});
run("MA108 requires a fully Shield-blocked attack",[&]{auto s=arena(20,1);install(r,s,craft(r,s,"MA108"));next(r,s);equal(s.hp,78,"18Shield absorbs18");equal(s.enemies[0].hp,10000,"partial block must not counter");equal(s.enemies[0].burn,0,"partial block must not apply Burn");});
run("copy retains source identity and resale while dropping attached bonuses",[&]{
    auto s=arena();auto original=craft(r,s,"SH009");Action pick;pick.parts={original};activate(r,s,craft(r,s,"SH036"),pick);const auto basis=part(s,original).materialBasis;use(r,s,"SH071",pick);roundtrip(s);next(r,s);Id clone=0;for(const auto&p:s.parts)if(p.id!=original&&p.recipe=="SH009")clone=p.id;expect(clone!=0,"fresh copy absent");equal(part(s,clone).createdRound,2,"copy age");expect(part(s,clone).materialBasis==basis&&part(s,clone).resaleReference=="SH009"&&part(s,clone).attachments.empty(),"copy lost immutable identity or kept later bonus");fire(r,s,{clone});equal(s.enemies[0].hp,9992,"printed copy damage8");fire(r,s,{original});equal(s.enemies[0].hp,9980,"original keeps attached+4");
});
run("copied generated SH026 Shield remains a pure grant without generator recursion",[&]{
    auto s=arena();auto p=craft(r,s,"SH026");act(r,s,Action::remove(p));Action a;a.parts={p};use(r,s,"SH102",a);next(r,s);std::vector<Id> copies;for(const auto&x:s.parts)if(x.recipe=="SH026"&&x.createdRound==2&&x.place==Place::Reserve)copies.push_back(x.id);equal(static_cast<Amount>(copies.size()),2,"two fresh generated copies");for(Id id:copies){equal(part(s,id).originalValue,4,"original fixed generated value");install(r,s,id);}equal(Rules::shield(s),14,"6 original scheduled+two4 copies");expect(s.deliveries.empty(),"copy manufactured generator schedule");
});
run("SH118 copied stored-momentum part starts fresh age",[&]{auto s=arena();auto old=craft(r,s,"SH090");next(r,s);Action a;a.parts={old};use(r,s,"SH118",a);next(r,s);Id clone=0;for(const auto&p:s.parts)if(p.recipe=="SH090"&&p.id!=old)clone=p.id;fire(r,s,{clone});equal(s.enemies[0].hp,9990,"copy starts at printed10");fire(r,s,{old});equal(s.enemies[0].hp,9964,"old two-round part deals26");});
run("SH110 reserved sacrifice cancels without consuming or firing its effect",[&]{auto s=arena();auto slug=craft(r,s,"SH001"),spread=craft(r,s,"SH110"),shield=craft(r,s,"MA003");Action load=Action::load({slug,spread});load.sacrifices={shield};act(r,s,load);expect(part(s,shield).place==Place::Payment,"Shield not reserved");roundtrip(s);Action unload;unload.type=ActionType::Unload;act(r,s,unload);expect(part(s,shield).place==Place::Reserve&&!part(s,shield).everInstalled,"unload consumed or used reserved Shield");equal(s.heat,0,"sacrifice reservation fired first-install Heat");});
run("variable first-install Heat payment remains paid after save and reinstall",[&]{auto s=arena();s.heat=8;auto p=craft(r,s,"MA096");Action a=Action::install(p);a.amount=9;rejected(r,s,a);a.amount=3;act(r,s,a);equal(s.heat,5,"chosen3 cost");equal(Rules::shield(s),15,"6+3x3Shield");act(r,s,Action::remove(p));roundtrip(s);install(r,s,p);equal(s.heat,5,"reinstall charged again");equal(part(s,p).paidHeat,3,"recorded payment");});
run("own HP cost cannot borrow later shield/refund and failed Use is atomic",[&]{auto s=arena();s.hp=6;auto a=Action::craft(memory(s,"MA116"));rejected(r,s,a);s.hp=7;act(r,s,a);equal(s.hp,1,"full6HP payment");equal(Rules::shield(s),24,"postpayment grant");});
run("MA093 and MA101 count paid part activations but exclude Utility Use",[&]{auto s=arena();s.heat=10;use(r,s,"MA093");use(r,s,"MA101");use(r,s,"MA035");use(r,s,"MA019");equal(Rules::shield(s),0,"direct Utility HP cost must not trigger Rivets");const auto iron=s.materials[0];next(r,s);equal(s.materials[0]-iron,5,"Utility Heat cost must not trigger Ledger");});
run("lethal support recoil stops later burn-reduction payload",[&]{auto s=arena();s.hp=2;s.enemies[0].burn=6;auto other=s.enemies[0];other.id=s.nextId++;other.burn=0;other.mesh=4;s.enemies.push_back(other);auto p=craft(r,s,"SH087");Action a;a.partTargets={{p,other.id}};fire(r,s,{p},s.enemies[0].id,a);expect(s.phase==Phase::Defeat,"support recoil should kill");equal(s.enemies[0].burn,6,"later Burn consumption must stop at final death");});
run("SH043 bypass redirects actual post-Armor shot damage",[&]{auto s=arena();s.enemies[0].armor=3;s.enemies[0].shield=20;activate(r,s,craft(r,s,"SH043"));fire(r,s,{grant(r,s,"SH001")});equal(s.enemies[0].hp,9997,"6-3 damage bypasses only3");equal(s.enemies[0].shield,20,"bypass did not add12");});
run("MA042 prehit Burn consumption and MA091 kill transfer follow placement order",[&]{auto s=arena();s.enemies[0].hp=1;s.enemies[0].burn=10;auto other=s.enemies[0];other.id=s.nextId++;other.hp=other.maxHp=1000;other.burn=0;s.enemies.push_back(other);auto consume=craft(r,s,"MA042"),transfer=craft(r,s,"MA091");Action a;a.partTargets={{transfer,other.id}};fire(r,s,{consume,transfer},s.enemies[0].id,a);equal(s.enemies[1].burn,4,"transfer records Burn after6 prehit spend");});
run("Split Chassis death-spawn has a new target and cannot attack in creation round",[&]{auto s=formation("C1-F-CHASSIS");const auto carrier=s.enemies[0].id;s.enemies[0].hp=1;fire(r,s,{grant(r,s,"SH089")},carrier);expect(s.phase==Phase::Preparation&&s.enemies.size()==2,"deathspawn missing or premature victory");const auto mite=s.enemies[1].id;equal(s.enemies[1].hp,7,"support hit retargeted to spawn");const auto before=s.hp;next(r,s);equal(s.hp,before,"spawn attacked during creation round");next(r,s);equal(s.hp,before-5,"spawn did not act in next enemy phase");expect(s.enemies[1].id==mite,"spawn identity changed");});
run("Nest committed Attack stays Attack after player kills the live Mite",[&]{auto s=formation("C1-F-NEST");next(r,s);next(r,s);expect(s.round==3&&s.enemies[0].intent.move==Move::Attack,"expected committed slot-full Attack");auto it=std::find_if(s.enemies.begin(),s.enemies.end(),[](const Enemy&e){return e.definition=="C1-R01"&&!e.dead;});expect(it!=s.enemies.end(),"missing Mite");auto mite=it->id;fire(r,s,{grant(r,s,"SH004")},mite);const auto supplies=s.enemies[0].summonsRemaining;const auto hp=s.hp;next(r,s);equal(s.hp,hp-6,"committed Attack replaced after slot freed");equal(s.enemies[0].summonsRemaining,supplies,"surprise deployment spent supply");});
run("boss preaction Corrosion threshold cancels pending attack and stops phase-one scaling",[&]{auto s=formation("C1-F-GATEBREAKER");s.enemies[0].hp=47;s.enemies[0].drive=5;s.enemies[0].corrosion=1;next(r,s);equal(s.hp,80,"threshold should cancel14+5 attack");expect(s.enemies[0].bossTransitioned&&!s.enemies[0].recoveryPending,"Recover not consumed once");equal(s.enemies[0].drive,0,"old Drive or phase-one scaling retained");expect(s.enemies[0].robotAction=="quad_strike","phase2 starts next round");});
run("boss postaction Burn threshold schedules next-round Recover",[&]{auto s=formation("C1-F-GATEBREAKER");s.enemies[0].hp=47;s.enemies[0].drive=2;s.enemies[0].burn=1;next(r,s);equal(s.hp,64,"already-performed16 attack must stand");expect(s.enemies[0].robotAction=="recover"&&s.enemies[0].recoveryPending,"next unperformed action is Recover");next(r,s);equal(s.hp,64,"Recover attacked");expect(s.enemies[0].robotAction=="quad_strike","Recover repeated or phase2 skipped");});
run("Fouling consumes only Ammo recipe uses and expires at affected EndTurn",[&]{auto s=arena();s.recipeFouling=2;s.foulingRound=1;auto copper=s.materials[1];use(r,s,"MA001");craft(r,s,"SH002");equal(s.recipeFouling,2,"Utility/Shield consumed Fouling");const auto iron=s.materials[0];craft(r,s,"SH003");equal(s.materials[0],iron-1,"Ammo without ordinaryIron did not pay surcharge");equal(s.recipeFouling,1,"Ammo Use count");next(r,s);equal(s.recipeFouling,0,"unused Fouling did not expire");expect(s.materials[1]>=copper,"unexpected unrelated debit");});
run("Shield Leak drains installed parts but preserves direct upgrade protection",[&]{auto s=arena(10,1);plain(r,s,Kind::Shield,4,true);s.protection.push_back({s.nextId++,s.nextOrder++,10});s.shieldLeak=6;s.shieldLeakRound=1;auto out=act(r,s,Action::endTurn());auto leak=std::find_if(out.events.begin(),out.events.end(),[](const Event&e){return e.type=="shield_leak";});expect(leak!=out.events.end(),"Leak event absent");equal(leak->amount,4,"Leak included active upgrade balance");equal(s.hp,80,"upgrade protection should absorb10");});
run("all six manual-grab enhancements honor auto/miss/Perfect outcome scopes",[&]{
    for(const auto*id:{"SH121","SH122","SH123","SH124","SH125","SH126"})for(Amount result:{-1,0,2}){
        auto s=arena();Action choice;choice.choices=std::string(id)=="SH122"?std::vector<Amount>{2,3}:std::vector<Amount>{2};auto p=craft(r,s,id,choice);activate(r,s,p);act(r,s,Action::endTurn());s.materials={};act(r,s,Action::collect(0,result));
        const bool perfect=result==2;Amount extra=1;if(std::string(id)=="SH121")extra=perfect?3:1;if(std::string(id)=="SH122")extra=perfect?4:1;if(std::string(id)=="SH123"||std::string(id)=="SH124")extra=perfect?3:1;if(std::string(id)=="SH125")extra=perfect?7:2;
        equal(sum(s.materials),10+(perfect?2:0)+extra,std::string(id)+" material total");equal(static_cast<Amount>(s.parts.size()),std::string(id)=="SH126"&&perfect?2:0,std::string(id)+" generated part count");
    }
});
run("finite pile requests clamp each named Perfect bonus separately",[&]{auto s=arena();auto p=craft(r,s,"SH125");activate(r,s,p);act(r,s,Action::endTurn());s.materials={};s.finitePile=true;s.pile={7,3,1,2,1};act(r,s,Action::collect(0,2));expect(s.materials==Materials({7,3,1,2,1}),"finite bonus stole baseline, created missing stock, or missed available named stock");expect(s.pile==Materials{},"available pile not consumed consistently");});
run("same named amplifier refreshes and doubles only unmodified Precision bundle",[&]{auto s=arena();for(int i=0;i<2;++i)activate(r,s,craft(r,s,"SH124"));Action a;a.choices={2};activate(r,s,craft(r,s,"SH121",a));act(r,s,Action::endTurn());s.materials={};act(r,s,Action::collect(0,2));expect(s.materials==Materials({9,3,4,1,1}),"amplifier duplicated a bonus or stacked copies");});
run("runtime rarity agrees with Common and suffixed manual-grab source headings",[&]{expect(r.recipe("SH026")->rarity==Rarity::Common,"SH026 Common");for(const auto*id:{"SH121","SH122","SH123"})expect(r.recipe(id)->rarity==Rarity::Rare,std::string(id)+" Rare");for(const auto*id:{"SH124","SH125","SH126"})expect(r.recipe(id)->rarity==Rarity::Legendary,std::string(id)+" Legendary");auto s=arena();auto p=craft(r,s,"SH026");expect(part(s,p).rarity==Rarity::Common,"generated grant lost creator rarity");});
run("MA102 highest remembered Heat only includes installed source parts",[&]{auto s=arena();s.heat=8;auto high=craft(r,s,"MA102");install(r,s,high);s.heat=3;install(r,s,craft(r,s,"MA102"));act(r,s,Action::remove(high));s.heat=0;roundtrip(s);next(r,s);equal(s.heat,3,"removed higher snapshot must not override installed3");});
run("MA086 halves once after flat reduction with two physical source parts",[&]{auto s=arena(60,1);activate(r,s,craft(r,s,"SH024"));Action a;a.target=s.enemies[0].id;install(r,s,craft(r,s,"MA086"),a);install(r,s,craft(r,s,"MA086"),a);roundtrip(s);next(r,s);equal(s.hp,77,"(60-6)/2-24Shield is3HP damage");});
run("MA059 independent physical parts each supply one first-attack reduction",[&]{auto s=arena(40,1);install(r,s,craft(r,s,"MA059"));install(r,s,craft(r,s,"MA059"));next(r,s);equal(s.hp,64,"40-10flat-14Shield=16");});
run("MA066 refreshes one delayed bonus and first installation does not repeat it",[&]{auto s=arena();auto p=craft(r,s,"MA014");Action a;a.parts={p};use(r,s,"MA066",a);use(r,s,"MA066",a);next(r,s);install(r,s,p);equal(s.heat,6,"printed2Heat plus one4Heat attachment");act(r,s,Action::remove(p));roundtrip(s);install(r,s,p);equal(s.heat,6,"reinstallation repeated delayed bonus");});
run("MA079 distinguishes prior part payments and later Utility costs",[&]{auto s=arena();s.heat=8;activate(r,s,craft(r,s,"MA010"));install(r,s,craft(r,s,"MA079"));use(r,s,"MA035");next(r,s);equal(s.heat,3,"8-3part-2Utility-2decay+2reward");auto t=arena();t.heat=8;install(r,t,craft(r,t,"MA079"));activate(r,t,craft(r,t,"MA010"));next(r,t);equal(t.heat,3,"later3part payment suppresses2 reward");});
run("MA048 optional payment occurs at EndTurn and all choices validate atomically",[&]{auto s=arena();s.heat=3;auto a=craft(r,s,"MA048"),b=craft(r,s,"MA048");install(r,s,a);install(r,s,b);equal(s.heat,3,"installation prematurely pays optional cost");auto end=Action::endTurn();end.partChoices={{a,2}};rejected(r,s,end);end.partChoices={{a,3},{b,3}};rejected(r,s,end);end.partChoices={{a,3},{b,0}};act(r,s,end);equal(s.heat,0,"one3Heat payment");equal(Rules::shield(s),16,"paid12 plus declined4 next-round grants");});
run("MA115 physical copies share24 restoration across whole attacks",[&]{auto s=arena(5,4);for(int i=0;i<2;++i){auto e=s.enemies[0];e.id=s.nextId++;s.enemies.push_back(e);}install(r,s,craft(r,s,"MA115"));install(r,s,craft(r,s,"MA115"));s.retentionAllowances={100};next(r,s);equal(s.hp,80,"restoration protects later attacks");equal(Rules::shield(s),12,"48initial+24sharedrestore-60damage");});
run("MA060 refresh holds two Burn decays and snapshots preserve the clock",[&]{auto s=arena();fire(r,s,{grant(r,s,"MA060")});next(r,s);equal(s.enemies[0].burn,3,"first tick hold");roundtrip(s);next(r,s);equal(s.enemies[0].burn,3,"second tick hold");next(r,s);equal(s.enemies[0].burn,2,"third tick must decay");});
run("MA120 echo uses original predefence shot value and current Shield once",[&]{auto s=arena();s.enemies[0].mark=5;s.enemies[0].armor=2;s.enemies[0].shield=8;fire(r,s,{grant(r,s,"MA120"),grant(r,s,"SH001")});equal(s.enemies[0].hp,9981,"24shot+5Mark-2Armor-8Shield");s.enemies[0].shield=9;roundtrip(s);next(r,s);equal(s.enemies[0].hp,9980,"12echo-2Armor-9currentShield");next(r,s);equal(s.enemies[0].hp,9980,"echo duplicated itself");});
run("SH115 refresh replaces scheduled duration without stacking old deliveries",[&]{auto s=arena();use(r,s,"SH115");use(r,s,"SH115");next(r,s);equal(Rules::shield(s),18,"duplicate next-round grants");use(r,s,"SH115");for(int i=0;i<3;++i){roundtrip(s);next(r,s);equal(Rules::shield(s),18,"one18 per refreshed turn");}next(r,s);equal(Rules::shield(s),0,"refreshed duration never expired");});
run("SH101 optional zero sacrifice and duplicate reservation validate atomically",[&]{auto s=arena();use(r,s,"SH101");expect(s.deliveries.empty(),"zero sacrifices invented delivery");auto p=grant(r,s,"SH001");Action a=Action::craft(memory(s,"SH101"));a.parts={p,p};a.choices={0,1};rejected(r,s,a);a.parts={p};a.choices={4};rejected(r,s,a);a.choices={3};act(r,s,a);const auto glass=s.materials[3];next(r,s);equal(s.materials[3]-glass,3,"onebaselineGlass plus scheduled2");});
run("SH070 discounts the first eligible next-round Utility Use only",[&]{auto s=arena();activate(r,s,craft(r,s,"SH070"));auto iron=s.materials[0];use(r,s,"SH104");equal(s.materials[0],iron-2,"saver triggered in activation round");next(r,s);iron=s.materials[0];use(r,s,"SH104");equal(s.materials[0],iron-1,"eligible Utility did not receive discount");use(r,s,"SH104");equal(s.materials[0],iron-3,"second Use received extra discount");});
run("preview and canonical snapshot reproduce complex Fire without mutation",[&]{auto s=arena();s.heat=7;auto e=s.enemies[0];e.id=s.nextId++;e.armor=2;e.mesh=2;s.enemies.push_back(e);auto ammo=grant(r,s,"MA091"),spread=grant(r,s,"MA041");s.enemies[0].hp=1;s.enemies[0].burn=6;act(r,s,Action::load({ammo,spread}));auto a=Action::fire(s.enemies[0].id);a.partTargets={{ammo,e.id},{spread,e.id}};const auto original=serialize(s);auto first=r.preview(s,a),second=r.preview(s,a);expect(first.result.ok&&second.result.ok,"preview failure");expect(serialize(s)==original,"preview mutated source");expect(serialize(first.state)==serialize(second.state),"preview state varies");std::string firstEvents,secondEvents;for(const auto&x:first.result.events)firstEvents+=eventJson(x);for(const auto&x:second.result.events)secondEvents+=eventJson(x);expect(firstEvents==secondEvents,"preview events vary");roundtrip(s);auto actual=act(r,s,a);std::string actualEvents;for(const auto&x:actual.events)actualEvents+=eventJson(x);expect(serialize(s)==serialize(first.state)&&actualEvents==firstEvents,"saved execution differs from preview");});
run("MA093 counts two paid physical spread parts despite named spread refresh",[&]{auto s=arena();s.heat=8;auto e=s.enemies[0];e.id=s.nextId++;s.enemies.push_back(e);use(r,s,"MA093");auto a=grant(r,s,"MA041"),b=grant(r,s,"MA041");Action choice;choice.partTargets={{a,e.id},{b,e.id}};fire(r,s,{grant(r,s,"SH001"),a,b},s.enemies[0].id,choice);equal(s.heat,0,"both physical4Heat costs paid");equal(s.enemies[1].hp,9997,"same named50percent spread happened more than once");const auto iron=s.materials[0];roundtrip(s);next(r,s);equal(s.materials[0]-iron,7,"5haulIron plus two1Iron part-activation rewards");});
run("combined Fire costs cannot borrow a later spread kill Heat refund",[&]{auto s=arena();s.heat=10;auto e=s.enemies[0];e.id=s.nextId++;e.hp=1;s.enemies.push_back(e);auto a=grant(r,s,"MA111"),b=grant(r,s,"MA041");act(r,s,Action::load({grant(r,s,"SH001"),a,b}));auto choice=Action::fire(s.enemies[0].id);choice.partTargets={{b,e.id}};rejected(r,s,choice);equal(s.heat,10,"combined11Heat cost rejection must be atomic");});
run("SH085 spends the chosen amount while preserving remaining protection",[&]{auto s=arena();auto first=plain(r,s,Kind::Shield,6,true),second=plain(r,s,Kind::Shield,4,true);auto p=craft(r,s,"SH085");Action a;a.type=ActionType::Activate;a.subject=p;for(Amount invalid:{-1,11,16}){a.amount=invalid;rejected(r,s,a);}a.amount=4;act(r,s,a);equal(part(s,first).shield,2,"chosen4 must drain oldest6 first");equal(part(s,second).shield,4,"unspent later4Shield must remain");fire(r,s,{grant(r,s,"SH001")});equal(s.enemies[0].hp,9986,"6shot+8chosen-payment bonus");auto t=arena();plain(r,t,Kind::Shield,6,true);activate(r,t,craft(r,t,"SH085"));equal(Rules::shield(t),6,"declined zero payment spent Shield");fire(r,t,{grant(r,t,"SH001")});equal(t.enemies[0].hp,9994,"zero payment invented bonus");});
std::cout<<"Expanded independent groups: "<<passed<<" passed, "<<failed<<" failed.\n";return failed?1:0;}
