void ammoCases(){
add("SH009","three OTHER Ammo threshold excludes physical Spread",[]{for(int others:{0,2,3,4}){auto s=arena();std::vector<Id> bullet{make(s,"SH009")};for(int i=0;i<others;++i)bullet.push_back(make(s,"SH001"));const auto spread=make(s,"SH051");bullet.push_back(spread);check(firedAmount(fire(s,bullet))==8+6*others+(others>=3?2:0),"Rivet threshold");}});
add("SH018","per OTHER Ammo scaling caps at six and ignores Spread",[]{for(int others:{0,1,5,6,7}){auto s=arena();std::vector<Id> bullet{make(s,"SH018")};for(int i=0;i<others;++i)bullet.push_back(make(s,"SH001"));bullet.push_back(make(s,"SH051"));check(firedAmount(fire(s,bullet))==6*others+std::min(12,others*2),"Thread scaling/cap");}});
add("SH014","Corrosion follows main hit and excludes extra targets",[]{auto s=arena();s.enemies[0].shield=4;const auto p=make(s,"SH014");fire(s,{p});check(s.enemies[0].hp==10000&&s.enemies[0].shield==2&&s.enemies[0].corrosion==2,"Shielded hit then Corrosion2");check(s.enemies[1].corrosion==0,"Main-only payload");const auto result=end(s);check(s.enemies[0].hp==9998&&s.enemies[0].corrosion==1,"Next pre-action corrosion tick");check(events(result,"enemy_action")==3,"Status does not replace action");});
add("SH016","Weaken4 after main hit only with ordinary decay",[]{auto s=arena();const auto p=make(s,"SH016");fire(s,{p});check(s.enemies[0].hp==9995&&s.enemies[0].weaken==4&&s.enemies[1].weaken==0,"Payload and recipient");attack(s,0,7);end(s);check(s.hp==997&&s.enemies[0].weaken==3,"Next attack reduced4 then decay1");});
add("SH041","remove floored half Shield BEFORE the added8 hit",[]{for(Amount value:{0,1,15,16,17,40}){auto s=arena();s.enemies[0].shield=value;const auto result=fire(s,{make(s,"SH041")});const auto remaining=value-value/2;check(s.enemies[0].shield==std::max(0,remaining-8)&&s.enemies[0].hp==10000-std::max(0,8-remaining),"Half removal and damage order");check(eventAmount(result,"shield_removed")==value/2,"Floor half");}});
add("SH042","main kill gates one chosen support hit and validates target",[]{for(bool kill:{false,true}){auto s=arena();s.enemies[0].hp=kill?8:9;const auto p=make(s,"SH042");act(s,Action::load({p}));auto a=Action::fire(s.enemies[0].id);reject(s,a);a.partTargets={{p,s.enemies[0].id}};reject(s,a);a.partTargets={{p,s.enemies[1].id}};act(s,a);check(s.enemies[0].dead==kill&&s.enemies[1].hp==(kill?9990:10000)&&s.enemies[2].hp==10000,"Only chosen extra on main kill");}auto s=arena(1);s.enemies[0].hp=8;fire(s,{make(s,"SH042")});check(s.phase==Phase::Victory,"No extra target required when none lives");});
add("SH044","three currently installed physical Shields count without payment",[]{for(int count:{0,2,3,4}){auto s=arena();std::vector<Id> shields;for(int i=0;i<count;++i){const auto p=make(s,"SH002");install(s,p);shields.push_back(p);}const auto base=Rules::shield(s);check(firedAmount(fire(s,{make(s,"SH044")}))==(count>=3?13:8),"Installed count");check(Rules::shield(s)==base,"Count is not Shield payment");if(count>=3){remove(s,shields.back());check(firedAmount(fire(s,{make(s,"SH044")}))==(count-1>=3?13:8),"Removed history not counted");}}});
add("SH045","post-main Shield2 per consumed Ammo capped12 excludes Spread",[]{for(int count:{1,5,6,7}){auto s=arena();std::vector<Id> ids{make(s,"SH045")};for(int i=1;i<count;++i)ids.push_back(make(s,"SH001"));ids.push_back(make(s,"SH051"));const auto result=fire(s,ids);check(firedAmount(result)==5+6*(count-1),"Ammo direct contribution");check(Rules::shield(s)==std::min(12,count*2),"Shield count/cap");const auto out=outputs(s,"SH045");check(out.size()==1&&part(s,out[0]).place==Place::Installed,"Fresh installed reward");remove(s,out[0]);next(s);install(s,out[0]);check(Rules::shield(s)==std::min(12,count*2),"Reward ordinary saved Shield");}});
add("SH046","Burn2 every other living enemy after main hit",[]{auto s=arena(4);s.enemies[3].escaped=true;fire(s,{make(s,"SH046")});check(s.enemies[0].hp==9993&&s.enemies[0].burn==0,"Main direct only");check(s.enemies[1].burn==2&&s.enemies[2].burn==2&&s.enemies[3].burn==0,"Other living recipients");});
add("SH047","Corrosion2 all living including surviving main excludes killed main",[]{for(bool kill:{false,true}){auto s=arena();s.enemies[0].hp=kill?5:6;fire(s,{make(s,"SH047")});check(s.enemies[0].corrosion==(kill?0:2)&&s.enemies[1].corrosion==2&&s.enemies[2].corrosion==2,"Living after main hit");}});
add("SH048","Weaken4 all currently attacking recipients only",[]{auto s=arena();attack(s,0,9);attack(s,1,9);fire(s,{make(s,"SH048")});check(s.enemies[0].hp==9992&&s.enemies[0].weaken==4&&s.enemies[1].weaken==4&&s.enemies[2].weaken==0,"Attack eligibility and direct damage");end(s);check(s.hp==990,"Both later attacks reduced");});
add("SH052","earlier-round reserve grants8 once physical age is earned",[]{for(int age:{0,1,3}){auto s=arena();const auto p=make(s,"SH052");for(int i=0;i<age;++i)next(s);snapshot(s);check(firedAmount(fire(s,{p}))==(age?15:7),"Saved copy age threshold");}});
add("SH053","Fire-start empty raw pool only; any one resource disqualifies",[]{for(int resource=-1;resource<5;++resource){auto s=arena();const auto p=make(s,"SH053");s.materials={};if(resource>=0)s.materials[static_cast<std::size_t>(resource)]=1;check(firedAmount(fire(s,{p}))==(resource<0?17:5),"Empty-pool snapshot");}});
add("SH054","actual same-round sacrifices add3 capped9 and reset",[]{for(int count:{0,1,3,4}){auto s=arena();for(int i=0;i<count;++i){Action a;a.parts={make(s,"SH001")};use(s,"SH032",a);}check(firedAmount(fire(s,{make(s,"SH054")}))==8+std::min(9,count*3),"Actual sacrifice count/cap");next(s);check(firedAmount(fire(s,{make(s,"SH054")}))==8,"Round count expires");}});
add("SH055","no previous HP loss grants8; Shield loss does not disqualify",[]{for(int mode:{0,1,2}){auto s=arena();if(mode){s.enemies[0].shield=mode==1?7:0;fire(s,{make(s,"SH001")});s.enemies[0].shield=0;}const auto result=fire(s,{make(s,"SH055")});check(firedAmount(result)==(mode==2?4:8)&&s.enemies[0].weaken==3,"HP history and after-hit Weaken3");}});
add("SH056","next-start8 same target once, lost when killed or fight ends",[]{for(bool dead:{false,true}){auto s=arena();const auto p=make(s,"SH056");fire(s,{p});check(s.enemies[0].hp==9993&&s.deliveries.size()==1,"Initial7 schedules8");if(dead){s.enemies[0].hp=6;fire(s,{make(s,"SH001")});}const auto before=s.enemies[0].hp;end(s);check(s.enemies[0].hp==(dead?0:before-8)&&s.enemies[1].hp==10000,"Same target no retarget");collect(s);end(s);check(s.enemies[0].hp==(dead?0:before-8),"Delivery once");}auto s=arena(1);s.enemies[0].hp=7;fire(s,{make(s,"SH056")});check(s.phase==Phase::Victory,"Fight end cancels reachable delivery");reject(s,Action::endTurn());});
add("SH075","main-kill Copper2 next start once; no direct cores or credits",[]{for(bool killed:{false,true}){auto s=arena();s.enemies[0].hp=killed?8:9;const auto before=s.credits;const auto p=make(s,"SH075");const auto copper=s.materials[1];const auto result=fire(s,{p});check(s.materials[1]==copper&&s.credits==before&&events(result,"core_dropped")==0,"No immediate currency grant");end(s);check(s.materials[1]==copper+(killed?2:0),"Conditional future Copper");}});
add("SH081","all main Shield removed before14 without affecting others",[]{for(Amount amount:{0,1,101}){auto s=arena();s.enemies[0].shield=amount;s.enemies[1].shield=20;fire(s,{make(s,"SH081")});check(s.enemies[0].shield==0&&s.enemies[0].hp==9986&&s.enemies[1].shield==20,"Complete main removal");}});
add("SH084","distinct printed crafting types across Ammo only capped27",[]{for(int mode:{0,1,2}){auto s=arena();std::vector<Id> bullet{make(s,"SH084")};Amount expected=21;if(mode>=1){bullet.push_back(make(s,"SH014"));expected=24+2;}if(mode>=2){bullet.push_back(make(s,"SH109"));expected=27+2+36;}bullet.push_back(make(s,"SH082"));check(firedAmount(fire(s,bullet))==expected,"Union of Ammo crafting material types");}auto s=arena();std::vector<Id> ids{make(s,"SH084"),make(s,"SH084")};check(firedAmount(fire(s,ids))==42,"Repeated materials counted once for each core");});
add("SH086","zero Shield at Fire start gates Corrosion6 after main hit",[]{for(Amount shield:{0,1,16,17}){auto s=arena();s.enemies[0].shield=shield;fire(s,{make(s,"SH086")});check(s.enemies[0].corrosion==(shield==0?6:0),"Pre-Fire Shield eligibility");check(s.enemies[0].hp==10000-std::max(0,16-shield),"Added16");}auto s=arena();s.enemies[0].shield=5;fire(s,{make(s,"SH081"),make(s,"SH086")});check(s.enemies[0].corrosion==0,"Earlier removal in same bullet does not rewrite Fire-start condition");});
add("SH087","one chosen Burn-sized support then floored half removal; recoil stops",[]{for(Amount burn:{0,5,6}){auto s=arena();s.enemies[0].burn=burn;const auto p=make(s,"SH087");Action a;a.partTargets={{p,s.enemies[1].id}};fire(s,{p},0,a);check(s.enemies[0].hp==9986&&s.enemies[1].hp==10000-burn&&s.enemies[0].burn==burn-burn/2&&s.enemies[2].hp==10000,"Burn copy and floor consumption");}auto s=arena();s.hp=2;s.enemies[0].burn=6;s.enemies[1].mesh=4;const auto p=make(s,"SH087");Action a;a.partTargets={{p,s.enemies[1].id}};fire(s,{p},0,a);check(s.phase==Phase::Defeat&&s.enemies[0].burn==6,"Final recoil stops later half-Burn operation");});
add("SH088","Fire-start distinct four statuses each add5 including spent Mark",[]{for(int mask=0;mask<16;++mask){auto s=arena();auto& e=s.enemies[0];e.burn=(mask&1)?1:0;e.corrosion=(mask&2)?3:0;e.mark=(mask&4)?2:0;e.weaken=(mask&8)?4:0;const int count=((mask&1)?1:0)+((mask&2)?1:0)+((mask&4)?1:0)+((mask&8)?1:0);const auto r=fire(s,{make(s,"SH088")});check(firedAmount(r)==10+5*count&&s.enemies[0].hp==10000-10-5*count-((mask&4)?2:0),"Distinct status rather than stacks");}auto s=arena();fire(s,{make(s,"SH014"),make(s,"SH088")});check(s.enemies[0].hp==9988,"Same-shot later Corrosion excluded");});
add("SH089","separate12 support only on surviving main; defence twice no payload repeat",[]{auto s=arena();s.enemies[0].armor=3;fire(s,{make(s,"SH089"),make(s,"SH014")});check(s.enemies[0].hp==9980&&s.enemies[0].corrosion==2,"14 minus3 then12 minus3; payload once");s=arena();s.enemies[0].hp=12;const auto r=fire(s,{make(s,"SH089")});check(s.enemies[0].dead&&events(r,"hit")==1,"Dead main receives no second hit");});
add("SH090","full reserve rounds add8 per round capped24 per physical part",[]{for(int age:{0,1,2,3,4}){auto s=arena();const auto p=make(s,"SH090");for(int i=0;i<age;++i)next(s);const auto fresh=make(s,"SH090");check(firedAmount(fire(s,{p}))==10+8*std::min(3,age),"Age scaling cap");check(firedAmount(fire(s,{fresh}))==10,"Fresh identity independent age");}});
add("SH109","post-hit strips up to12 Shield each other living enemy",[]{auto s=arena(4);s.enemies[0].shield=50;s.enemies[1].shield=5;s.enemies[2].shield=20;s.enemies[3].shield=30;s.enemies[3].escaped=true;fire(s,{make(s,"SH109")});check(s.enemies[0].shield==14&&s.enemies[0].hp==10000,"Main36 no strip");check(s.enemies[1].shield==0&&s.enemies[2].shield==8&&s.enemies[3].shield==30,"Other living cap12");});
add("SH112","main kill gates20 each other enemy once without recursive propagation",[]{for(bool kill:{false,true}){auto s=arena();s.enemies[0].hp=kill?24:25;s.enemies[1].hp=20;fire(s,{make(s,"SH112")});check(s.enemies[1].hp==(kill?0:20)&&s.enemies[2].hp==(kill?9980:10000),"Single nonrecursive wave");}});
}
