void boundaryCases(){
add("SH092.boundaries","saved source no rearm, fatal enemy phase and Campaign completion cleanup",[]{
    for(const auto& recipe:{"SH092","SH113"}){
        auto s=arena();const auto p=make(s,recipe);install(s,p);remove(s,p);install(s,p);remove(s,p);check(s.deliveries.size()==1,"Repeated same-round movement never duplicates schedule");end(s);check(Rules::shield(s)==(std::string(recipe)=="SH092"?15:20),"First promised delivery");collect(s);install(s,p);remove(s,p);snapshot(s);end(s);check(Rules::shield(s)==0&&s.deliveries.empty(),"Next-round reinstall never rearms");
        s=arena();const auto fatal=make(s,recipe);install(s,fatal);remove(s,fatal);s.hp=1;attack(s,0,1);const auto r=end(s);check(s.phase==Phase::Defeat&&outputs(s,recipe).size()==1&&events(r,"delivery")==0,"Final death interrupts due delivery");
        s=arena();const auto detached=make(s,recipe);install(s,detached);remove(s,detached);attack(s,0,2);end(s);check(s.enemies[0].mark==0,"Detached source has no reactive Mark");
        CampaignRules campaignRules(rules,cinderwallUpgradeHooks(rules));auto c=campaignRules.newGame(17,"shared-schedule-contract");c.mayorOffers={"MY1-01","MY1-02","MY1-03"};
        const auto run=[&](CampaignAction a){a.runId=c.runId;a.sequence=c.nextTransaction;const auto result=campaignRules.apply(c,a);check(result.ok,result.reason);return result;};
        CampaignAction mayor;mayor.type=CampaignActionType::ChooseMayor;mayor.choice="MY1-02";run(mayor);
        CampaignAction enter;enter.type=CampaignActionType::EnterOffer;for(const auto& o:routeOffers(c.route))if(o.kind==EncounterKind::Regular){enter.subject=o.id;break;}check(enter.subject!=0,"Actual regular offer");run(enter);
        const auto combat=[&](const Action& action){CampaignAction a;a.type=CampaignActionType::Combat;a.combat=action;return run(a);};combat(Action::collect(0));c.fight.materials={100,100,100,100,100};c.fight.hotBarrel=false;
        const auto stored=memory(c.fight,recipe);const auto first=c.fight.nextId;combat(Action::craft(stored));const auto source=created(c.fight,first)[0];combat(Action::install(source));combat(Action::remove(source));check(c.fight.deliveries.size()==1,"Real campaign has committed delayed delivery");
        for(auto& e:c.fight.enemies){e.hp=6;e.armor=e.shield=e.tiles=e.mesh=0;}
        while(c.phase==CityPhase::Fight){Id target=0;for(const auto& e:c.fight.enemies)if(!e.dead&&!e.escaped){target=e.id;break;}const auto ammoCopy=memory(c.fight,"SH001");const auto before=c.fight.nextId;combat(Action::craft(ammoCopy));const auto ammo=created(c.fight,before)[0];combat(Action::load({ammo}));combat(Action::fire(target));}
        check(c.phase==CityPhase::Rewards&&c.fight.parts.empty()&&c.fight.deliveries.empty()&&c.fight.materials==Materials{},"Production Campaign fight boundary clears pending parts/materials/deliveries");
    }
});
add("SH113.boundaries","pre-reset10 condition uses current balance and installed source; delivery cooling is live",[]{
    for(int mode:{0,1,2,3,4}){auto s=arena();const auto cold=memory(s,"SH118");copy(s,cold).cooldown=3;copy(s,cold).usedRound=s.round;const auto wall=make(s,"SH113");if(mode==3)activate(s,make(s,"SH066"));install(s,wall);if(mode==0)Rules::spendShield(s,28,true);if(mode==1)Rules::spendShield(s,29,true);if(mode==2)remove(s,wall);if(mode>=3){Rules::spendShield(s,21,true);if(mode==4)activate(s,make(s,"SH066"));}end(s);check(Rules::shield(s)==20,"Promised Shield always arrives");check(copy(s,cold).cooldown==((mode==0||mode==4)?2:3),"Current pre-reset source presence and threshold");}
    auto s=arena();const auto first=memory(s,"SH052"),later=memory(s,"SH118");copy(s,first).cooldown=1;copy(s,first).usedRound=0;copy(s,later).cooldown=3;copy(s,later).usedRound=1;install(s,make(s,"SH113"));end(s);check(copy(s,first).cooldown==0&&copy(s,later).cooldown==2,"Delivery affects recipes currently cooling after ordinary tick, floor0");
});
add("SH035.boundaries","flat bonus not multiplied by dynamic Shield and copied Shield drops upgrades",[]{auto s=arena();activate(s,make(s,"SH035"));const auto p=make(s,"SH028");install(s,p);check(Rules::shield(s)==13,"Living3 times3 plus4 once");for(const auto& recipe:{"SH102","SH118"}){s=arena();check(rules.acquireUpgrade(s,"UGS-140").ok,"Real upgrade acquisition");const auto original=use(s,"SH026")[0];check(part(s,original).shield==8,"Original printed4 plus production4");remove(s,original);Action a;a.parts={original};use(s,recipe,a);end(s);const auto copies=outputs(s,recipe);check(copies.size()==2,"Two copies");collect(s);for(Id id:copies)install(s,id);check(Rules::shield(s)==14,"Normal next6 plus two printed4 copies");check(part(s,original).shield==8,"Original retains earned bonus");}});
add("SH064.boundaries","fouling/leak do not consume screen; current-round expiry retains no prevention",[]{auto s=arena(5);const auto setup=[&](std::size_t index,const std::string& definition,const std::string& action){auto& e=s.enemies[index];e.definition=definition;e.robotAction=action;e.intentRound=s.round;e.intent={Move::Support,0,0};};setup(0,"C1-R04","foul");setup(1,"C1-R08","double_punch");setup(2,"C1-O03","thermal_runaway");setup(3,"C1-O03","thermal_runaway");activate(s,make(s,"SH064"));end(s);check(s.recipeFouling==1&&s.shieldLeak==2&&s.burn==2,"Excluded statuses pass through, first Burn prevented, second applies");collect(s);s.burn=0;for(auto& e:s.enemies){e.definition="controlled";e.robotAction.clear();e.intent={Move::Recover,0,0};e.pattern={e.intent};}setup(0,"C1-O03","thermal_runaway");end(s);check(s.burn==2,"No next-round screen");});
add("SH103.boundaries","selected batch attachment survives storage and invalid choice is atomic",[]{auto s=arena();activate(s,make(s,"SH103"));Action a;a.type=ActionType::Craft;a.subject=memory(s,"MA038");a.amount=2;reject(s,a);a.amount=-1;reject(s,a);a.amount=1;const auto first=s.nextId;paid(s,a.subject,a);const auto ids=created(s,first);next(s);check(firedAmount(fire(s,{ids[1]}))==12&&firedAmount(fire(s,{ids[0]}))==4,"Stored chosen physical bonus persists to first use");});
add("SH072.boundaries","unused nextshot copy expires and copying excludes unattached or absent part choices",[]{auto s=arena();activate(s,make(s,"SH072"));next(s);fire(s,{make(s,"SH001")});end(s);check(outputs(s,"SH072").empty(),"Unspent capture expires");s=arena();activate(s,make(s,"SH072"));const auto source=make(s,"SH001"),other=make(s,"SH009");act(s,Action::load({source}));auto a=Action::fire(s.enemies[0].id);a.partChoices={{0,other}};reject(s,a);a.partChoices={{0,source},{0,source}};reject(s,a);});
add("SH122.boundaries","manual models share one attempt; finite extras and fitting order preserved",[]{
    for(const auto& recipe:{"SH122","SH123","SH126"}){auto s=arena();s.precisionSpent=true;Action choice;if(std::string(recipe)=="SH122")choice.choices={0,3};activate(s,make(s,recipe,choice));end(s);reject(s,Action::collect(0,2));const auto before=s.materials;collect(s);auto expected=ordinaryHaul;if(std::string(recipe)=="SH123")++expected[3];else ++expected[0];check(delta(s.materials,before)==expected,"Already-spent attempt leaves unconditional addition");}
    auto s=arena();Action choice;choice.choices={0,3};activate(s,make(s,"SH122",choice));activate(s,make(s,"SH122",choice));end(s);s.finitePile=true;s.pile={8,2,1,2,1};const auto before=s.materials;collect(s,2,0);check(delta(s.materials,before)==Materials{8,2,1,2,1},"Baseline5Iron +ordinaryPerfect2 leaves only1Iron bonus; secondGlass shortage1; same-name not doubled");
    s=arena();activate(s,make(s,"SH126"));activate(s,make(s,"SH126"));end(s);s.finitePile=true;s.pile={7,2,1,1,1};collect(s,2);check(outputs(s,"SH126").size()==2,"Part reward no pile cost even when no Iron extra remains; same-name once");
});
add("SH104.boundaries","full health consumes zero healing allowance; cooldown not bypassed by bonus",[]{auto s=arena();const auto full=memory(s,"SH104");paid(s,full);check(s.hp==1000&&s.carefulHealing==0,"Zero actual heal at fullHP");s.hp=970;use(s,"SH104");use(s,"SH104");check(s.hp==986&&s.carefulHealing==16,"Full16 remains after zero-heal Use");use(s,"SH104");check(s.hp==986,"Shared cap exhausted");});
add("SH093.boundaries","shown multi-hit damage includes Drive and Weaken, excludes nonattack and dead",[]{auto s=arena(4);attack(s,0,7,2);s.enemies[0].drive=3;s.enemies[0].weaken=4;attack(s,1,4,3);s.enemies[1].weaken=8;s.enemies[2].intent={Move::Charge,100,1};attack(s,3,100);s.enemies[3].dead=true;s.enemies[3].hp=0;install(s,make(s,"SH093"));check(Rules::shield(s)==6,"Half of two hits of6; negative second clamped0");});
add("SH043.boundaries","main bypass does not bypass Shield on physical spread hits",[]{auto s=arena();s.enemies[0].shield=s.enemies[1].shield=20;activate(s,make(s,"SH043"));const auto spread=make(s,"SH051");Action a;a.spreadTargets={{spread,s.enemies[1].id}};fire(s,{make(s,"SH009"),spread},0,a);check(s.enemies[0].hp==9992&&s.enemies[0].shield==20&&s.enemies[1].hp==10000&&s.enemies[1].shield==17,"8 redirected main;3 direct extra remains Shielded");});
add("SH110.boundaries","usedShield payment excluded and dead extra gets no Weaken",[]{auto s=arena();const auto shield=make(s,"SH063");install(s,shield);remove(s,shield);const auto spread=make(s,"SH110"),ammo=make(s,"SH014");auto a=Action::load({ammo,spread});a.sacrifices={shield};reject(s,a);const auto unused=make(s,"SH002");a.sacrifices={unused};act(s,a);s.enemies[1].hp=2;act(s,Action::fire(s.enemies[0].id));check(s.enemies[1].dead&&s.enemies[1].weaken==0&&s.enemies[2].weaken==3,"Weaken only surviving extra targets");});
add("SH119.boundaries","each chosen material's shortage independent; perfect Circuit request cannot steal baseline",[]{auto s=arena();Action a;a.choices={1,3};activate(s,make(s,"SH119",a));end(s);s.finitePile=true;s.pile={5,3,1,1,1};const auto before=s.materials;collect(s);check(delta(s.materials,before)==Materials{5,3,1,1,1},"Only one extraCopper available; no extraGlass");s=arena();activate(s,make(s,"SH123"));end(s);s.finitePile=true;s.pile={7,2,1,2,1};const auto original=s.materials;collect(s,2);check(delta(s.materials,original)==Materials{7,2,1,2,1},"OrdinaryCircuit survives missing two extraCircuit");});
}
