const Materials ordinaryHaul{5,2,1,1,1};
void magnetExpires(const std::string& recipe,Action choice={}){auto s=arena();const auto p=make(s,recipe,choice);const auto before=s.materials;end(s);collect(s);check(!exists(s,p)&&delta(s.materials,before)==ordinaryHaul,"Unfitted Magnet cannot be stored for later collection");}
void bonusCollection(const std::string& recipe,Materials extra,Action choice={}){
    for(bool finite:{false,true}){auto s=arena();activate(s,make(s,recipe,choice));check(s.round==1,"No immediate new collection");end(s);if(finite){s.finitePile=true;s.pile=ordinaryHaul;for(std::size_t i=0;i<5;++i)s.pile[i]+=extra[i];}snapshot(s);const auto before=s.materials;const auto pile=s.pile;collect(s);Materials expected=ordinaryHaul;for(std::size_t i=0;i<5;++i)expected[i]+=extra[i];check(delta(s.materials,before)==expected,"Exact normal plus source material extras");if(finite){check(total(s.pile)==0&&delta(pile,s.pile)==expected,"Only finite actual pile stock gathered");s.finitePile=false;}end(s);const auto second=s.materials;collect(s);check(delta(s.materials,second)==ordinaryHaul,"Temporary bonus expires after one haul");}
    auto s=arena();activate(s,make(s,recipe,choice));end(s);s.finitePile=true;s.pile=ordinaryHaul;const auto before=s.materials;collect(s);check(delta(s.materials,before)==ordinaryHaul&&total(s.pile)==0,"No missing bonus material takes away guaranteed baseline");magnetExpires(recipe,choice);
}
void collectionCases(){
for(const auto& item:std::vector<std::pair<std::string,Materials>>{{"SH037",{2,0,0,0,0}},{"SH038",{0,2,0,0,0}},{"SH039",{0,0,2,0,0}},{"SH040",{0,0,0,2,0}},{"SH077",{1,1,0,0,0}},{"SH078",{0,0,1,1,0}},{"SH079",{0,0,0,0,1}},{"SH107",{1,1,1,1,0}}}){const auto id=item.first;const auto extra=item.second;add(id,"specified next-haul extras only from available pile; normal haul and expiry",[=]{bonusCollection(id,extra);auto s=arena();activate(s,make(s,id));activate(s,make(s,id));end(s);const auto before=s.materials;collect(s);Materials expected=ordinaryHaul;for(std::size_t i=0;i<5;++i)expected[i]+=extra[i];check(delta(s.materials,before)==expected,"Same named gathering effect refreshes rather than stacks");});}
add("SH080","two chosen types take first3 normal slots, no haul-size increase, shortage fallback",[]{Action choice;choice.choices={2,3};for(bool available:{false,true}){auto s=arena();activate(s,make(s,"SH080",choice));end(s);s.finitePile=true;s.pile={100,100,available?100:0,available?100:0,100};const auto before=s.materials;collect(s);const auto got=delta(s.materials,before);check(total(got)==10,"Preference is not extra haul");if(available)check(got[0]==2&&got[2]+got[3]==5,"First3 otherwiseIron slots use chosen types");else check(got==Materials{7,2,0,0,1},"Unavailable types fall back normal");}for(const auto& values:std::vector<std::vector<Amount>>{{},{2},{2,2},{-1,2},{2,5}}){auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH080");a.choices=values;reject(s,a);}magnetExpires("SH080",choice);});
add("SH105","normal10 plus5 actual extras leave exactly2 gathered units back in pile",[]{auto s=arena();activate(s,make(s,"SH105"));end(s);s.finitePile=true;s.pile={50,50,50,50,50};const auto before=s.materials,pile=s.pile;auto a=Action::collect(0);reject(s,a);a.discarded={1,0,0,0,0};reject(s,a);a.discarded={0,0,0,0,20};reject(s,a);a.discarded={2,0,0,0,0};act(s,a);const auto got=delta(s.materials,before);check(total(got)==13&&delta(pile,s.pile)==got,"15 gathered minus2 returned, stock conserved");s=arena();activate(s,make(s,"SH105"));end(s);s.finitePile=true;s.pile={10,0,0,0,0};const auto start=s.materials;collect(s,-1,0,{2,0,0,0,0});check(delta(s.materials,start)==Materials{8,0,0,0,0}&&s.pile==Materials{2,0,0,0,0},"Pile may supply no extra but exactly2 actual gathered units returned");magnetExpires("SH105");});
add("SH106","chosen one of all5 types adds up-to4 after ordinary haul",[]{for(Amount material=0;material<5;++material){Action a;a.choices={material};Materials extra{};extra[static_cast<std::size_t>(material)]=4;bonusCollection("SH106",extra,a);auto s=arena();activate(s,make(s,"SH106",a));end(s);s.finitePile=true;s.pile=ordinaryHaul;s.pile[static_cast<std::size_t>(material)]+=2;const auto before=s.materials;collect(s);auto expected=ordinaryHaul;expected[static_cast<std::size_t>(material)]+=2;check(delta(s.materials,before)==expected,"Partial available2 of4");}for(const auto& values:std::vector<std::vector<Amount>>{{},{1,2},{5},{-1}}){auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH106");a.choices=values;reject(s,a);}});
add("SH108","four NORMAL slots prioritize chosen type with fallback then freshShield6",[]{for(Amount available:{0,2,20}){auto s=arena();Action choice;choice.choices={4};activate(s,make(s,"SH108",choice));end(s);s.finitePile=true;s.pile={100,100,100,100,available};const auto before=s.materials;collect(s);const auto expected=available==0?Materials{6,2,1,1,0}:available==2?Materials{4,2,1,1,2}:Materials{1,2,1,1,5};check(delta(s.materials,before)==expected&&Rules::shield(s)==6,"Four preference slots not four extra");const auto out=outputs(s,"SH108");check(out.size()==1&&part(s,out[0]).place==Place::Installed,"Fresh post-haul Shield");remove(s,out[0]);s.finitePile=false;next(s);install(s,out[0]);check(Rules::shield(s)==6,"Saveable regular Shield");}Action choice;choice.choices={4};magnetExpires("SH108",choice);auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH108");a.choices={5};reject(s,a);});
add("SH119","two DIFFERENT chosen types up-to3 each independently after normal haul",[]{for(Amount first=0;first<5;++first)for(Amount second=first+1;second<5;++second){Action a;a.choices={first,second};Materials extra{};extra[static_cast<std::size_t>(first)]=extra[static_cast<std::size_t>(second)]=3;bonusCollection("SH119",extra,a);}auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH119");a.choices={2,2};reject(s,a);a.choices={1};reject(s,a);a.choices={0,5};reject(s,a);});
add("SH120","one-each preference uses5 normal positions then4 available normal-mix extras",[]{auto s=arena();activate(s,make(s,"SH120"));end(s);const auto before=s.materials;collect(s);const auto got=delta(s.materials,before);check(total(got)==14&&got[0]>=1&&got[1]>=3&&got[2]>=2&&got[3]>=2&&got[4]>=2,"Five reserved normal positions and only4 extra");for(Amount available:{10,12,20}){s=arena();activate(s,make(s,"SH120"));end(s);s.finitePile=true;s.pile={available,0,0,0,0};const auto start=s.materials;collect(s);check(delta(s.materials,start)==Materials{std::min(14,available),0,0,0,0},"Unavailable positions fill normally and extra shortage truncates");}magnetExpires("SH120");});
add("SH122","ordered two different nonCircuit choices; unconditional1 then Perfect extra1+2",[]{for(Amount mode:{-1,0,1,2})for(const auto& pair:std::vector<std::vector<Amount>>{{0,3},{3,0}}){auto s=arena();Action a;a.choices=pair;activate(s,make(s,"SH122",a));end(s);const auto before=s.materials;collect(s,mode,2);auto expected=ordinaryHaul;expected[0]-=2;expected[2]+=2+std::max(0,mode);expected[static_cast<std::size_t>(pair[0])]+=mode==2?2:1;if(mode==2)expected[static_cast<std::size_t>(pair[1])]+=2;check(delta(s.materials,before)==expected,"Exact unconditional and Perfect-only ordered amounts");}for(const auto& v:std::vector<std::vector<Amount>>{{0,0},{0,4},{0},{0,1,2}}){auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH122");a.choices=v;reject(s,a);}Action a;a.choices={0,3};bonusCollection("SH122",{1,0,0,0,0},a);});
add("SH123","Glass1 all modes, Perfect Circuit2 extra while ordinary Circuit remains",[]{for(Amount mode:{-1,0,1,2}){auto s=arena();activate(s,make(s,"SH123"));end(s);const auto before=s.materials;collect(s,mode);auto expected=ordinaryHaul;expected[0]+=std::max(0,mode);expected[3]+=1;if(mode==2)expected[4]+=2;check(delta(s.materials,before)==expected,"Any handling Glass and optional Perfect Circuit");}bonusCollection("SH123",{0,0,0,1,0});});
add("SH126","Iron1 anymode; Perfect free physicalAmmo10 Shield10 afterhaul with ordinary use",[]{for(Amount mode:{-1,0,1,2}){auto s=arena();activate(s,make(s,"SH126"));end(s);const auto before=s.materials;collect(s,mode);auto expected=ordinaryHaul;expected[0]+=1+std::max(0,mode);check(delta(s.materials,before)==expected,"Only printed craft cost, no reward material payment");const auto out=outputs(s,"SH126");check(out.size()==static_cast<std::size_t>(mode==2?2:0),"Perfect only two physical rewards");if(mode==2){check(part(s,out[0]).place==Place::Reserve&&part(s,out[1]).place==Place::Reserve&&out[0]!=out[1],"Distinct saveable reserve IDs");next(s);Id ammo=0,shield=0;for(Id id:out){if(part(s,id).kind==Kind::Ammo)ammo=id;else shield=id;}check(firedAmount(fire(s,{ammo}))==10,"Saved plainAmmo10 consumed");install(s,shield);check(Rules::shield(s)==10,"PlainShield10");end(s);check(!exists(s,shield),"Ordinary Shield reset");}}bonusCollection("SH126",{1,0,0,0,0});});
}
