void shieldCases(){
add("SH019","first-install attacker count threshold with snapshot and no refill",[]{for(int n=0;n<=3;++n){auto s=arena();for(int i=0;i<n;++i)attack(s,static_cast<std::size_t>(i),1);const auto p=make(s,"SH019");install(s,p);const auto expected=n>=2?10:7;for(auto& e:s.enemies)e.intent.move=Move::Recover;savedValue(s,p,expected);Rules::spendShield(s,2,true);remove(s,p);install(s,p);check(part(s,p).shield==expected-2,"Spent Shield not refilled");}});
add("SH020","first attacker Weaken2 after its complete attack, installed source only",[]{for(bool removed:{false,true}){auto s=arena();attack(s,0,8);attack(s,1,8);const auto p=make(s,"SH020");install(s,p);if(removed)remove(s,p);end(s);check(s.hp==(removed?984:990),"No retroactive first attack reduction");check(s.enemies[0].weaken==(removed?0:1)&&s.enemies[1].weaken==0,"First attack only then decay");}});
add("SH021","exactly one attacker selects12 otherwise7 at first install",[]{for(int count=0;count<=3;++count){auto s=arena();for(int i=0;i<count;++i)attack(s,static_cast<std::size_t>(i),3);const auto p=make(s,"SH021");install(s,p);for(auto& e:s.enemies)e.intent.move=Move::Recover;savedValue(s,p,count==1?12:7);}});
add("SH022","Shield6 plus at-most3 Burn removed once on first install",[]{for(Amount burn:{0,2,3,5}){auto s=arena();s.burn=burn;const auto p=make(s,"SH022");check(s.burn==burn,"Reserve craft does not clear Burn");install(s,p);check(s.burn==std::max(0,burn-3)&&Rules::shield(s)==6,"Burn floor and Shield6");s.burn=7;remove(s,p);install(s,p);check(s.burn==7,"No repeated first-install cleanse");}});
add("SH023","actual Copper paid by all Uses including Utility and self; cap10 snapshot",[]{for(int n=0;n<=4;++n){auto s=arena();for(int i=0;i<n;++i)use(s,"SH030");const auto p=make(s,"SH023");install(s,p);check(part(s,p).shield==std::min(10,7+2*n),"Own Copper2 plus Utility payments");use(s,"SH030");savedValue(s,p,std::min(10,7+2*n));}auto s=arena();const auto p=make(s,"SH023");next(s);install(s,p);check(part(s,p).shield==5,"Prior-round payments excluded");});
add("SH025","fully blocked attack yields one next-start Iron, not partial or detached",[]{for(int mode:{0,1,2}){auto s=arena();attack(s,0,mode==1?6:2);attack(s,1,2);const auto p=make(s,"SH025");install(s,p);if(mode==2)remove(s,p);const auto iron=s.materials[0];end(s);check(s.materials[0]==iron+(mode==0?1:0),"Once-only next-start Iron eligibility");check(s.hp==(mode==0?1000:mode==1?997:996),"Normal defence");}});
add("SH027","first enemy attack returns3 after attack once with source installed",[]{for(bool removed:{false,true}){auto s=arena();attack(s,0,6);attack(s,1,6);const auto p=make(s,"SH027");install(s,p);if(removed)remove(s,p);end(s);check(s.hp==(removed?988:992)&&s.enemies[0].hp==(removed?10000:9997)&&s.enemies[1].hp==10000,"First reactive hit only");}});
add("SH028","living enemies3 each capped12; dead and escaped excluded",[]{for(int living=1;living<=5;++living){auto s=arena(living+2);s.enemies[static_cast<std::size_t>(living)].dead=true;s.enemies[static_cast<std::size_t>(living)].hp=0;s.enemies.back().escaped=true;const auto p=make(s,"SH028");install(s,p);savedValue(s,p,std::min(12,living*3));}});
add("SH058","first attack exhausting total Shield weakens all living3 once",[]{for(Amount damage:{8,9,10}){auto s=arena();attack(s,0,damage);const auto p=make(s,"SH058");install(s,p);end(s);for(const auto& e:s.enemies)check(e.weaken==(damage>=9?2:0),"Total Shield break threshold then decay");}auto s=arena();attack(s,0,9);attack(s,1,4);const auto p=make(s,"SH058");install(s,p);fixedShield(s,4);end(s);check(s.hp==1000&&s.enemies[0].weaken==2,"Source exhaustion alone insufficient; total exhausted by second attack");});
add("SH059","half maximum inclusive threshold sampled once",[]{for(Amount hp:{499,500,501}){auto s=arena();s.hp=hp;const auto p=make(s,"SH059");install(s,p);s.hp=1000;savedValue(s,p,hp<=500?13:7);}});
add("SH061","marked living enemy count3 each capped9 extra, snapshot",[]{for(int marked=0;marked<=4;++marked){auto s=arena(6);for(int i=0;i<marked;++i)s.enemies[static_cast<std::size_t>(i)].mark=99;s.enemies[4].mark=2;s.enemies[4].dead=true;s.enemies[4].hp=0;s.enemies[5].mark=2;s.enemies[5].escaped=true;const auto p=make(s,"SH061");install(s,p);for(auto& e:s.enemies)e.mark=0;savedValue(s,p,7+std::min(9,marked*3));}});
add("SH062","next main-shot check once even on failure or removal; round expiry",[]{for(int mode:{0,1,2,3}){auto s=arena();const auto p=make(s,"SH062");install(s,p);if(mode==1)s.enemies[0].shield=100;if(mode==2)remove(s,p);if(mode==3){remove(s,p);next(s);install(s,p);}fire(s,{make(s,"SH001")});check(outputs(s,"SH062").size()==static_cast<std::size_t>(mode==0?2:1),"Fresh7 only installed same-round HP damage");s.enemies[0].shield=0;if(mode==2)install(s,p);fire(s,{make(s,"SH001")});check(outputs(s,"SH062").size()==static_cast<std::size_t>(mode==0?2:1),"No second check/rearm");if(mode==0)check(Rules::shield(s)==13,"6 plus fresh7");}});
add("SH063","remove at-most5 Corrosion first install only and Shield8",[]{for(Amount status:{0,4,5,7}){auto s=arena();s.corrosion=status;const auto p=make(s,"SH063");check(s.corrosion==status,"Reserve has no cleanse");install(s,p);check(s.corrosion==std::max(0,status-5)&&Rules::shield(s)==8,"Cleanse cap");s.corrosion=9;remove(s,p);install(s,p);check(s.corrosion==9,"No recleanse");}});
add("SH091","post-actions positive Shield returns6 per surviving attacker only",[]{for(Amount damage:{11,12,13}){auto s=arena();attack(s,0,damage);attack(s,1,damage);const auto p=make(s,"SH091");install(s,p);end(s);check(s.enemies[0].hp==(damage<12?9994:10000)&&s.enemies[1].hp==(damage<12?9994:10000)&&s.enemies[2].hp==10000,"Remaining Shield and attacker recipients");check(!exists(s,p)&&Rules::shield(s)==0,"Ordinary reset after retaliation");}});
add("SH092","first-install15 commits next15; removal never cancels committed delivery",[]{auto s=arena();const auto p=make(s,"SH092");check(s.deliveries.empty(),"Reserve crafting alone no schedule");install(s,p);check(Rules::shield(s)==15,"Immediate installed15");remove(s,p);snapshot(s);end(s);check(Rules::shield(s)==15&&outputs(s,"SH092").size()==2,"First-install committed delivery survives removal");collect(s);install(s,p);end(s);check(Rules::shield(s)==0,"Saved reinstall cannot repeat delivery");s=arena();attack(s,0,0);attack(s,1,2);attack(s,2,2);install(s,make(s,"SH092"));end(s);check(s.enemies[0].mark==0&&s.enemies[1].mark==4&&s.enemies[2].mark==0,"First attack removing Shield only");});
add("SH093","half total shown multi-hit attack damage floor and30 cap",[]{for(Amount damage:{1,3,29,30,31,70}){auto s=arena();attack(s,0,damage,2);attack(s,1,1,1);const auto p=make(s,"SH093");install(s,p);for(auto& e:s.enemies)e.intent.move=Move::Recover;savedValue(s,p,std::min(30,(2*damage+1)/2));}});
add("SH094","direct7 after first two enemy actions not each individual hit",[]{auto s=arena(4);for(std::size_t i=0;i<4;++i)attack(s,i,1,2);const auto p=make(s,"SH094");install(s,p);end(s);check(s.hp==1000&&s.enemies[0].hp==9993&&s.enemies[1].hp==9993&&s.enemies[2].hp==10000&&s.enemies[3].hp==10000,"Two whole-attack triggers");});
add("SH096","first-install12 schedules fresh12 next start even after removal",[]{auto s=arena();const auto p=make(s,"SH096");check(s.deliveries.empty(),"No reserve-only schedule");install(s,p);check(Rules::shield(s)==12&&s.deliveries.size()==1,"Immediate and future12");remove(s,p);snapshot(s);end(s);const auto ids=outputs(s,"SH096");check(ids.size()==2&&Rules::shield(s)==12,"Independent fresh physical delivery");collect(s);install(s,p);end(s);check(Rules::shield(s)==0,"Reinstall does not schedule again");});
add("SH097","first positive enemy HP damage prevented by at-most8 once",[]{for(Amount damage:{14,15,21,22,25}){auto s=arena();attack(s,0,damage);attack(s,1,3);install(s,make(s,"SH097"));end(s);const auto first=std::max(0,damage-14);const auto loss=first>0?std::max(0,first-8)+3:0;check(s.hp==1000-loss,"First HP damage and8 cap");}auto s=arena();attack(s,0,15,2);install(s,make(s,"SH097"));end(s);check(s.hp==985,"Only first HP-bearing hit prevented");});
add("SH098","reserve age Shield10 plus7 per full round max31 snapshot",[]{for(int age:{0,1,2,3,4}){auto s=arena();const auto p=make(s,"SH098");for(int i=0;i<age;++i)next(s);install(s,p);savedValue(s,p,10+7*std::min(3,age));}});
add("SH113","first-install38 commits20 independently; leftover10 gates delivery cooling",[]{auto s=arena();const auto p=make(s,"SH113");install(s,p);remove(s,p);end(s);check(Rules::shield(s)==20,"Removal retains already committed20");for(Amount damage:{28,29,38}){s=arena();attack(s,0,damage);const auto cold=memory(s,"SH118");copy(s,cold).cooldown=3;copy(s,cold).usedRound=s.round;install(s,make(s,"SH113"));end(s);check(Rules::shield(s)==20,"Twenty delivered regardless of leftovers");check(copy(s,cold).cooldown==(damage<=28?2:3),"At least10 pre-reset gates one cooling at delivery");}});
add("SH114","fully blocked attack retaliation10 capped three actions",[]{for(Amount damage:{1,7}){auto s=arena(4);for(std::size_t i=0;i<4;++i)attack(s,i,damage);install(s,make(s,"SH114"));end(s);for(std::size_t i=0;i<4;++i)check(s.enemies[i].hp==(i<3?9990:10000),"Three fully blocked responses only");check(s.hp==(damage==1?1000:997),"Partial fourth attack not blocked");}});
}
