void copyContract(const std::string& recipe,int count){
    const std::vector<std::string> allowed=recipe=="SH071"?std::vector<std::string>{"SH009"}:recipe=="SH102"?std::vector<std::string>{"SH009","SH019","SH026"}:std::vector<std::string>{"SH001","SH002","SH009","SH019","SH052","SH058","SH090","SH098"};
    for(const auto& source:allowed){auto s=arena();Id p=0;if(source=="SH026"){p=use(s,source)[0];remove(s,p);}else p=make(s,source);const auto original=part(s,p);if(original.kind==Kind::Ammo){Action bonus;bonus.parts={p};activate(s,make(s,"SH036"),bonus);}Action a;a.parts={p};const auto result=use(s,recipe,a);check(result.empty()&&exists(s,p),"No immediate copy or consumption of source");snapshot(s);end(s);const auto copies=outputs(s,recipe);check(copies.size()==static_cast<std::size_t>(count),"Next-start exact copy count");std::set<Id> ids{p};for(Id id:copies){auto& q=part(s,id);check(ids.insert(id).second&&q.origin==PartOrigin::Copied&&q.place==Place::Reserve&&q.createdRound==s.round&&!q.everInstalled,"Fresh independent physical copy");check(q.recipe==original.recipe&&q.resaleReference==original.resaleReference&&q.attachments.empty()&&q.upgradeDamage==0&&q.upgradeShield==0,"Printed identity and immutable reference, no later bonus");}collect(s);if(original.kind==Kind::Ammo){const Amount printed=source=="SH001"?6:source=="SH009"?8:source=="SH052"?7:10;for(Id id:copies)check(firedAmount(fire(s,{id}))==printed,"Actual printed-only copy Fire");}else{for(Id id:copies)install(s,id);const Amount printed=source=="SH002"?6:source=="SH019"?7:source=="SH026"?4:source=="SH058"?9:10;check(Rules::shield(s)==count*printed+(source=="SH026"?6:0),"Actual fresh Shield installation");}}
    const std::vector<std::string> denied=recipe=="SH071"?std::vector<std::string>{"SH001","SH019","SH052","SH051","SH037"}:recipe=="SH102"?std::vector<std::string>{"SH001","SH052","SH051","SH037"}:std::vector<std::string>{"SH109","SH113","SH051","SH037"};
    for(const auto& source:denied){auto s=arena();const auto p=make(s,source);Action a;a.type=ActionType::Craft;a.subject=memory(s,recipe);a.parts={p};reject(s,a);}
    auto s=arena();const auto p=make(s,"SH009");Action a;a.type=ActionType::Craft;a.subject=memory(s,recipe);reject(s,a);a.parts={p,p};reject(s,a);a.parts={p};act(s,Action::load({p}));reject(s,a);act(s,Action{ActionType::Unload});
    if(recipe!="SH071"){const auto used=make(s,"SH020");install(s,used);Rules::spendShield(s,1,true);remove(s,used);a.parts={used};reject(s,a);}
}
void utilityCases(){
add("SH015","immediate Mark5 one selected living target once before shot",[]{auto s=arena();Action a;a.target=s.enemies[1].id;check(use(s,"SH015",a).empty(),"Utility produces no item");check(s.enemies[0].mark==0&&s.enemies[1].mark==5,"Selected Mark5 now");fire(s,{make(s,"SH001")},s.enemies[1].id);check(s.enemies[1].hp==9989&&s.enemies[1].mark==0,"Mark applied to next hit once");a.type=ActionType::Craft;a.subject=memory(s,"SH015");a.target=999999;reject(s,a);});
for(const auto& row:std::vector<std::tuple<std::string,int,int>>{{"SH029",0,1},{"SH030",1,3},{"SH031",2,0}}){const auto [id,payment,gain]=row;add(id,"lossy immediate conversion pays printed2 once gains1 with no part",[=]{auto s=arena();s.materials={};s.materials[static_cast<std::size_t>(payment)]=2;const auto recipe=memory(s,id);paid(s,recipe);check(s.parts.empty()&&total(s.materials)==1&&s.materials[static_cast<std::size_t>(gain)]==1,"Exactly2 paid once then1 now");reject(s,Action::craft(recipe));next(s);s.materials[static_cast<std::size_t>(payment)]=2;paid(s,recipe);});}
add("SH032","one unused reserve part sacrificed without payload for nextIron1Glass1",[]{for(const auto& source:{"SH014","SH022","SH037","SH051"}){auto s=arena();const auto p=make(s,source);Action a;a.parts={p};const auto before=s.materials;use(s,"SH032",a);check(!exists(s,p)&&s.sacrificesRound==1&&s.enemies[0].corrosion==0,"Actual sacrifice with no source payload");check(delta(s.materials,before)==Materials{0,-1,0,0,0},"Only printed cost now");const auto paidState=s.materials;end(s);check(delta(s.materials,paidState)==Materials{1,0,0,1,0},"Next-start exact resources");}auto s=arena();const auto p=make(s,"SH002");install(s,p);Rules::spendShield(s,1,true);remove(s,p);Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH032");a.parts={p};reject(s,a);a.parts.clear();reject(s,a);});
add("SH033","independent2 Burn/Corrosion cleanse and immediate removableShield3",[]{for(Amount n:{0,1,2,4}){auto s=arena();s.burn=n;s.corrosion=n+1;const auto parts=use(s,"SH033");check(s.burn==std::max(0,n-2)&&s.corrosion==std::max(0,n-1)&&Rules::shield(s)==3,"Cleanses each independently");check(parts.size()==1,"One generated part");remove(s,parts[0]);next(s);install(s,parts[0]);check(Rules::shield(s)==3,"Saved grant ordinary lifetime");}});
add("SH034","Use schedules fresh8 exactly next start independent of later recipe actions",[]{auto s=arena();check(use(s,"SH034").empty()&&Rules::shield(s)==0,"No immediate item");snapshot(s);end(s);const auto p=outputs(s,"SH034");check(p.size()==1&&Rules::shield(s)==8&&part(s,p[0]).place==Place::Installed,"Fresh auto-installed8");collect(s);remove(s,p[0]);next(s);check(outputs(s,"SH034").size()==1,"Schedule once");install(s,p[0]);check(Rules::shield(s)==8,"Removable and saveable");end(s);check(!exists(s,p[0]),"Ordinary installed reset");});
add("SH035","next first-used Shield+4 once, same-name refresh and turn expiry",[]{auto s=arena();activate(s,make(s,"SH035"));activate(s,make(s,"SH035"));const auto a=make(s,"SH019"),b=make(s,"SH002");install(s,a);install(s,b);check(part(s,a).shield==11&&part(s,b).shield==6,"Bonus once not doubled by refresh");remove(s,a);install(s,a);check(part(s,a).shield==11,"No refill/repeat");s=arena();activate(s,make(s,"SH035"));next(s);install(s,make(s,"SH002"));check(Rules::shield(s)==6,"Unused bonus expires");});
add("SH043","main-only post-Armor bypass redirects at-most12 once then expires",[]{for(Amount damage:{6,18,36}){auto s=arena();activate(s,make(s,"SH043"));activate(s,make(s,"SH043"));s.enemies[0].armor=3;s.enemies[0].shield=50;std::vector<Id> bullet;for(int i=0;i<damage/6;++i)bullet.push_back(make(s,"SH001"));const Amount hp=std::min(12,damage-3);fire(s,bullet);check(s.enemies[0].hp==10000-hp&&s.enemies[0].shield==50-(damage-3-hp),"Redirect not additive and cap12 after Armor");fire(s,{make(s,"SH001")});check(s.enemies[0].hp==10000-hp,"Only next main shot");}auto s=arena();activate(s,make(s,"SH043"));next(s);s.enemies[0].shield=40;fire(s,{make(s,"SH001")});check(s.enemies[0].hp==10000,"Unused bypass expires");});
add("SH049","immediate chosenMark4 and each other livingMark2",[]{auto s=arena(4);s.enemies[3].escaped=true;Action a;a.target=s.enemies[1].id;use(s,"SH049",a);check(s.enemies[0].mark==2&&s.enemies[1].mark==4&&s.enemies[2].mark==2&&s.enemies[3].mark==0,"Mark recipients");a.type=ActionType::Craft;a.subject=memory(s,"SH049");a.target=s.enemies[3].id;reject(s,a);});
add("SH051","physicalSpread40 floor to up-to-two selected others no payloads",[]{for(int targets=0;targets<=2;++targets){auto s=arena(4);const auto ammo=make(s,"SH014"),spread=make(s,"SH051");std::vector<Id> bullet{ammo,make(s,"SH001"),spread};Action a;for(int i=0;i<targets;++i)a.spreadTargets.push_back({spread,s.enemies[static_cast<std::size_t>(i+1)].id});fire(s,bullet,0,a);check(s.enemies[0].hp==9992&&s.enemies[0].corrosion==2,"Main8 and payload");for(int i=1;i<4;++i)check(s.enemies[static_cast<std::size_t>(i)].hp==(i<=targets?9997:10000)&&s.enemies[static_cast<std::size_t>(i)].corrosion==0,"Floor3 spread no status");}auto s=arena(4);const auto p=make(s,"SH051");act(s,Action::load({make(s,"SH001"),p}));auto a=Action::fire(s.enemies[0].id,{{p,s.enemies[1].id},{p,s.enemies[2].id},{p,s.enemies[3].id}});reject(s,a);a.spreadTargets={{p,s.enemies[1].id},{p,s.enemies[1].id}};reject(s,a);a.spreadTargets={{p,s.enemies[0].id}};reject(s,a);act(s,Action{ActionType::Unload});check(exists(s,p)&&part(s,p).place==Place::Reserve,"Unfired spread returned unused");});
add("SH057","Use grants8 and post-paymentIron>=3 schedules5; source removal irrelevant",[]{for(Amount iron:{4,5,6}){auto s=arena();s.materials[0]=iron;const auto out=use(s,"SH057");check(Rules::shield(s)==8&&out.size()==1,"Immediate8");const bool due=s.materials[0]>=3;remove(s,out[0]);end(s);check(Rules::shield(s)==(due?5:0)&&outputs(s,"SH057").size()==static_cast<std::size_t>(due?2:1),"Condition after material payment at Use");collect(s);install(s,out[0]);check(Rules::shield(s)==(due?13:8),"Both ordinary saved parts");}});
add("SH064","Burn prevention once and fouling/leak exclusions; three unavailable status producers unproved",[]{auto s=arena();s.enemies[0].definition="C1-O03";s.enemies[0].robotAction="thermal_runaway";s.enemies[0].intentRound=1;s.enemies[1].definition="C1-O03";s.enemies[1].robotAction="thermal_runaway";s.enemies[1].intentRound=1;activate(s,make(s,"SH064"));check(Rules::shield(s)==5,"ImmediateShield5");const auto r=end(s);check(eventAmount(r,"status_prevented")==2&&s.burn==2,"First Burn prevented, second applies");});
add("SH065","unused reserve Ammo sacrifice has no payload; Shield10 now Iron1 next",[]{auto s=arena();const auto p=make(s,"SH014");Action a;a.parts={p};const auto out=use(s,"SH065",a);check(!exists(s,p)&&s.enemies[0].corrosion==0&&Rules::shield(s)==10&&out.size()==1,"No sacrificed Ammo effects");const auto before=s.materials;end(s);check(delta(s.materials,before)==Materials{1,0,0,0,0},"Iron1 next start");s=arena();a.type=ActionType::Craft;a.subject=memory(s,"SH065");a.parts={make(s,"SH002")};reject(s,a);a.parts.clear();reject(s,a);});
add("SH066","automatic complete groups0..14 cap3; ordered readers see remainder",[]{for(Amount n=0;n<=14;++n){auto s=arena();fixedShield(s,n);activate(s,make(s,"SH066"));s.retentionAllowances={100};const auto before=s.materials[0];end(s);check(s.materials[0]==before+std::min(3,n/3)&&Rules::shield(s)==n-3*std::min(3,n/3),"Automatic minimum payment for maximum complete reward");}for(bool sweepFirst:{false,true}){auto s=arena();if(sweepFirst)activate(s,make(s,"SH066"));install(s,make(s,"MA055"));if(!sweepFirst)activate(s,make(s,"SH066"));const auto before=s.materials[0];end(s);check(s.materials[0]==before+(sweepFirst?3:5),"Reader observes ordered pre-reset current balance");}auto s=arena();install(s,make(s,"SH060"));activate(s,make(s,"SH066"));const auto before=s.materials[0];end(s);check(s.materials[0]==before,"Earlier SH060 discards all before Sweep");});
for(const auto& item:std::vector<std::pair<std::string,Amount>>{{"SH067",2},{"SH068",1},{"SH099",999},{"SH100",1},{"SH116",999}}){const auto id=item.first;const auto amount=item.second;add(id,"cool every currently cooling physical copy, floor0; paid recraft still required",[=]{auto s=arena();std::vector<Id> ids;for(int n=0;n<=4;++n){const auto c=memory(s,"SH052");copy(s,c).cooldown=n;ids.push_back(c);}const auto used=memory(s,"SH001");paid(s,used);use(s,id);for(std::size_t i=0;i<ids.size();++i)check(copy(s,ids[i]).cooldown==std::max(0,static_cast<Amount>(i)-amount),"Each physical cooldown reduced/clamped");reject(s,Action::craft(used));if(amount==999){s.materials={};reject(s,Action::craft(ids.back()));s.materials=printedCosts.at("SH052");paid(s,ids.back());}snapshot(s);});}
add("SH069","choose Copper Carbon or Glass2 only at next start",[]{for(Amount material:{1,2,3}){auto s=arena();Action a;a.choices={material};use(s,"SH069",a);const auto before=s.materials;end(s);Materials expected{};expected[static_cast<std::size_t>(material)]=2;check(delta(s.materials,before)==expected,"Chosen delivery2");}for(std::vector<Amount> choices:std::vector<std::vector<Amount>>{{},{0},{4},{1,2}}){auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH069");a.choices=choices;reject(s,a);}});
add("SH070","next-turn first qualifying >=2Iron Use includes Utility; cheap Uses do not consume",[]{for(const auto& eligible:{"SH009","SH104"}){auto s=arena();activate(s,make(s,"SH070"));use(s,"SH009");next(s);use(s,"SH001");use(s,eligible,{},Materials{1,0,0,0,0});use(s,eligible);check(s.round==2,"Only next turn");}auto s=arena();activate(s,make(s,"SH070"));next(s);next(s);use(s,"SH009");});
add("SH071","Common Ammo printed copy next start with selectors and exclusions",[]{copyContract("SH071",1);});
add("SH072","next shot selected Base/Common Ammo consumed then fresh printed copy once",[]{for(const auto& source:{"SH001","SH009"}){auto s=arena();activate(s,make(s,"SH072"));const auto p=make(s,source);Action bonus;bonus.parts={p};activate(s,make(s,"SH036"),bonus);act(s,Action::load({p}));auto a=Action::fire(s.enemies[0].id);reject(s,a);a.partChoices={{0,p}};act(s,a);check(!exists(s,p)&&outputs(s,"SH072").empty(),"Only future copy after consumption");end(s);const auto out=outputs(s,"SH072");check(out.size()==1&&part(s,out[0]).origin==PartOrigin::Copied&&part(s,out[0]).attachments.empty(),"Fresh printed copy");collect(s);check(firedAmount(fire(s,out))==(std::string(source)=="SH001"?6:8),"Bonus not copied");end(s);check(outputs(s,"SH072").empty(),"Once-only trigger");}auto s=arena();activate(s,make(s,"SH072"));const auto p=make(s,"SH052");act(s,Action::load({p}));auto a=Action::fire(s.enemies[0].id);a.partChoices={{0,p}};reject(s,a);});
add("SH073","cleanse up-to6 each Weaken Mark plus nextshot3 expiresEndTurn",[]{for(Amount n:{0,5,6,8}){auto s=arena();s.weaken=s.mark=n;use(s,"SH073");check(s.weaken==std::max(0,n-6)&&s.mark==std::max(0,n-6),"Independent cleansing cap");check(firedAmount(fire(s,{make(s,"SH001")}))==9-std::max(0,n-6),"Next shot adds3");check(firedAmount(fire(s,{make(s,"SH001")}))==6-std::max(0,n-6),"Once only");}auto s=arena();use(s,"SH073");next(s);check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Expired unspent bonus");});
add("SH076","sacrifice fixed unused Shield printed value capped14; no secondary effects",[]{for(const auto& row:std::vector<std::pair<std::string,Amount>>{{"SH002",6},{"SH020",6},{"SH063",8},{"SH097",14},{"SH091",14}}){auto s=arena();s.corrosion=5;const auto p=make(s,row.first);Action a;a.parts={p};const auto out=use(s,"SH076",a);check(out.size()==1&&!exists(s,p)&&s.corrosion==5&&Rules::shield(s)==0,"Sacrifice does not install or cleanse");check(firedAmount(fire(s,out))==row.second,"Plain printed amount cap14");check(s.enemies[0].weaken==0&&s.enemies[1].hp==10000,"No former Shield secondary payload");}for(const auto& source:{"SH019","SH023","SH059","SH098","SH001"}){auto s=arena();Action a;a.type=ActionType::Craft;a.subject=memory(s,"SH076");a.parts={make(s,source)};reject(s,a);}});
add("SH082","all other living half whole-shot floored, payload main only",[]{auto s=arena(4);s.enemies[3].escaped=true;const auto spread=make(s,"SH082");fire(s,{make(s,"SH016"),spread});check(s.enemies[0].hp==9995&&s.enemies[0].weaken==4&&s.enemies[1].hp==9998&&s.enemies[2].hp==9998&&s.enemies[3].hp==10000&&s.enemies[1].weaken==0,"Every living extra floor2 direct only");});
add("SH083","nextshot additive8percent per Ammo capped80; Spread excluded and expires",[]{for(int count:{1,9,10,11}){auto s=arena();activate(s,make(s,"SH083"));std::vector<Id> ids;for(int i=0;i<count;++i)ids.push_back(make(s,"SH001"));ids.push_back(make(s,"SH051"));check(firedAmount(fire(s,ids))==count*6+count*6*std::min(80,count*8)/100,"Whole integer percent count cap");check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Next only");}auto s=arena();activate(s,make(s,"SH083"));next(s);check(firedAmount(fire(s,{make(s,"SH001")}))==6,"EndTurn expiry");});
add("SH095","Weaken8 current attackers and Shield5 per nonattacker cap15",[]{for(int n=0;n<=4;++n){auto s=arena(5);for(int i=0;i<5-n;++i)attack(s,static_cast<std::size_t>(i),10);activate(s,make(s,"SH095"));check(Rules::shield(s)==std::min(15,n*5),"Nonattacker count cap");for(int i=0;i<5;++i)check(s.enemies[static_cast<std::size_t>(i)].weaken==(i<5-n?8:0),"Only attackers weakened");}});
add("SH102","Common Ammo or Shield two next-start printed copies and exclusions",[]{copyContract("SH102",2);});
add("SH103","next crafted Ammo one chosen output+8 firstuse, no grant and round expiry",[]{auto s=arena();activate(s,make(s,"SH103"));make(s,"SH002");const auto before=s.nextId;check(rules.grantPart(s,"SH001").ok,"Controlled free grant");const auto free=created(s,before)[0];Action a;a.amount=1;const auto parts=use(s,"MA038",a);check(parts.size()==2&&part(s,parts[0]).attachments.empty()&&part(s,parts[1]).attachments.size()==1,"Chosen physical member only");check(firedAmount(fire(s,{parts[0]}))==4&&firedAmount(fire(s,{parts[1]}))==12&&firedAmount(fire(s,{free}))==6,"Only next paid output gains8");check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Once only");s=arena();activate(s,make(s,"SH103"));next(s);check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Unused mould expires");});
add("SH104","actual healing8 clamps max and shared16; no-attackerShield independent",[]{auto s=arena();s.hp=997;use(s,"SH104");check(s.hp==1000&&s.carefulHealing==3&&Rules::shield(s)==8,"Actual3 counts not8");s.hp=970;use(s,"SH104");check(s.hp==978&&s.carefulHealing==11,"Second heals8");use(s,"SH104");check(s.hp==983&&s.carefulHealing==16,"Cap remaining5");use(s,"SH104");check(s.hp==983&&Rules::shield(s)==32,"Cap shared but Shield remains");s=arena();s.hp=990;attack(s,0,1);use(s,"SH104");check(s.hp==998&&Rules::shield(s)==0,"Attacker blocks Shield only");});
add("SH110","physical all-target spread reserves unusedShield untilFire sacrifice without effect",[]{auto s=arena();const auto spread=make(s,"SH110"),shield=make(s,"SH063"),ammo=make(s,"SH014");s.corrosion=5;auto load=Action::load({ammo,spread});reject(s,load);load.sacrifices={ammo};reject(s,load);load.sacrifices={shield};act(s,load);check(exists(s,shield)&&part(s,shield).place==Place::Payment,"Reservation not consumption");act(s,Action{ActionType::Unload});check(part(s,shield).place==Place::Reserve,"Unload releases payment");act(s,load);act(s,Action::fire(s.enemies[0].id));check(!exists(s,shield)&&!exists(s,spread)&&s.corrosion==5&&Rules::shield(s)==0,"Sacrifice no Shield or cleanse");check(s.enemies[0].hp==9998&&s.enemies[0].corrosion==2&&s.enemies[1].hp==9998&&s.enemies[1].corrosion==0&&s.enemies[1].weaken==3&&s.enemies[2].weaken==3,"100percent extra direct then Weaken3 only extras");});
add("SH111","nextshot double damage, Shield15 threshold10Ammo excludesSpread",[]{for(int count:{9,10,11}){auto s=arena();activate(s,make(s,"SH111"));std::vector<Id> ids;for(int i=0;i<count;++i)ids.push_back(make(s,"SH001"));ids.push_back(make(s,"SH051"));check(firedAmount(fire(s,ids))==12*count&&Rules::shield(s)==(count>=10?15:0),"Double and count threshold");check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Next only");}auto s=arena();activate(s,make(s,"SH111"));next(s);check(firedAmount(fire(s,{make(s,"SH001")}))==6,"Unspent expiry");});
add("SH117","four materials2 nextstart once noCircuit; fight ends before delivery loses grant",[]{auto s=arena();use(s,"SH117");const auto before=s.materials;snapshot(s);end(s);check(delta(s.materials,before)==Materials{2,2,2,2,0},"Exact delayed stock");collect(s);const auto after=s.materials;end(s);check(s.materials==after,"No repeat");s=arena(1);use(s,"SH117");s.enemies[0].hp=6;fire(s,{make(s,"SH001")});check(s.phase==Phase::Victory,"Fight ends before delivery");reject(s,Action::endTurn());});
add("SH118","Base throughRare Ammo Shield two fresh printed copies excludesLegendary and nonparts",[]{copyContract("SH118",2);});
}
