#include "city_runner.hpp"
#include "overkill/robots.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <cmath>
#include <iostream>
#include <stdexcept>
using namespace overkill;using namespace overkill::runner;
int main(){try{int checks=0;const auto check=[&](bool yes,const std::string& why){++checks;if(!yes)throw std::runtime_error(why);};
    CampaignAction a;a.type=CampaignActionType::ResolveUpgradeOffer;a.runId="test \"quoted\"\nrun";a.sequence=12;a.subject=13;a.exchange=14;a.target=15;a.choice="SH001";a.quantity=2;a.eventShop=true;a.decline=true;a.material=4;auto& b=a.combat;b.type=ActionType::ResolveUpgradeChoice;b.subject=21;b.target=22;b.parts={3,4};b.spreadTargets={{3,8}};b.steering=2;b.precision=1;b.amount=6;b.choices={0,1};b.targets={6,7};b.sacrifices={8};b.partTargets={{9,10}};b.partChoices={{11,12}};b.discarded={1,2,3,4,5};b.upgradeChoice={23,{24,25},{1,2},"defence",{1,0,0,0,0},{0,0,0,0,1},true};b.discount={0,1,0,0,0};b.upgrade="MY1-10";const auto text=encodeAction(a);CampaignAction decoded;std::string error;check(decodeAction(unhex(hex(text)),decoded,error),error);check(encodeAction(decoded)==text,"Command codec lost an Action field");check(!decodeAction(text+" extra",decoded,error),"Trailing command fields accepted");check(!decodeAction(text.substr(0,text.size()/2),decoded,error),"Truncated command accepted");
    Rules fights;CampaignRules campaign(fights,cinderwallUpgradeHooks(fights));Options options;options.seed=1;options.timeoutSeconds=30;options.trace="runner-tests/replay.oftrace";const auto result=runCity(options,fights,campaign);check(result.outcome=="city_complete"||result.outcome=="defeat"||result.outcome=="blocked_rule","Baseline did not reach a legitimate terminal or held rule: "+result.outcome+" "+result.reason);check(replayTrace(options.trace,campaign).find(result.hash)!=std::string::npos,"Exact replay differs");
    {std::ifstream in(options.trace,std::ios::binary);const std::string original((std::istreambuf_iterator<char>(in)),{});const auto reject=[&](const std::string& content,const std::string& why){std::ofstream out("runner-tests/tampered.oftrace",std::ios::binary);out<<content;out.close();bool rejected=false;try{replayTrace("runner-tests/tampered.oftrace",campaign);}catch(const std::exception&){rejected=true;}check(rejected,why);};
        const auto row=[&](const std::string& prefix,const std::string& replacement){auto text=original;const auto start=text.find(prefix);check(start!=std::string::npos,"Missing trace fixture row");text.replace(start,text.find('\n',start)-start,replacement);return text;};
        auto content=original;const auto position=content.find("\nE ");check(position!=std::string::npos,"Replay fixture has no events");content[position+3]='!';reject(content,"Tampered event did not fail replay");
        reject(row("META ","META "),"Empty metadata accepted");
        content=original;content.replace(content.find(RulesVersion),std::string(RulesVersion).size(),"wrong-rules");reject(content,"Wrong rules metadata accepted");
        content=original;content.replace(content.find("\"aggressive\""),12,"\"defensive\"");reject(content,"Metadata policy differs from original campaign identity");
        for(const auto* prefix:{"META ","R ","FINAL "}){const auto start=original.find(prefix),end=original.find('\n',start);reject(row(prefix,original.substr(start,end-start)+" extra"),"Trailing fields accepted in "+std::string(prefix));}
        content=original;const auto final=content.find("FINAL "),outcome=content.find(result.outcome,final);content.replace(outcome,result.outcome.size(),result.outcome=="city_complete"?"defeat":"city_complete");reject(content,"False final outcome accepted");
        reject(original.substr(0,original.find("FINAL ")),"Truncated trace accepted");
    }
    {Options calibrated=options;calibrated.seed=2;calibrated.policy="defensive";calibrated.trace="runner-tests/calibration.oftrace";const auto visit=runCity(calibrated,fights,campaign);check(std::find(visit.choices.begin(),visit.choices.end(),"UGS-030")!=visit.choices.end(),"Technician policy fixture changed");check(visit.hpPaid==8,"Technician's actual 8 HP service payment missing or counted twice");check(visit.hp==80+visit.healing-visit.hpLost-visit.hpPaid,"City attrition totals do not reconcile");}
    {auto c=campaign.newGame(2,"information-boundary");c.phase=CityPhase::Fight;c.fight=Rules::teachingEncounter(2,true);check(fights.apply(c.fight,Action::collect(0)).ok,"Information fixture collection");auto hidden=c;hidden.fight.rng=Rng::seeded(9876,"concealed");for(auto& e:hidden.fight.enemies){e.pattern={{Move::Attack,999,9},{Move::Escape,0,0}};e.patternRandom=7654321;}Policy first(fights,campaign,options),second(fights,campaign,options);const auto x=first.choose(c),y=second.choose(hidden);check(x.available&&y.available&&encodeAction(x.action)==encodeAction(y.action),"Policy decision depended on future enemy pattern or RNG");}
    {auto c=campaign.newGame(3,"hidden-mystery");c.phase=CityPhase::Between;c.shop.clear();c.route.nodes[0].offers={{1,EncounterKind::Mystery,"","C1-M-PATROL"},{2,EncounterKind::Mystery,"","C1-M-EXCHANGE"},{3,EncounterKind::Regular,"C1-F-RAM"}};auto hidden=c;hidden.route.nodes[0].offers[0].mystery="C1-M-TECH";hidden.route.nodes[0].offers[0].formation="C1-F-CHASSIS";hidden.route.nodes[0].offers[1].mystery="C1-M-PATROL";Options defensive=options;defensive.policy="defensive";Policy first(fights,campaign,defensive),second(fights,campaign,defensive);first.choose(c);second.choose(hidden);check(encodeAction(first.choose(c).action)==encodeAction(second.choose(hidden).action),"Policy inspected a concealed Mystery category/formation");}
    // Canonical bands from design/data/beta-balance-v1.json. Means alone cannot
    // distinguish Good from Perfect, which trigger different real upgrades.
    for(const auto& model:std::vector<std::pair<std::string,std::array<int,3>>>{{"learning",{55,35,10}},{"practised",{20,45,35}},{"expert",{5,25,70}}}){auto c=campaign.newGame(1,"precision-model");c.phase=CityPhase::Fight;c.fight.phase=Phase::Collection;Options o=options;o.precision=model.first;Policy p(fights,campaign,o);std::array<int,3> counts{};double total=0;for(int i=0;i<10000;++i){const auto choice=p.choose(c);check(choice.action.combat.precision>=0&&choice.action.combat.precision<=2,"Invalid recorded Precision outcome");total+=choice.action.combat.precision;++counts[static_cast<std::size_t>(choice.action.combat.precision)];}for(std::size_t i=0;i<3;++i)check(std::abs(counts[i]/10000.0-model.second[i]/100.0)<0.015,"Synthetic Precision category differs from canonical data");check(std::abs(total/10000-(model.second[1]+2*model.second[2])/100.0)<0.025,"Synthetic Precision mean differs from declared model");c.fight.precisionSpent=true;check(p.choose(c).action.combat.precision==-1,"Policy retries Precision on a later round");}
    for(Amount mark:{0,24,108}){auto c=campaign.newGame(7,"chassis-progress");c.phase=CityPhase::Fight;auto& s=c.fight;s.phase=Phase::Preparation;s.heat=10;s.round=2;s.enemies=makeCinderwallFormation("C1-F-CHASSIS",7,"chassis-progress",s.nextId);s.enemies.front().hp=1;s.enemies.front().mark=mark;s.enemies.front().intent={Move::Support,0,0};s.enemies.front().robotAction="thermal_runaway";check(fights.grantPart(s,"SH001").ok,"Chassis policy fixture Ammo");Policy p(fights,campaign,options);const auto pick=p.choose(c);check(pick.available&&pick.action.combat.type==ActionType::Load,"Policy preserves excessive Mark instead of killing the Chassis and releasing its helper");const auto loaded=fights.preview(s,pick.action.combat);const auto shot=fights.preview(loaded.state,Action::fire(s.enemies.front().id));check(shot.result.ok&&shot.state.kills==1&&shot.state.enemies.size()==2,"Policy fixture must actually release the Chassis helper");}
    {auto c=campaign.newGame(13,"shield-progress");c.phase=CityPhase::Fight;auto& s=c.fight;s.phase=Phase::Preparation;s.heat=10;for(Amount hp:{2,1}){Enemy e;e.id=s.nextId++;e.hp=e.maxHp=hp;e.intent={Move::Attack,6,1};s.enemies.push_back(e);}check(fights.grantPart(s,"SH001").ok&&fights.grantPlainPart(s,Kind::Shield,17,"policy-fixture",true).ok,"Shield policy fixture");Options o=options;o.policy="defensive";Policy p(fights,campaign,o);const auto pick=p.choose(c);check(pick.available&&pick.action.combat.type==ActionType::Load,"Policy values an unnecessary Shield more than eliminating an attacker");}
    std::cout<<"PASS "<<checks<<" runner codec/replay assertions; seed1 outcome="<<result.outcome<<", actions="<<result.actions<<"\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
