#include "city_runner.hpp"
#include "overkill/upgrades.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>

namespace overkill::runner {
namespace {
void need(bool b,const std::string& why){if(!b)throw std::runtime_error(why);}
void exhausted(std::istream& in,const std::string& why){need(static_cast<bool>(in),why);in>>std::ws;need(in.eof(),why);}
std::string quote(const std::string& value){std::ostringstream o;o<<'"';for(unsigned char c:value){if(c=='"'||c=='\\')o<<'\\'<<c;else if(c<32)o<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<static_cast<unsigned>(c);else o<<c;}o<<'"';return o.str();}
void strings(std::ostream& out,const std::vector<std::string>& values){out<<'[';bool comma=false;for(const auto& value:values){if(comma)out<<',';comma=true;out<<quote(value);}out<<']';}
template<class Values> void numbers(std::ostream& out,const Values& values){out<<' '<<values.size();for(const auto& v:values)out<<' '<<v;}
template<class Values> void pairs(std::ostream& out,const Values& values){out<<' '<<values.size();for(const auto& v:values)out<<' '<<v.part<<' '<<v.enemy;}
template<class T> void readNumbers(std::istream& in,std::vector<T>& values,std::size_t limit){std::size_t n=0;in>>n;need(n<=limit,"Invalid action vector length");values.resize(n);for(auto& x:values)in>>x;}
void readMaterials(std::istream& in,Materials& values){std::size_t n=0;in>>n;need(n==values.size(),"Wrong material vector length");for(auto& x:values)in>>x;}
void readPairs(std::istream& in,std::vector<SpreadTarget>& values,std::size_t limit){std::size_t n=0;in>>n;need(n<=limit,"Invalid action pair length");values.resize(n);for(auto& x:values)in>>x.part>>x.enemy;}
const char* kind(EncounterClass k){return k==EncounterClass::Boss?"boss":k==EncounterClass::Officer?"officer":"regular";}
void recordEvents(RunRecord& result,const State& before,const Campaign& after,const CampaignAction& action,const std::vector<Event>& events){
    std::int64_t healed=0,damaged=0,paid=0;
    for(const auto& e:events){if(e.type=="recipe_used")for(std::size_t i=0;i<5;++i)result.spent[i]+=e.paid[i];if(e.type=="heal"||e.type.rfind("upgrade_heal:",0)==0)healed+=e.amount;if(e.type=="player_damage")damaged+=e.amount;if(e.type=="hp_cost"||e.type=="acquisition_hp_cost")paid+=e.amount;}
    // The outer Technician service debits HP in CampaignRules without an
    // event. Attribute its actual residual debit after the acquired upgrade's
    // separately reported healing/damage/payment, rather than duplicating its
    // printed price or counting a nested acquisition payment twice.
    if(action.type==CampaignActionType::AcceptCalibration)paid+=std::max<std::int64_t>(0,static_cast<std::int64_t>(before.hp)-after.fight.hp+healed-damaged-paid);
    result.healing+=healed;result.hpLost+=damaged;result.hpPaid+=paid;
    std::int64_t purchase=0;if(action.type==CampaignActionType::Buy){const auto& stock=action.eventShop?after.eventShop:after.shop;for(const auto& p:stock)if(p.id==action.subject)purchase=static_cast<std::int64_t>(upgradeShopPrice(before,static_cast<PurchaseKind>(p.kind),p.price))*action.quantity;}
    const auto creditDelta=static_cast<std::int64_t>(after.fight.credits)-before.credits+purchase;result.spending+=purchase;if(creditDelta>0)result.income+=creditDelta;else result.spending-=creditDelta;
    for(std::size_t i=0;i<5;++i)if(after.fight.materials[i]>before.materials[i])result.gained[i]+=after.fight.materials[i]-before.materials[i];
    if(!action.choice.empty())result.choices.push_back(action.choice);
}
}
std::string hex(const std::string& data){static const char* digits="0123456789abcdef";std::string out;out.reserve(data.size()*2);for(unsigned char c:data){out+=digits[c>>4];out+=digits[c&15];}return out;}
std::string unhex(const std::string& encoded){need(encoded.size()%2==0,"Odd hex length");const auto digit=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;throw std::runtime_error("Invalid hexadecimal byte");};std::string out;out.reserve(encoded.size()/2);for(std::size_t i=0;i<encoded.size();i+=2)out+=static_cast<char>((digit(encoded[i])<<4)|digit(encoded[i+1]));return out;}
std::string encodeAction(const CampaignAction& a){std::ostringstream o;o<<static_cast<int>(a.type)<<' '<<std::quoted(a.runId)<<' '<<a.sequence<<' '<<a.subject<<' '<<a.exchange<<' '<<a.target<<' '<<std::quoted(a.choice)<<' '<<a.quantity<<' '<<a.eventShop<<' '<<a.decline<<' '<<a.material;const auto& b=a.combat;o<<' '<<static_cast<int>(b.type)<<' '<<b.subject<<' '<<b.target<<' '<<b.steering<<' '<<b.precision<<' '<<b.amount;numbers(o,b.parts);pairs(o,b.spreadTargets);numbers(o,b.choices);numbers(o,b.targets);numbers(o,b.sacrifices);pairs(o,b.partTargets);pairs(o,b.partChoices);numbers(o,b.discarded);o<<' '<<b.upgradeChoice.choice;numbers(o,b.upgradeChoice.objects);numbers(o,b.upgradeChoice.values);o<<' '<<std::quoted(b.upgradeChoice.option);numbers(o,b.upgradeChoice.removed);numbers(o,b.upgradeChoice.added);o<<' '<<b.upgradeChoice.decline;numbers(o,b.discount);o<<' '<<std::quoted(b.upgrade);return o.str();}
bool decodeAction(const std::string& text,CampaignAction& out,std::string& error){try{CampaignAction a;std::istringstream in(text);int type=0,combat=0;in>>type>>std::quoted(a.runId)>>a.sequence>>a.subject>>a.exchange>>a.target>>std::quoted(a.choice)>>a.quantity>>a.eventShop>>a.decline>>a.material;auto& b=a.combat;in>>combat>>b.subject>>b.target>>b.steering>>b.precision>>b.amount;need(type>=0&&type<=static_cast<int>(CampaignActionType::MoveRecipeCopy)&&combat>=0&&combat<=static_cast<int>(ActionType::ActivateUpgrade),"Invalid action enum");a.type=static_cast<CampaignActionType>(type);b.type=static_cast<ActionType>(combat);readNumbers(in,b.parts,text.size());readPairs(in,b.spreadTargets,text.size());readNumbers(in,b.choices,text.size());readNumbers(in,b.targets,text.size());readNumbers(in,b.sacrifices,text.size());readPairs(in,b.partTargets,text.size());readPairs(in,b.partChoices,text.size());readMaterials(in,b.discarded);in>>b.upgradeChoice.choice;readNumbers(in,b.upgradeChoice.objects,text.size());readNumbers(in,b.upgradeChoice.values,text.size());in>>std::quoted(b.upgradeChoice.option);readMaterials(in,b.upgradeChoice.removed);readMaterials(in,b.upgradeChoice.added);in>>b.upgradeChoice.decline;readMaterials(in,b.discount);in>>std::quoted(b.upgrade);need(static_cast<bool>(in),"Truncated command");in>>std::ws;need(in.eof(),"Trailing command fields");out=std::move(a);error.clear();return true;}catch(const std::exception& e){error=e.what();return false;}}
std::string summaryJson(const RunRecord& r){std::ostringstream o;o<<"{\"seed\":"<<r.seed<<",\"policy\":"<<quote(r.policy)<<",\"policy_version\":"<<quote(PolicyVersion)<<",\"precision\":"<<quote(r.precision)<<",\"outcome\":"<<quote(r.outcome)<<",\"reason\":"<<quote(r.reason)<<",\"hp\":"<<r.hp<<",\"position\":"<<r.position<<",\"actions\":"<<r.actions<<",\"previews\":"<<r.previews<<",\"seconds\":"<<std::fixed<<std::setprecision(3)<<r.seconds<<",\"income\":"<<r.income<<",\"spending\":"<<r.spending<<",\"healing\":"<<r.healing<<",\"hp_lost\":"<<r.hpLost<<",\"hp_paid\":"<<r.hpPaid<<",\"state_hash\":"<<quote(r.hash)<<",\"trace\":"<<quote(r.trace)<<",\"materials_spent\":[";for(std::size_t i=0;i<5;++i){if(i)o<<',';o<<r.spent[i];}o<<"],\"materials_gained\":[";for(std::size_t i=0;i<5;++i){if(i)o<<',';o<<r.gained[i];}o<<"],\"fights\":[";bool comma=false;for(const auto& f:r.fights){if(comma)o<<',';comma=true;o<<"{\"encounter\":"<<quote(f.encounter)<<",\"kind\":"<<quote(f.kind)<<",\"outcome\":"<<quote(f.outcome)<<",\"hp_start\":"<<f.hpStart<<",\"hp_end\":"<<f.hpEnd<<",\"rounds\":"<<f.rounds<<",\"shots\":"<<f.shots<<",\"kills\":"<<f.kills<<",\"recipes_at_entry\":";strings(o,f.recipes);o<<",\"upgrades_at_entry\":";strings(o,f.upgrades);o<<",\"choices\":";strings(o,f.choices);o<<'}';}o<<"],\"choices\":";strings(o,r.choices);o<<'}';return o.str();}
RunRecord runCity(const Options& options,const Rules& fights,const CampaignRules& rules){
    const auto started=std::chrono::steady_clock::now();RunRecord result;result.seed=options.seed;result.policy=options.policy;result.precision=options.precision;result.trace=options.trace;
    auto c=rules.newGame(options.seed,"runner/"+std::to_string(options.seed)+"/"+options.policy+"/"+options.precision);Policy policy(fights,rules,options);std::ofstream trace;if(!options.trace.empty()){const auto path=std::filesystem::path(options.trace);if(path.has_parent_path())std::filesystem::create_directories(path.parent_path());trace.open(path,std::ios::binary);need(static_cast<bool>(trace),"Cannot create trace");trace<<"OFCITY2\nMETA "<<quote(RulesVersion)<<' '<<quote(ContentVersion)<<' '<<quote(c.manifestHash)<<' '<<quote(PolicyVersion)<<' '<<quote(options.policy)<<' '<<quote(options.precision)<<' '<<options.searchBudget<<"\nSTART "<<hex(serializeCampaign(c))<<'\n';}
    bool active=false;FightRecord current;
    while(c.phase!=CityPhase::Complete&&c.phase!=CityPhase::Defeated){
        const auto elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();if(elapsed>options.timeoutSeconds){result.outcome="policy_timeout";result.reason="Runner wall-clock watchdog; no in-game action or turn cap.";break;}
        const auto decision=policy.choose(c);if(!decision.available){result.outcome="unsupported_choice";result.reason=decision.reason;break;}
        const auto before=c.fight;const auto action=decision.action;const auto applied=rules.apply(c,action);++result.actions;
        if(trace){trace<<"A "<<hex(encodeAction(action))<<'\n';trace<<"R "<<applied.ok<<' '<<std::quoted(applied.reason)<<' '<<campaignHash(c)<<' '<<applied.events.size()<<'\n';for(const auto& e:applied.events)trace<<"E "<<eventJson(e)<<'\n';}
        if(!applied.ok){result.outcome=applied.reason.find("owner decision")!=std::string::npos?"blocked_rule":"policy_error";result.reason=applied.reason;break;}
        recordEvents(result,before,c,action,applied.events);
        if(!active&&c.phase==CityPhase::Fight){active=true;current={};current.encounter=c.fight.encounter;current.kind=kind(c.fight.encounterClass);current.hpStart=c.fight.hp;for(const auto& copy:c.fight.memory)current.recipes.push_back(copy.recipe);for(const auto& upgrade:c.fight.upgrades)current.upgrades.push_back(upgrade.id);}
        if(active){current.rounds=std::max(current.rounds,before.round);current.hpEnd=c.fight.hp;for(const auto& e:applied.events){if(e.type=="fire"){++current.shots;current.choices.push_back("fire:"+std::to_string(e.target));}if(e.type=="enemy_death")++current.kills;if(e.type=="recipe_used")current.choices.push_back("use:"+e.source);}if(action.type==CampaignActionType::Combat&&action.combat.type==ActionType::Collect)current.choices.push_back("collect:"+std::to_string(action.combat.steering)+"/"+std::to_string(action.combat.precision));if(action.type==CampaignActionType::ResolveUpgradeChoice||action.type==CampaignActionType::ResolveUpgradeOffer)current.choices.push_back("nested-command:"+std::to_string(action.sequence));if(c.phase!=CityPhase::Fight){current.outcome=c.phase==CityPhase::Defeated?"defeat":current.kills?"victory":"escaped";result.fights.push_back(current);active=false;}}
    }
    if(result.outcome.empty())result.outcome=c.phase==CityPhase::Complete?"city_complete":"defeat";if(active){current.hpEnd=c.fight.hp;current.rounds=std::max(current.rounds,c.fight.round);current.outcome=result.outcome;result.fights.push_back(current);}
    result.hp=c.fight.hp;result.position=c.route.position;result.hash=campaignHash(c);result.previews=policy.previews();result.seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();if(trace)trace<<"FINAL "<<result.hash<<' '<<result.outcome<<' '<<hex(serializeCampaign(c))<<'\n';return result;
}
std::string replayTrace(const std::string& file,const CampaignRules& rules){
    std::ifstream trace(file,std::ios::binary);need(static_cast<bool>(trace),"Cannot read trace");std::string line;std::getline(trace,line);need(line=="OFCITY2","Unsupported runner trace");std::getline(trace,line);need(line.rfind("META ",0)==0,"Missing trace metadata");
    std::istringstream meta(line.substr(5));std::string ruleVersion,contentVersion,manifest,policyVersion,policy,precision,budgetText;meta>>std::quoted(ruleVersion)>>std::quoted(contentVersion)>>std::quoted(manifest)>>std::quoted(policyVersion)>>std::quoted(policy)>>std::quoted(precision)>>budgetText;exhausted(meta,"Invalid trace metadata fields");need(!budgetText.empty()&&std::all_of(budgetText.begin(),budgetText.end(),[](char c){return c>='0'&&c<='9';}),"Invalid trace preview budget");const auto budget=std::stoull(budgetText);
    need(ruleVersion==RulesVersion&&contentVersion==ContentVersion&&manifest==rules.content().manifestHash,"Trace rules/content metadata differs from this build");need(policyVersion==PolicyVersion&&(policy=="aggressive"||policy=="defensive")&&(precision=="auto"||precision=="learning"||precision=="practised"||precision=="expert")&&budget>0,"Unsupported trace policy metadata");
    std::getline(trace,line);need(line.rfind("START ",0)==0,"Missing initial campaign");Campaign c;std::string error;const auto initial=unhex(line.substr(6));need(deserializeCampaign(initial,c,error),error);need(c.manifestHash==manifest,"Trace manifest differs from initial state");need(c.runId=="runner/"+std::to_string(c.seed)+"/"+policy+"/"+precision,"Trace policy metadata differs from campaign identity");need(initial==serializeCampaign(rules.newGame(c.seed,c.runId)),"Trace does not start at canonical Mara NewGame");std::size_t commands=0;bool lastOk=true;std::string lastReason;
    while(std::getline(trace,line)){if(line.rfind("FINAL ",0)==0){std::istringstream in(line.substr(6));std::string hash,outcome,encoded;in>>hash>>outcome>>encoded;exhausted(in,"Invalid final trace fields");need(hash==campaignHash(c)&&!encoded.empty()&&unhex(encoded)==serializeCampaign(c),"Final replay state bytes differ");
            const bool complete=c.phase==CityPhase::Complete,defeated=c.phase==CityPhase::Defeated,held=lastReason.find("owner decision")!=std::string::npos;
            const bool terminal=(outcome=="city_complete"&&complete&&lastOk)||(outcome=="defeat"&&defeated&&lastOk);
            const bool stopped=!complete&&!defeated&&((outcome=="blocked_rule"&&!lastOk&&held)||(outcome=="policy_error"&&!lastOk&&!held)||((outcome=="policy_timeout"||outcome=="unsupported_choice")&&lastOk));
            need(terminal||stopped,"Final outcome contradicts replayed campaign/result");need(!std::getline(trace,line),"Trailing data after final trace");return "Replayed "+std::to_string(commands)+" exact commands/events; final "+outcome+"; hash "+hash;}
        need(lastOk,"Unexpected action after a rejected runner command");need(line.rfind("A ",0)==0,"Expected trace action");CampaignAction a;need(decodeAction(unhex(line.substr(2)),a,error),error);const auto result=rules.apply(c,a);++commands;need(static_cast<bool>(std::getline(trace,line))&&line.rfind("R ",0)==0,"Missing action result");std::istringstream row(line.substr(2));bool ok=false;std::string reason,hash;std::size_t n=0;row>>ok>>std::quoted(reason)>>hash>>n;exhausted(row,"Invalid action result fields");need(ok==result.ok&&reason==result.reason&&hash==campaignHash(c)&&n==result.events.size(),"Command/state mismatch at "+std::to_string(commands));lastOk=ok;lastReason=reason;for(std::size_t i=0;i<n;++i){need(static_cast<bool>(std::getline(trace,line)),"Missing event");need(line=="E "+eventJson(result.events[i]),"Event mismatch at command "+std::to_string(commands));}}
    throw std::runtime_error("Trace ended without final state");
}
} // namespace overkill::runner
